import json

def analyze_career_data():
    with open('careers.json', 'r') as f:
        careers = json.load(f)

    with open('all_career_types.json', 'r') as f:
        all_career_types = json.load(f)

    # This is a simplified mapping based on the provided files.
    # A more robust solution would involve a clear mapping in the data source.
    category_map = {
        "Technology & Engineering": ["software-engineer", "full-stack-developer", "frontend-developer", "backend-developer", "mobile-app-developer", "devops-engineer", "cloud-solutions-engineer", "cybersecurity-analyst", "data-scientist", "senior-data-scientist", "data-science-manager", "ml-engineer", "solutions-architect", "qa-engineer", "technical-program-manager", "blockchain-developer", "embedded-systems-engineer", "game-developer", "aerospace-engineer", "mechanical-design-engineer", "chemical-engineer", "civil-engineer", "structural-engineer", "environmental-engineer", "power-systems-engineer", "electronics-engineer", "control-systems-engineer", "transportation-engineer", "chief-technology-officer", "vp-engineering", "engineering-manager", "senior-software-architect", "principal-engineer", "staff-engineer"],
        "Healthcare & Medical": ["family-medicine-physician", "cardiologist", "pediatrician", "general-surgeon", "orthopedic-surgeon", "neurologist", "emergency-medicine-physician", "dermatologist", "anesthesiologist", "registered-nurse", "nurse-practitioner", "critical-care-nurse", "pediatric-nurse", "operating-room-nurse", "nurse-anesthetist", "physical-therapist", "occupational-therapist", "radiologic-technologist", "speech-language-pathologist", "respiratory-therapist", "pharmacy-technician", "medical-laboratory-technologist", "ultrasound-technologist", "dietitian-nutritionist", "clinical-psychologist", "clinical-social-worker", "psychiatrist", "marriage-family-therapist", "substance-abuse-counselor", "medical-assistant", "healthcare-administrator", "medical-records-technician", "medical-billing-specialist", "health-information-manager", "patient-care-coordinator", "medical-equipment-technician", "hospital-social-worker", "pharmacist", "biomedical-engineer", "clinical-research-coordinator"],
        "Skilled Trades & Construction": ["electrician", "master-electrician", "electrical-engineer", "power-line-technician", "industrial-electrician", "electrical-inspector", "plumber", "hvac-technician", "master-plumber", "pipefitter", "hvac-engineer", "refrigeration-technician", "carpenter", "construction-manager", "mason", "roofer", "concrete-finisher", "drywall-installer", "flooring-installer", "construction-project-manager", "heavy-equipment-operator", "automotive-technician", "master-automotive-technician", "diesel-mechanic", "automotive-service-advisor", "auto-body-technician", "motorcycle-technician", "machinist", "welder", "tool-die-maker", "cnc-operator", "quality-control-inspector", "industrial-maintenance-technician", "millwright", "sheet-metal-worker", "boilermaker", "locksmith", "glazier", "insulation-worker", "elevator-technician"],
        "Education & Training": ["elementary-teacher", "high-school-teacher", "school-principal", "school-counselor", "middle-school-teacher", "special-education-teacher", "assistant-principal", "curriculum-coordinator", "school-psychologist", "reading-specialist", "esl-teacher", "substitute-teacher", "college-professor", "university-administrator", "academic-advisor", "research-scientist", "dean-of-students", "admissions-counselor", "registrar", "student-affairs-coordinator", "corporate-trainer", "instructional-designer", "learning-development-manager", "training-specialist", "elearning-developer", "od-consultant", "librarian", "edtech-specialist", "tutor", "educational-consultant", "education-program-coordinator", "academic-coach", "museum-educator", "adult-education-instructor", "educational-writer", "education-policy-analyst", "distance-learning-coordinator", "education-data-analyst", "preschool-teacher", "education-grant-writer"],
        "Business & Finance": ["cpa", "financial-analyst", "investment-banker", "controller", "auditor", "financial-planner", "budget-analyst", "credit-analyst", "treasury-analyst", "tax-specialist", "management-consultant", "operations-manager", "project-manager", "general-manager", "it-consultant", "strategy-consultant", "supply-chain-manager", "sales-manager", "marketing-manager", "business-development-manager", "sales-director", "marketing-analyst", "digital-marketing-specialist", "account-manager", "brand-manager", "hr-manager", "recruiter", "compensation-analyst", "training-development-manager", "hr-business-partner", "benefits-administrator", "business-analyst", "administrative-assistant", "executive-assistant", "data-analyst", "risk-manager", "compliance-officer", "quality-assurance-manager", "procurement-manager", "customer-success-manager", "product-manager", "logistics-coordinator", "financial-controller", "cfo"],
        "Legal & Law": ["Legal & Law"],
        "Creative & Arts": ["creative-director", "art-director", "head-of-design", "chief-creative-officer", "senior-ux-designer", "senior-graphic-designer", "motion-graphics-designer", "brand-designer", "creative-producer", "ux-ui-designer", "graphic-designer", "web-designer", "video-editor", "photographer", "illustrator", "junior-graphic-designer", "junior-ux-designer", "social-media-designer", "production-assistant", "content-creator", "art-teacher", "3d-artist", "game-artist", "concept-artist", "sound-designer", "animator"],
        "Public Service & Government": ["federal-agency-director", "deputy-secretary", "assistant-secretary", "senior-executive-service", "gs15-program-manager", "federal-policy-analyst", "federal-contracting-officer", "gs13-management-analyst", "federal-budget-analyst", "federal-hr-specialist", "federal-it-specialist", "gs11-program-analyst", "federal-administrative-officer", "state-agency-director", "state-program-manager", "state-policy-analyst", "state-social-worker", "city-manager", "county-administrator", "municipal-department-head", "city-planner", "municipal-finance-director", "police-chief", "fire-chief", "emergency-management-director", "police-detective", "firefighter-paramedic", "legislative-director", "congressional-staff-director", "legislative-analyst"],
        "Hospitality & Service": ["hotel-general-manager", "restaurant-chain-director", "tourism-director", "food-beverage-manager", "event-manager", "guest-services-manager", "catering-manager", "restaurant-manager", "front-desk-manager", "cruise-ship-officer", "banquet-manager", "hotel-front-desk-agent", "server-waitstaff", "tour-guide", "concierge", "bartender", "customer-service-representative", "housekeeper-room-attendant", "sommelier", "wedding-planner", "spa-manager"],
        "Manufacturing & Industrial": ["manufacturing-director", "plant-manager", "operations-director", "production-manager", "quality-assurance-manager", "industrial-engineer", "supply-chain-manager", "manufacturing-engineer", "process-engineer", "quality-control-specialist", "production-supervisor", "maintenance-manager", "production-worker", "quality-inspector", "machine-operator", "warehouse-associate", "assembly-line-worker", "automation-engineer", "safety-manager", "lean-manufacturing-specialist", "materials-manager", "industrial-maintenance-technician"],
        "Agriculture & Environment": ["agricultural-operations-director", "environmental-director", "conservation-director", "farm-manager", "environmental-scientist", "forestry-manager", "agricultural-engineer", "agronomist", "environmental-consultant", "wildlife-biologist", "soil-scientist", "sustainable-agriculture-specialist", "farm-worker", "environmental-technician", "park-ranger", "greenhouse-worker", "conservation-technician", "organic-farm-manager", "water-resource-specialist", "climate-change-analyst", "renewable-energy-specialist", "environmental-educator"],
        "Product Management": ["chief-product-officer", "vp-product", "head-of-product", "director-product-management", "principal-product-manager", "group-product-manager", "senior-product-manager", "product-manager", "technical-product-manager", "growth-product-manager", "platform-product-manager", "junior-product-manager"],
        "Engineering": ["aerospace-engineer", "mechanical-design-engineer", "chemical-engineer", "civil-engineer", "structural-engineer", "environmental-engineer", "power-systems-engineer", "electronics-engineer", "control-systems-engineer", "transportation-engineer"]
    }

    category_counts = {category: 0 for category in category_map.keys()}
    
    career_types_in_careers_json = {career['careerType'] for career in careers}

    for category, types in category_map.items():
        for career_type in types:
            if career_type in career_types_in_careers_json:
                category_counts[category] += 1

    print(json.dumps(category_counts, indent=2))
    print(f"\nTotal careers in careers.json: {len(careers)}")
    print(f"Total unique career types in all_career_types.json: {len(set(all_career_types))}")

if __name__ == "__main__":
    analyze_career_data()