"""
Agriculture & Environment careers database with comprehensive career options.
Covers farming, environmental science, conservation, forestry, and sustainable agriculture.
"""

AGRICULTURE_ENVIRONMENT_CAREERS = [
    # EXECUTIVE LEVEL (15+ years, $120k+)
    {
        "title": "Agricultural Operations Director",
        "careerType": "agricultural-operations-director",
        "description": "Lead large-scale agricultural operations, manage multiple farms, drive sustainable farming practices.",
        "salaryRange": "$150,000 - $220,000",
        "experienceLevel": "executive",
        "requiredTechnicalSkills": ["Agricultural Management", "Sustainable Farming", "Supply Chain Management", "Financial Planning", "Team Leadership"],
        "requiredSoftSkills": ["Executive Leadership", "Strategic Planning", "Communication", "Problem Solving", "Environmental Awareness"],
        "companies": ["Cargill", "ADM", "Tyson Foods", "John Deere", "Monsanto", "Large Farming Operations"],
        "learningPath": "Agricultural Leadership Program (6-12 months)",
        "relevanceScore": 82,
        "confidenceLevel": 80,
        "matchReasons": ["Agricultural expertise", "Operations leadership", "Sustainability focus"],
        "minExperienceYears": 15,
        "maxExperienceYears": 30,
        "minSalary": 150000,
        "maxSalary": 220000
    },
    {
        "title": "Environmental Director",
        "careerType": "environmental-director",
        "description": "Lead environmental programs, ensure regulatory compliance, drive sustainability initiatives.",
        "salaryRange": "$140,000 - $200,000",
        "experienceLevel": "executive",
        "requiredTechnicalSkills": ["Environmental Management", "Regulatory Compliance", "Sustainability Programs", "Environmental Impact Assessment", "Team Leadership"],
        "requiredSoftSkills": ["Executive Leadership", "Strategic Thinking", "Communication", "Problem Solving", "Environmental Passion"],
        "companies": ["EPA", "Environmental Consulting Firms", "Large Corporations", "Non-profits", "Government Agencies", "Utilities"],
        "learningPath": "Environmental Leadership Program (6-8 months)",
        "relevanceScore": 85,
        "confidenceLevel": 82,
        "matchReasons": ["Environmental leadership", "Regulatory expertise", "Sustainability focus"],
        "minExperienceYears": 12,
        "maxExperienceYears": 25,
        "minSalary": 140000,
        "maxSalary": 200000
    },
    {
        "title": "Conservation Director",
        "careerType": "conservation-director",
        "description": "Lead conservation programs, manage natural resources, coordinate with stakeholders on environmental protection.",
        "salaryRange": "$120,000 - $180,000",
        "experienceLevel": "executive",
        "requiredTechnicalSkills": ["Conservation Biology", "Natural Resource Management", "Environmental Policy", "Grant Writing", "Program Management"],
        "requiredSoftSkills": ["Leadership", "Communication", "Strategic Planning", "Stakeholder Management", "Environmental Passion"],
        "companies": ["Nature Conservancy", "WWF", "National Parks Service", "State Environmental Agencies", "Conservation Organizations", "Zoos"],
        "learningPath": "Conservation Leadership Program (4-6 months)",
        "relevanceScore": 80,
        "confidenceLevel": 78,
        "matchReasons": ["Conservation expertise", "Environmental leadership", "Program management"],
        "minExperienceYears": 10,
        "maxExperienceYears": 20,
        "minSalary": 120000,
        "maxSalary": 180000
    },

    # SENIOR LEVEL (8-15 years, $70k-130k)
    {
        "title": "Farm Manager",
        "careerType": "farm-manager",
        "description": "Manage farm operations, oversee crop production, coordinate with workers, ensure profitability.",
        "salaryRange": "$75,000 - $120,000",
        "experienceLevel": "senior",
        "requiredTechnicalSkills": ["Farm Management", "Crop Production", "Livestock Management", "Agricultural Technology", "Financial Management"],
        "requiredSoftSkills": ["Leadership", "Problem Solving", "Communication", "Planning", "Weather Awareness"],
        "companies": ["Large Farms", "Agricultural Cooperatives", "Agribusiness Companies", "Ranch Operations", "Dairy Farms", "Organic Farms"],
        "learningPath": "Farm Management Certification (4-6 months)",
        "relevanceScore": 88,
        "confidenceLevel": 85,
        "matchReasons": ["Agricultural management", "Operations leadership", "Production expertise"],
        "minExperienceYears": 8,
        "maxExperienceYears": 15,
        "minSalary": 75000,
        "maxSalary": 120000
    },
    {
        "title": "Environmental Scientist",
        "careerType": "environmental-scientist",
        "description": "Conduct environmental research, assess environmental impacts, develop solutions for environmental problems.",
        "salaryRange": "$70,000 - $110,000",
        "experienceLevel": "senior",
        "requiredTechnicalSkills": ["Environmental Science", "Data Analysis", "Field Research", "Environmental Monitoring", "Report Writing"],
        "requiredSoftSkills": ["Analytical Thinking", "Problem Solving", "Communication", "Attention to Detail", "Environmental Awareness"],
        "companies": ["EPA", "Environmental Consulting", "Research Institutions", "Government Agencies", "Non-profits", "Universities"],
        "learningPath": "Environmental Science Specialization (4-6 months)",
        "relevanceScore": 85,
        "confidenceLevel": 82,
        "matchReasons": ["Scientific research", "Environmental focus", "Data analysis"],
        "minExperienceYears": 6,
        "maxExperienceYears": 12,
        "minSalary": 70000,
        "maxSalary": 110000
    },
    {
        "title": "Forestry Manager",
        "careerType": "forestry-manager",
        "description": "Manage forest resources, plan timber harvests, ensure sustainable forestry practices.",
        "salaryRange": "$65,000 - $100,000",
        "experienceLevel": "senior",
        "requiredTechnicalSkills": ["Forest Management", "Timber Harvesting", "Wildlife Management", "GIS Mapping", "Environmental Regulations"],
        "requiredSoftSkills": ["Leadership", "Planning", "Communication", "Problem Solving", "Environmental Stewardship"],
        "companies": ["US Forest Service", "State Forestry Departments", "Timber Companies", "Paper Companies", "Conservation Organizations", "Private Landowners"],
        "learningPath": "Forestry Management Program (4-6 months)",
        "relevanceScore": 82,
        "confidenceLevel": 80,
        "matchReasons": ["Natural resource management", "Environmental stewardship", "Planning skills"],
        "minExperienceYears": 6,
        "maxExperienceYears": 12,
        "minSalary": 65000,
        "maxSalary": 100000
    },
    {
        "title": "Agricultural Engineer",
        "careerType": "agricultural-engineer",
        "description": "Design agricultural systems, develop farming equipment, optimize agricultural processes.",
        "salaryRange": "$80,000 - $120,000",
        "experienceLevel": "senior",
        "requiredTechnicalSkills": ["Agricultural Engineering", "Equipment Design", "Irrigation Systems", "CAD Software", "Project Management"],
        "requiredSoftSkills": ["Problem Solving", "Innovation", "Communication", "Analytical Thinking", "Project Management"],
        "companies": ["John Deere", "Case IH", "New Holland", "Agricultural Equipment Companies", "Engineering Firms", "Government Agencies"],
        "learningPath": "Agricultural Engineering Program (4-6 months)",
        "relevanceScore": 85,
        "confidenceLevel": 82,
        "matchReasons": ["Engineering expertise", "Agricultural technology", "Innovation focus"],
        "minExperienceYears": 5,
        "maxExperienceYears": 12,
        "minSalary": 80000,
        "maxSalary": 120000
    },

    # MID LEVEL (4-8 years, $45k-80k)
    {
        "title": "Agronomist",
        "careerType": "agronomist",
        "description": "Study crop production, soil management, provide recommendations to farmers for optimal yields.",
        "salaryRange": "$55,000 - $85,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Crop Science", "Soil Science", "Plant Pathology", "Pest Management", "Data Analysis"],
        "requiredSoftSkills": ["Analytical Thinking", "Communication", "Problem Solving", "Attention to Detail", "Farmer Relations"],
        "companies": ["Agricultural Cooperatives", "Seed Companies", "Fertilizer Companies", "Extension Services", "Research Institutions", "Consulting Firms"],
        "learningPath": "Agronomy Certification (3-4 months)",
        "relevanceScore": 88,
        "confidenceLevel": 85,
        "matchReasons": ["Agricultural science", "Problem solving", "Technical expertise"],
        "minExperienceYears": 4,
        "maxExperienceYears": 8,
        "minSalary": 55000,
        "maxSalary": 85000
    },
    {
        "title": "Environmental Consultant",
        "careerType": "environmental-consultant",
        "description": "Assess environmental impacts, ensure regulatory compliance, provide environmental solutions to clients.",
        "salaryRange": "$60,000 - $90,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Environmental Assessment", "Regulatory Knowledge", "Environmental Monitoring", "Report Writing", "Client Relations"],
        "requiredSoftSkills": ["Communication", "Problem Solving", "Analytical Thinking", "Attention to Detail", "Client Service"],
        "companies": ["Environmental Consulting Firms", "Engineering Companies", "Government Contractors", "Utilities", "Manufacturing Companies", "Real Estate"],
        "learningPath": "Environmental Consulting Certification (3-4 months)",
        "relevanceScore": 82,
        "confidenceLevel": 80,
        "matchReasons": ["Environmental expertise", "Consulting skills", "Regulatory knowledge"],
        "minExperienceYears": 3,
        "maxExperienceYears": 8,
        "minSalary": 60000,
        "maxSalary": 90000
    },
    {
        "title": "Wildlife Biologist",
        "careerType": "wildlife-biologist",
        "description": "Study wildlife populations, conduct field research, develop conservation strategies.",
        "salaryRange": "$50,000 - $75,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Wildlife Biology", "Field Research", "Data Collection", "Statistical Analysis", "GIS Mapping"],
        "requiredSoftSkills": ["Observation Skills", "Patience", "Communication", "Problem Solving", "Environmental Passion"],
        "companies": ["Fish & Wildlife Service", "State Wildlife Agencies", "National Parks", "Conservation Organizations", "Research Institutions", "Zoos"],
        "learningPath": "Wildlife Biology Specialization (3-4 months)",
        "relevanceScore": 80,
        "confidenceLevel": 78,
        "matchReasons": ["Scientific research", "Wildlife interest", "Field work"],
        "minExperienceYears": 3,
        "maxExperienceYears": 8,
        "minSalary": 50000,
        "maxSalary": 75000
    },
    {
        "title": "Soil Scientist",
        "careerType": "soil-scientist",
        "description": "Study soil properties, assess soil health, provide recommendations for land use and agriculture.",
        "salaryRange": "$55,000 - $80,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Soil Science", "Laboratory Analysis", "Field Sampling", "GIS Mapping", "Data Analysis"],
        "requiredSoftSkills": ["Analytical Thinking", "Attention to Detail", "Communication", "Problem Solving", "Scientific Method"],
        "companies": ["USDA", "Environmental Consulting", "Agricultural Companies", "Research Institutions", "Government Agencies", "Universities"],
        "learningPath": "Soil Science Certification (3-4 months)",
        "relevanceScore": 82,
        "confidenceLevel": 80,
        "matchReasons": ["Scientific analysis", "Agricultural focus", "Environmental science"],
        "minExperienceYears": 3,
        "maxExperienceYears": 8,
        "minSalary": 55000,
        "maxSalary": 80000
    },
    {
        "title": "Sustainable Agriculture Specialist",
        "careerType": "sustainable-agriculture-specialist",
        "description": "Promote sustainable farming practices, develop organic programs, educate farmers on eco-friendly methods.",
        "salaryRange": "$50,000 - $75,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Sustainable Agriculture", "Organic Farming", "Permaculture", "Soil Health", "Integrated Pest Management"],
        "requiredSoftSkills": ["Communication", "Teaching", "Problem Solving", "Environmental Passion", "Farmer Relations"],
        "companies": ["Extension Services", "Organic Certification Bodies", "Non-profits", "Agricultural Cooperatives", "Sustainable Farms", "Government Agencies"],
        "learningPath": "Sustainable Agriculture Program (3-4 months)",
        "relevanceScore": 85,
        "confidenceLevel": 82,
        "matchReasons": ["Sustainability focus", "Agricultural expertise", "Environmental awareness"],
        "minExperienceYears": 3,
        "maxExperienceYears": 8,
        "minSalary": 50000,
        "maxSalary": 75000
    },

    # JUNIOR LEVEL (0-4 years, $30k-55k)
    {
        "title": "Farm Worker",
        "careerType": "farm-worker",
        "description": "Perform agricultural tasks, plant and harvest crops, care for livestock, operate farm equipment.",
        "salaryRange": "$30,000 - $45,000",
        "experienceLevel": "junior",
        "requiredTechnicalSkills": ["Farm Operations", "Equipment Operation", "Crop Care", "Livestock Care", "Safety Procedures"],
        "requiredSoftSkills": ["Physical Stamina", "Reliability", "Teamwork", "Weather Tolerance", "Attention to Detail"],
        "companies": ["Farms", "Ranches", "Agricultural Cooperatives", "Dairy Operations", "Organic Farms", "Seasonal Operations"],
        "learningPath": "Farm Operations Training (1-2 months)",
        "relevanceScore": 75,
        "confidenceLevel": 72,
        "matchReasons": ["Agricultural work", "Hands-on experience", "Outdoor work"],
        "minExperienceYears": 0,
        "maxExperienceYears": 3,
        "minSalary": 30000,
        "maxSalary": 45000
    },
    {
        "title": "Environmental Technician",
        "careerType": "environmental-technician",
        "description": "Collect environmental samples, monitor pollution levels, assist with environmental assessments.",
        "salaryRange": "$35,000 - $50,000",
        "experienceLevel": "junior",
        "requiredTechnicalSkills": ["Sample Collection", "Environmental Monitoring", "Laboratory Procedures", "Data Recording", "Safety Protocols"],
        "requiredSoftSkills": ["Attention to Detail", "Reliability", "Communication", "Problem Solving", "Environmental Awareness"],
        "companies": ["Environmental Consulting", "Government Agencies", "Laboratories", "Utilities", "Manufacturing Companies", "Research Institutions"],
        "learningPath": "Environmental Technician Training (2-3 months)",
        "relevanceScore": 80,
        "confidenceLevel": 78,
        "matchReasons": ["Environmental focus", "Technical skills", "Field work"],
        "minExperienceYears": 0,
        "maxExperienceYears": 4,
        "minSalary": 35000,
        "maxSalary": 50000
    },
    {
        "title": "Park Ranger",
        "careerType": "park-ranger",
        "description": "Protect natural resources, educate visitors, maintain park facilities, ensure visitor safety.",
        "salaryRange": "$38,000 - $55,000",
        "experienceLevel": "junior",
        "requiredTechnicalSkills": ["Natural Resource Management", "Visitor Services", "Safety Procedures", "Environmental Education", "Emergency Response"],
        "requiredSoftSkills": ["Communication", "Leadership", "Problem Solving", "Physical Fitness", "Environmental Passion"],
        "companies": ["National Park Service", "State Parks", "Local Parks", "Forest Service", "Wildlife Refuges", "Conservation Organizations"],
        "learningPath": "Park Ranger Training (2-3 months)",
        "relevanceScore": 82,
        "confidenceLevel": 80,
        "matchReasons": ["Environmental protection", "Public service", "Outdoor work"],
        "minExperienceYears": 0,
        "maxExperienceYears": 4,
        "minSalary": 38000,
        "maxSalary": 55000
    },
    {
        "title": "Greenhouse Worker",
        "careerType": "greenhouse-worker",
        "description": "Care for plants in greenhouse settings, monitor growing conditions, assist with plant propagation.",
        "salaryRange": "$32,000 - $45,000",
        "experienceLevel": "junior",
        "requiredTechnicalSkills": ["Plant Care", "Greenhouse Operations", "Irrigation Systems", "Pest Management", "Climate Control"],
        "requiredSoftSkills": ["Attention to Detail", "Patience", "Physical Stamina", "Reliability", "Plant Interest"],
        "companies": ["Nurseries", "Garden Centers", "Research Institutions", "Universities", "Botanical Gardens", "Commercial Growers"],
        "learningPath": "Greenhouse Operations Training (1-2 months)",
        "relevanceScore": 78,
        "confidenceLevel": 75,
        "matchReasons": ["Plant care", "Controlled environment", "Agricultural interest"],
        "minExperienceYears": 0,
        "maxExperienceYears": 3,
        "minSalary": 32000,
        "maxSalary": 45000
    },
    {
        "title": "Conservation Technician",
        "careerType": "conservation-technician",
        "description": "Assist with conservation projects, maintain trails and facilities, support wildlife monitoring.",
        "salaryRange": "$33,000 - $48,000",
        "experienceLevel": "junior",
        "requiredTechnicalSkills": ["Conservation Practices", "Trail Maintenance", "Wildlife Monitoring", "Data Collection", "Equipment Operation"],
        "requiredSoftSkills": ["Physical Fitness", "Teamwork", "Environmental Awareness", "Reliability", "Problem Solving"],
        "companies": ["Conservation Organizations", "National Parks", "State Agencies", "Non-profits", "Environmental Groups", "Land Trusts"],
        "learningPath": "Conservation Technician Training (1-2 months)",
        "relevanceScore": 80,
        "confidenceLevel": 78,
        "matchReasons": ["Conservation work", "Environmental focus", "Hands-on experience"],
        "minExperienceYears": 0,
        "maxExperienceYears": 3,
        "minSalary": 33000,
        "maxSalary": 48000
    },

    # SPECIALIZED AGRICULTURE & ENVIRONMENT ROLES
    {
        "title": "Organic Farm Manager",
        "careerType": "organic-farm-manager",
        "description": "Manage organic farming operations, ensure organic certification compliance, oversee sustainable practices.",
        "salaryRange": "$60,000 - $90,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Organic Farming", "Certification Standards", "Sustainable Agriculture", "Crop Rotation", "Natural Pest Control"],
        "requiredSoftSkills": ["Leadership", "Environmental Passion", "Problem Solving", "Communication", "Planning"],
        "companies": ["Organic Farms", "Whole Foods", "Organic Cooperatives", "Sustainable Agriculture Organizations", "CSA Operations", "Farmers Markets"],
        "learningPath": "Organic Farm Management (3-4 months)",
        "relevanceScore": 88,
        "confidenceLevel": 85,
        "matchReasons": ["Organic agriculture", "Sustainability focus", "Farm management"],
        "minExperienceYears": 4,
        "maxExperienceYears": 10,
        "minSalary": 60000,
        "maxSalary": 90000
    },
    {
        "title": "Water Resource Specialist",
        "careerType": "water-resource-specialist",
        "description": "Manage water resources, assess water quality, develop water conservation programs.",
        "salaryRange": "$55,000 - $85,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Water Management", "Hydrology", "Water Quality Testing", "GIS Mapping", "Environmental Regulations"],
        "requiredSoftSkills": ["Analytical Thinking", "Problem Solving", "Communication", "Attention to Detail", "Environmental Awareness"],
        "companies": ["Water Districts", "Environmental Consulting", "Government Agencies", "Utilities", "Engineering Firms", "Non-profits"],
        "learningPath": "Water Resource Management (3-4 months)",
        "relevanceScore": 82,
        "confidenceLevel": 80,
        "matchReasons": ["Water management", "Environmental science", "Resource conservation"],
        "minExperienceYears": 3,
        "maxExperienceYears": 8,
        "minSalary": 55000,
        "maxSalary": 85000
    },
    {
        "title": "Climate Change Analyst",
        "careerType": "climate-change-analyst",
        "description": "Study climate patterns, assess climate impacts, develop adaptation and mitigation strategies.",
        "salaryRange": "$65,000 - $95,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Climate Science", "Data Analysis", "Statistical Modeling", "GIS", "Research Methods"],
        "requiredSoftSkills": ["Analytical Thinking", "Communication", "Problem Solving", "Attention to Detail", "Environmental Passion"],
        "companies": ["NOAA", "EPA", "Research Institutions", "Environmental Consulting", "Non-profits", "Government Agencies"],
        "learningPath": "Climate Science Specialization (4-6 months)",
        "relevanceScore": 85,
        "confidenceLevel": 82,
        "matchReasons": ["Climate expertise", "Data analysis", "Environmental science"],
        "minExperienceYears": 4,
        "maxExperienceYears": 10,
        "minSalary": 65000,
        "maxSalary": 95000
    },
    {
        "title": "Renewable Energy Specialist",
        "careerType": "renewable-energy-specialist",
        "description": "Develop renewable energy projects, assess site feasibility, promote clean energy adoption.",
        "salaryRange": "$70,000 - $100,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Renewable Energy", "Solar/Wind Technology", "Energy Analysis", "Project Management", "Environmental Assessment"],
        "requiredSoftSkills": ["Innovation", "Problem Solving", "Communication", "Project Management", "Environmental Passion"],
        "companies": ["Solar Companies", "Wind Energy Companies", "Utilities", "Environmental Consulting", "Government Agencies", "Non-profits"],
        "learningPath": "Renewable Energy Certification (3-4 months)",
        "relevanceScore": 88,
        "confidenceLevel": 85,
        "matchReasons": ["Clean energy focus", "Environmental technology", "Innovation"],
        "minExperienceYears": 4,
        "maxExperienceYears": 10,
        "minSalary": 70000,
        "maxSalary": 100000
    },
    {
        "title": "Environmental Educator",
        "careerType": "environmental-educator",
        "description": "Teach environmental concepts, develop educational programs, promote environmental awareness.",
        "salaryRange": "$40,000 - $65,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Environmental Education", "Curriculum Development", "Program Planning", "Public Speaking", "Environmental Science"],
        "requiredSoftSkills": ["Teaching", "Communication", "Creativity", "Patience", "Environmental Passion"],
        "companies": ["Nature Centers", "Museums", "Schools", "Non-profits", "Parks", "Environmental Organizations"],
        "learningPath": "Environmental Education Certification (2-3 months)",
        "relevanceScore": 80,
        "confidenceLevel": 78,
        "matchReasons": ["Education focus", "Environmental awareness", "Communication skills"],
        "minExperienceYears": 2,
        "maxExperienceYears": 8,
        "minSalary": 40000,
        "maxSalary": 65000
    }
]