"""
Business & Finance Career Database
Part of comprehensive career database expansion
"""

BUSINESS_FINANCE_CAREERS = [
    # ACCOUNTING & FINANCE
    {
        "title": "Certified Public Accountant (CPA)",
        "careerType": "cpa",
        "description": "Prepare and examine financial records, ensure compliance with tax laws, provide financial advice.",
        "salaryRange": "$65,000 - $95,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Accounting", "Tax Preparation", "Financial Analysis", "Auditing"],
        "requiredSoftSkills": ["Attention to Detail", "Analytical Thinking", "Communication", "Ethics"],
        "companies": ["Accounting Firms", "Corporations", "Government", "Non-Profits"],
        "learningPath": "Bachelor's in Accounting + CPA License (4-6 years)",
        "relevanceScore": 82,
        "confidenceLevel": 85,
        "matchReasons": ["Financial expertise", "Analytical skills", "Professional certification"],
        "minExperienceYears": 2,
        "maxExperienceYears": 40,
        "minSalary": 65000,
        "maxSalary": 95000
    },
    {
        "title": "Financial Analyst",
        "careerType": "financial-analyst",
        "description": "Analyze financial data, create investment recommendations, assess business performance and market trends.",
        "salaryRange": "$70,000 - $105,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Financial Modeling", "Data Analysis", "Excel", "Investment Analysis"],
        "requiredSoftSkills": ["Analytical Thinking", "Communication", "Attention to Detail", "Problem Solving"],
        "companies": ["Investment Banks", "Corporations", "Consulting Firms", "Asset Management"],
        "learningPath": "Bachelor's in Finance/Economics + CFA (4-6 years)",
        "relevanceScore": 85,
        "confidenceLevel": 88,
        "matchReasons": ["Financial analysis", "Data-driven decisions", "Market research"],
        "minExperienceYears": 2,
        "maxExperienceYears": 25,
        "minSalary": 70000,
        "maxSalary": 105000
    },
    {
        "title": "Investment Banker",
        "careerType": "investment-banker",
        "description": "Help companies raise capital, facilitate mergers and acquisitions, provide financial advisory services.",
        "salaryRange": "$120,000 - $200,000",
        "experienceLevel": "senior",
        "requiredTechnicalSkills": ["Financial Modeling", "Valuation", "M&A", "Capital Markets"],
        "requiredSoftSkills": ["Communication", "Negotiation", "Stress Management", "Client Relations"],
        "companies": ["Goldman Sachs", "Morgan Stanley", "JP Morgan", "Bank of America"],
        "learningPath": "Bachelor's in Finance + MBA (6-8 years)",
        "relevanceScore": 80,
        "confidenceLevel": 82,
        "matchReasons": ["High-level finance", "Deal making", "Client advisory"],
        "minExperienceYears": 4,
        "maxExperienceYears": 30,
        "minSalary": 120000,
        "maxSalary": 200000
    },
    {
        "title": "Controller",
        "careerType": "controller",
        "description": "Oversee accounting operations, manage financial reporting, ensure regulatory compliance.",
        "salaryRange": "$95,000 - $140,000",
        "experienceLevel": "senior",
        "requiredTechnicalSkills": ["Accounting", "Financial Reporting", "Budgeting", "Compliance"],
        "requiredSoftSkills": ["Leadership", "Communication", "Problem Solving", "Attention to Detail"],
        "companies": ["Corporations", "Non-Profits", "Government", "Healthcare"],
        "learningPath": "CPA + Management Experience (8-12 years)",
        "relevanceScore": 85,
        "confidenceLevel": 88,
        "matchReasons": ["Financial leadership", "Accounting expertise", "Management skills"],
        "minExperienceYears": 8,
        "maxExperienceYears": 35,
        "minSalary": 95000,
        "maxSalary": 140000
    },

    # MANAGEMENT & CONSULTING
    {
        "title": "Management Consultant",
        "careerType": "management-consultant",
        "description": "Analyze business problems, develop solutions, help organizations improve performance and efficiency.",
        "salaryRange": "$85,000 - $130,000",
        "experienceLevel": "senior",
        "requiredTechnicalSkills": ["Business Analysis", "Strategy Development", "Process Improvement", "Data Analysis"],
        "requiredSoftSkills": ["Problem Solving", "Communication", "Leadership", "Analytical Thinking"],
        "companies": ["McKinsey", "BCG", "Bain", "Deloitte", "Accenture"],
        "learningPath": "Bachelor's + MBA (6-8 years)",
        "relevanceScore": 88,
        "confidenceLevel": 90,
        "matchReasons": ["Strategic thinking", "Problem solving", "Business improvement"],
        "minExperienceYears": 4,
        "maxExperienceYears": 30,
        "minSalary": 85000,
        "maxSalary": 130000
    },
    {
        "title": "Operations Manager",
        "careerType": "operations-manager",
        "description": "Oversee daily operations, manage teams, optimize processes, ensure quality and efficiency.",
        "salaryRange": "$75,000 - $110,000",
        "experienceLevel": "senior",
        "requiredTechnicalSkills": ["Operations Management", "Process Improvement", "Budget Management", "Quality Control"],
        "requiredSoftSkills": ["Leadership", "Communication", "Problem Solving", "Organization"],
        "companies": ["Manufacturing", "Retail", "Healthcare", "Technology"],
        "learningPath": "Bachelor's + Management Experience (6-10 years)",
        "relevanceScore": 82,
        "confidenceLevel": 85,
        "matchReasons": ["Operations expertise", "Team leadership", "Process optimization"],
        "minExperienceYears": 6,
        "maxExperienceYears": 35,
        "minSalary": 75000,
        "maxSalary": 110000
    },
    {
        "title": "Project Manager",
        "careerType": "project-manager",
        "description": "Plan and execute projects, manage resources and timelines, coordinate teams, ensure deliverables.",
        "salaryRange": "$70,000 - $105,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Project Management", "Agile/Scrum", "Risk Management", "Budget Management"],
        "requiredSoftSkills": ["Leadership", "Communication", "Organization", "Problem Solving"],
        "companies": ["Technology", "Construction", "Healthcare", "Consulting"],
        "learningPath": "Bachelor's + PMP Certification (4-6 years)",
        "relevanceScore": 85,
        "confidenceLevel": 88,
        "matchReasons": ["Project coordination", "Team leadership", "Delivery focus"],
        "minExperienceYears": 3,
        "maxExperienceYears": 30,
        "minSalary": 70000,
        "maxSalary": 105000
    },

    # SALES & MARKETING
    {
        "title": "Sales Manager",
        "careerType": "sales-manager",
        "description": "Lead sales teams, develop sales strategies, manage client relationships, achieve revenue targets.",
        "salaryRange": "$80,000 - $120,000",
        "experienceLevel": "senior",
        "requiredTechnicalSkills": ["Sales Management", "CRM Software", "Sales Analytics", "Territory Management"],
        "requiredSoftSkills": ["Leadership", "Communication", "Negotiation", "Motivation"],
        "companies": ["Technology", "Pharmaceuticals", "Manufacturing", "Services"],
        "learningPath": "Bachelor's + Sales Experience (6-10 years)",
        "relevanceScore": 80,
        "confidenceLevel": 82,
        "matchReasons": ["Sales leadership", "Revenue generation", "Team management"],
        "minExperienceYears": 6,
        "maxExperienceYears": 35,
        "minSalary": 80000,
        "maxSalary": 120000
    },
    {
        "title": "Marketing Manager",
        "careerType": "marketing-manager",
        "description": "Develop marketing strategies, manage campaigns, analyze market trends, oversee marketing teams.",
        "salaryRange": "$70,000 - $105,000",
        "experienceLevel": "senior",
        "requiredTechnicalSkills": ["Marketing Strategy", "Digital Marketing", "Analytics", "Brand Management"],
        "requiredSoftSkills": ["Creativity", "Communication", "Leadership", "Analytical Thinking"],
        "companies": ["Consumer Goods", "Technology", "Healthcare", "Retail"],
        "learningPath": "Bachelor's in Marketing + Experience (5-8 years)",
        "relevanceScore": 82,
        "confidenceLevel": 85,
        "matchReasons": ["Marketing expertise", "Brand development", "Campaign management"],
        "minExperienceYears": 5,
        "maxExperienceYears": 30,
        "minSalary": 70000,
        "maxSalary": 105000
    },
    {
        "title": "Business Development Manager",
        "careerType": "business-development-manager",
        "description": "Identify growth opportunities, develop partnerships, expand market presence, drive revenue growth.",
        "salaryRange": "$75,000 - $115,000",
        "experienceLevel": "senior",
        "requiredTechnicalSkills": ["Business Development", "Market Analysis", "Partnership Management", "Sales"],
        "requiredSoftSkills": ["Relationship Building", "Communication", "Strategic Thinking", "Negotiation"],
        "companies": ["Technology", "Consulting", "Healthcare", "Financial Services"],
        "learningPath": "Bachelor's + Business Development Experience (5-8 years)",
        "relevanceScore": 85,
        "confidenceLevel": 88,
        "matchReasons": ["Growth focus", "Partnership building", "Strategic development"],
        "minExperienceYears": 5,
        "maxExperienceYears": 30,
        "minSalary": 75000,
        "maxSalary": 115000
    },

    # HUMAN RESOURCES
    {
        "title": "HR Manager",
        "careerType": "hr-manager",
        "description": "Manage human resources functions, recruit talent, handle employee relations, ensure compliance.",
        "salaryRange": "$70,000 - $100,000",
        "experienceLevel": "senior",
        "requiredTechnicalSkills": ["HR Management", "Recruitment", "Employee Relations", "Compliance"],
        "requiredSoftSkills": ["Communication", "Empathy", "Problem Solving", "Confidentiality"],
        "companies": ["Corporations", "Non-Profits", "Government", "Healthcare"],
        "learningPath": "Bachelor's in HR + SHRM Certification (5-8 years)",
        "relevanceScore": 80,
        "confidenceLevel": 82,
        "matchReasons": ["People management", "Organizational development", "Employee support"],
        "minExperienceYears": 5,
        "maxExperienceYears": 35,
        "minSalary": 70000,
        "maxSalary": 100000
    },
    {
        "title": "Recruiter",
        "careerType": "recruiter",
        "description": "Source and recruit candidates, conduct interviews, manage hiring process, build talent pipelines.",
        "salaryRange": "$50,000 - $75,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Recruiting", "Interviewing", "ATS Software", "Sourcing"],
        "requiredSoftSkills": ["Communication", "Relationship Building", "Persuasion", "Organization"],
        "companies": ["Recruiting Firms", "Corporations", "Staffing Agencies"],
        "learningPath": "Bachelor's + Recruiting Experience (3-5 years)",
        "relevanceScore": 75,
        "confidenceLevel": 78,
        "matchReasons": ["People skills", "Talent identification", "Relationship building"],
        "minExperienceYears": 2,
        "maxExperienceYears": 25,
        "minSalary": 50000,
        "maxSalary": 75000
    },

    # ENTRY LEVEL BUSINESS
    {
        "title": "Business Analyst",
        "careerType": "business-analyst",
        "description": "Analyze business processes, identify improvement opportunities, gather requirements, support decision making.",
        "salaryRange": "$60,000 - $85,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Business Analysis", "Data Analysis", "Process Mapping", "Requirements Gathering"],
        "requiredSoftSkills": ["Analytical Thinking", "Communication", "Problem Solving", "Attention to Detail"],
        "companies": ["Consulting", "Technology", "Healthcare", "Financial Services"],
        "learningPath": "Bachelor's + Business Analysis Certification (3-5 years)",
        "relevanceScore": 85,
        "confidenceLevel": 88,
        "matchReasons": ["Analytical skills", "Process improvement", "Business understanding"],
        "minExperienceYears": 2,
        "maxExperienceYears": 20,
        "minSalary": 60000,
        "maxSalary": 85000
    },
    {
        "title": "Administrative Assistant",
        "careerType": "administrative-assistant",
        "description": "Provide administrative support, manage schedules, handle correspondence, organize meetings.",
        "salaryRange": "$35,000 - $50,000",
        "experienceLevel": "junior",
        "requiredTechnicalSkills": ["Office Software", "Scheduling", "Data Entry", "Communication"],
        "requiredSoftSkills": ["Organization", "Communication", "Attention to Detail", "Multitasking"],
        "companies": ["All Industries", "Government", "Non-Profits", "Healthcare"],
        "learningPath": "High School + Office Skills Training (1-2 years)",
        "relevanceScore": 65,
        "confidenceLevel": 70,
        "matchReasons": ["Organizational skills", "Support role", "Office environment"],
        "minExperienceYears": 0,
        "maxExperienceYears": 30,
        "minSalary": 35000,
        "maxSalary": 50000
    }
]