"""
Business & Finance Career Database
Part of comprehensive career database expansion
"""

BUSINESS_FINANCE_CAREERS = [
    # ACCOUNTING & FINANCE
    {
        "title": "Certified Public Accountant (CPA)",
        "careerType": "cpa",
        "description": "Prepare and examine financial records, ensure compliance with tax laws, provide financial advice.",
        "salaryRange": "$65,000 - $95,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Accounting", "Tax Preparation", "Financial Analysis", "Auditing"],
        "requiredSoftSkills": ["Attention to Detail", "Analytical Thinking", "Communication", "Ethics"],
        "companies": ["Accounting Firms", "Corporations", "Government", "Non-Profits"],
        "learningPath": "Bachelor's in Accounting + CPA License (4-6 years)",
        "relevanceScore": 82,
        "confidenceLevel": 85,
        "matchReasons": ["Financial expertise", "Analytical skills", "Professional certification"],
        "minExperienceYears": 2,
        "maxExperienceYears": 40,
        "minSalary": 65000,
        "maxSalary": 95000
    },
    {
        "title": "Financial Analyst",
        "careerType": "financial-analyst",
        "description": "Analyze financial data, create investment recommendations, assess business performance and market trends.",
        "salaryRange": "$70,000 - $105,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Financial Modeling", "Data Analysis", "Excel", "Investment Analysis"],
        "requiredSoftSkills": ["Analytical Thinking", "Communication", "Attention to Detail", "Problem Solving"],
        "companies": ["Investment Banks", "Corporations", "Consulting Firms", "Asset Management"],
        "learningPath": "Bachelor's in Finance/Economics + CFA (4-6 years)",
        "relevanceScore": 85,
        "confidenceLevel": 88,
        "matchReasons": ["Financial analysis", "Data-driven decisions", "Market research"],
        "minExperienceYears": 2,
        "maxExperienceYears": 25,
        "minSalary": 70000,
        "maxSalary": 105000
    },
    {
        "title": "Investment Banker",
        "careerType": "investment-banker",
        "description": "Help companies raise capital, facilitate mergers and acquisitions, provide financial advisory services.",
        "salaryRange": "$120,000 - $200,000",
        "experienceLevel": "senior",
        "requiredTechnicalSkills": ["Financial Modeling", "Valuation", "M&A", "Capital Markets"],
        "requiredSoftSkills": ["Communication", "Negotiation", "Stress Management", "Client Relations"],
        "companies": ["Goldman Sachs", "Morgan Stanley", "JP Morgan", "Bank of America"],
        "learningPath": "Bachelor's in Finance + MBA (6-8 years)",
        "relevanceScore": 80,
        "confidenceLevel": 82,
        "matchReasons": ["High-level finance", "Deal making", "Client advisory"],
        "minExperienceYears": 4,
        "maxExperienceYears": 30,
        "minSalary": 120000,
        "maxSalary": 200000
    },
    {
        "title": "Controller",
        "careerType": "controller",
        "description": "Oversee accounting operations, manage financial reporting, ensure regulatory compliance.",
        "salaryRange": "$95,000 - $140,000",
        "experienceLevel": "senior",
        "requiredTechnicalSkills": ["Accounting", "Financial Reporting", "Budgeting", "Compliance"],
        "requiredSoftSkills": ["Leadership", "Communication", "Problem Solving", "Attention to Detail"],
        "companies": ["Corporations", "Non-Profits", "Government", "Healthcare"],
        "learningPath": "CPA + Management Experience (8-12 years)",
        "relevanceScore": 85,
        "confidenceLevel": 88,
        "matchReasons": ["Financial leadership", "Accounting expertise", "Management skills"],
        "minExperienceYears": 8,
        "maxExperienceYears": 35,
        "minSalary": 95000,
        "maxSalary": 140000
    },
    {
        "title": "Auditor",
        "careerType": "auditor",
        "description": "Examine financial records and statements to ensure accuracy, compliance, and detect fraud or errors.",
        "salaryRange": "$55,000 - $85,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Auditing", "Risk Assessment", "Compliance", "Financial Analysis"],
        "requiredSoftSkills": ["Attention to Detail", "Analytical Thinking", "Ethics", "Communication"],
        "companies": ["Public Accounting Firms", "Government", "Corporations", "Non-Profits"],
        "learningPath": "Bachelor's in Accounting + CPA/CIA (4-6 years)",
        "relevanceScore": 80,
        "confidenceLevel": 83,
        "matchReasons": ["Financial scrutiny", "Risk assessment", "Compliance expertise"],
        "minExperienceYears": 2,
        "maxExperienceYears": 30,
        "minSalary": 55000,
        "maxSalary": 85000
    },
    {
        "title": "Financial Planner",
        "careerType": "financial-planner",
        "description": "Help individuals and families plan for financial goals, retirement, investments, and insurance needs.",
        "salaryRange": "$60,000 - $95,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Financial Planning", "Investment Analysis", "Tax Planning", "Insurance"],
        "requiredSoftSkills": ["Communication", "Empathy", "Trust Building", "Problem Solving"],
        "companies": ["Financial Planning Firms", "Banks", "Insurance Companies", "Independent Practice"],
        "learningPath": "Bachelor's + CFP Certification (4-6 years)",
        "relevanceScore": 78,
        "confidenceLevel": 80,
        "matchReasons": ["Client advisory", "Financial expertise", "Goal-oriented planning"],
        "minExperienceYears": 2,
        "maxExperienceYears": 35,
        "minSalary": 60000,
        "maxSalary": 95000
    },
    {
        "title": "Budget Analyst",
        "careerType": "budget-analyst",
        "description": "Develop, analyze, and monitor budgets for organizations, ensuring efficient allocation of resources.",
        "salaryRange": "$58,000 - $88,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Budget Analysis", "Financial Modeling", "Forecasting", "Cost Analysis"],
        "requiredSoftSkills": ["Analytical Thinking", "Attention to Detail", "Communication", "Organization"],
        "companies": ["Government", "Corporations", "Non-Profits", "Healthcare"],
        "learningPath": "Bachelor's in Finance/Accounting (4-5 years)",
        "relevanceScore": 82,
        "confidenceLevel": 85,
        "matchReasons": ["Financial planning", "Resource optimization", "Analytical skills"],
        "minExperienceYears": 2,
        "maxExperienceYears": 25,
        "minSalary": 58000,
        "maxSalary": 88000
    },
    {
        "title": "Credit Analyst",
        "careerType": "credit-analyst",
        "description": "Evaluate creditworthiness of individuals and businesses, assess loan risks, make lending recommendations.",
        "salaryRange": "$52,000 - $78,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Credit Analysis", "Risk Assessment", "Financial Analysis", "Banking Software"],
        "requiredSoftSkills": ["Analytical Thinking", "Attention to Detail", "Decision Making", "Communication"],
        "companies": ["Banks", "Credit Unions", "Investment Firms", "Insurance Companies"],
        "learningPath": "Bachelor's in Finance + Credit Analysis Training (3-5 years)",
        "relevanceScore": 75,
        "confidenceLevel": 78,
        "matchReasons": ["Risk assessment", "Financial analysis", "Decision making"],
        "minExperienceYears": 1,
        "maxExperienceYears": 20,
        "minSalary": 52000,
        "maxSalary": 78000
    },
    {
        "title": "Treasury Analyst",
        "careerType": "treasury-analyst",
        "description": "Manage corporate cash flow, investments, and financial risk, optimize liquidity and funding strategies.",
        "salaryRange": "$65,000 - $95,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Cash Management", "Financial Risk", "Investment Analysis", "Treasury Systems"],
        "requiredSoftSkills": ["Analytical Thinking", "Attention to Detail", "Problem Solving", "Communication"],
        "companies": ["Corporations", "Banks", "Investment Firms", "Government"],
        "learningPath": "Bachelor's in Finance + Treasury Certification (4-6 years)",
        "relevanceScore": 80,
        "confidenceLevel": 82,
        "matchReasons": ["Financial management", "Risk analysis", "Strategic planning"],
        "minExperienceYears": 2,
        "maxExperienceYears": 25,
        "minSalary": 65000,
        "maxSalary": 95000
    },
    {
        "title": "Tax Specialist",
        "careerType": "tax-specialist",
        "description": "Prepare tax returns, provide tax planning advice, ensure compliance with tax regulations.",
        "salaryRange": "$48,000 - $72,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Tax Preparation", "Tax Law", "Tax Software", "Research"],
        "requiredSoftSkills": ["Attention to Detail", "Analytical Thinking", "Communication", "Ethics"],
        "companies": ["Accounting Firms", "Tax Preparation Services", "Corporations", "Government"],
        "learningPath": "Bachelor's in Accounting + Tax Certification (3-5 years)",
        "relevanceScore": 75,
        "confidenceLevel": 78,
        "matchReasons": ["Tax expertise", "Compliance focus", "Client service"],
        "minExperienceYears": 1,
        "maxExperienceYears": 30,
        "minSalary": 48000,
        "maxSalary": 72000
    },

    # MANAGEMENT & CONSULTING
    {
        "title": "Management Consultant",
        "careerType": "management-consultant",
        "description": "Analyze business problems, develop solutions, help organizations improve performance and efficiency.",
        "salaryRange": "$85,000 - $130,000",
        "experienceLevel": "senior",
        "requiredTechnicalSkills": ["Business Analysis", "Strategy Development", "Process Improvement", "Data Analysis"],
        "requiredSoftSkills": ["Problem Solving", "Communication", "Leadership", "Analytical Thinking"],
        "companies": ["McKinsey", "BCG", "Bain", "Deloitte", "Accenture"],
        "learningPath": "Bachelor's + MBA (6-8 years)",
        "relevanceScore": 88,
        "confidenceLevel": 90,
        "matchReasons": ["Strategic thinking", "Problem solving", "Business improvement"],
        "minExperienceYears": 4,
        "maxExperienceYears": 30,
        "minSalary": 85000,
        "maxSalary": 130000
    },
    {
        "title": "Operations Manager",
        "careerType": "operations-manager",
        "description": "Oversee daily operations, manage teams, optimize processes, ensure quality and efficiency.",
        "salaryRange": "$75,000 - $110,000",
        "experienceLevel": "senior",
        "requiredTechnicalSkills": ["Operations Management", "Process Improvement", "Budget Management", "Quality Control"],
        "requiredSoftSkills": ["Leadership", "Communication", "Problem Solving", "Organization"],
        "companies": ["Manufacturing", "Retail", "Healthcare", "Technology"],
        "learningPath": "Bachelor's + Management Experience (6-10 years)",
        "relevanceScore": 82,
        "confidenceLevel": 85,
        "matchReasons": ["Operations expertise", "Team leadership", "Process optimization"],
        "minExperienceYears": 6,
        "maxExperienceYears": 35,
        "minSalary": 75000,
        "maxSalary": 110000
    },
    {
        "title": "Project Manager",
        "careerType": "project-manager",
        "description": "Plan and execute projects, manage resources and timelines, coordinate teams, ensure deliverables.",
        "salaryRange": "$70,000 - $105,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Project Management", "Agile/Scrum", "Risk Management", "Budget Management"],
        "requiredSoftSkills": ["Leadership", "Communication", "Organization", "Problem Solving"],
        "companies": ["Technology", "Construction", "Healthcare", "Consulting"],
        "learningPath": "Bachelor's + PMP Certification (4-6 years)",
        "relevanceScore": 85,
        "confidenceLevel": 88,
        "matchReasons": ["Project coordination", "Team leadership", "Delivery focus"],
        "minExperienceYears": 3,
        "maxExperienceYears": 30,
        "minSalary": 70000,
        "maxSalary": 105000
    },
    {
        "title": "General Manager",
        "careerType": "general-manager",
        "description": "Oversee all aspects of business operations, manage multiple departments, drive strategic initiatives.",
        "salaryRange": "$90,000 - $150,000",
        "experienceLevel": "senior",
        "requiredTechnicalSkills": ["Business Management", "Strategic Planning", "Financial Management", "Operations"],
        "requiredSoftSkills": ["Leadership", "Strategic Thinking", "Communication", "Decision Making"],
        "companies": ["Retail", "Hospitality", "Manufacturing", "Services"],
        "learningPath": "Bachelor's + MBA + Management Experience (8-12 years)",
        "relevanceScore": 88,
        "confidenceLevel": 90,
        "matchReasons": ["Executive leadership", "Strategic oversight", "Business management"],
        "minExperienceYears": 8,
        "maxExperienceYears": 35,
        "minSalary": 90000,
        "maxSalary": 150000
    },
    {
        "title": "IT Consultant",
        "careerType": "it-consultant",
        "description": "Advise organizations on technology solutions, implement IT systems, optimize technology infrastructure.",
        "salaryRange": "$75,000 - $115,000",
        "experienceLevel": "senior",
        "requiredTechnicalSkills": ["IT Systems", "Technology Strategy", "System Implementation", "Cybersecurity"],
        "requiredSoftSkills": ["Problem Solving", "Communication", "Analytical Thinking", "Adaptability"],
        "companies": ["Consulting Firms", "Technology Companies", "Independent Practice", "Corporations"],
        "learningPath": "Bachelor's in IT + Certifications (5-8 years)",
        "relevanceScore": 82,
        "confidenceLevel": 85,
        "matchReasons": ["Technology expertise", "Strategic consulting", "System optimization"],
        "minExperienceYears": 5,
        "maxExperienceYears": 30,
        "minSalary": 75000,
        "maxSalary": 115000
    },
    {
        "title": "Strategy Consultant",
        "careerType": "strategy-consultant",
        "description": "Develop corporate strategies, analyze market opportunities, guide executive decision-making.",
        "salaryRange": "$95,000 - $145,000",
        "experienceLevel": "senior",
        "requiredTechnicalSkills": ["Strategic Planning", "Market Analysis", "Financial Modeling", "Competitive Analysis"],
        "requiredSoftSkills": ["Strategic Thinking", "Communication", "Analytical Thinking", "Presentation"],
        "companies": ["Top Consulting Firms", "Boutique Strategy Firms", "Corporate Strategy Teams"],
        "learningPath": "Bachelor's + MBA + Strategy Experience (6-10 years)",
        "relevanceScore": 90,
        "confidenceLevel": 92,
        "matchReasons": ["Strategic expertise", "High-level consulting", "Executive advisory"],
        "minExperienceYears": 6,
        "maxExperienceYears": 30,
        "minSalary": 95000,
        "maxSalary": 145000
    },
    {
        "title": "Supply Chain Manager",
        "careerType": "supply-chain-manager",
        "description": "Manage end-to-end supply chain operations, optimize logistics, coordinate with suppliers and vendors.",
        "salaryRange": "$80,000 - $120,000",
        "experienceLevel": "senior",
        "requiredTechnicalSkills": ["Supply Chain Management", "Logistics", "Procurement", "Inventory Management"],
        "requiredSoftSkills": ["Problem Solving", "Negotiation", "Communication", "Analytical Thinking"],
        "companies": ["Manufacturing", "Retail", "E-commerce", "Logistics"],
        "learningPath": "Bachelor's + Supply Chain Certification (5-8 years)",
        "relevanceScore": 82,
        "confidenceLevel": 85,
        "matchReasons": ["Operations expertise", "Process optimization", "Vendor management"],
        "minExperienceYears": 5,
        "maxExperienceYears": 30,
        "minSalary": 80000,
        "maxSalary": 120000
    },

    # SALES & MARKETING
    {
        "title": "Sales Manager",
        "careerType": "sales-manager",
        "description": "Lead sales teams, develop sales strategies, manage client relationships, achieve revenue targets.",
        "salaryRange": "$80,000 - $120,000",
        "experienceLevel": "senior",
        "requiredTechnicalSkills": ["Sales Management", "CRM Software", "Sales Analytics", "Territory Management"],
        "requiredSoftSkills": ["Leadership", "Communication", "Negotiation", "Motivation"],
        "companies": ["Technology", "Pharmaceuticals", "Manufacturing", "Services"],
        "learningPath": "Bachelor's + Sales Experience (6-10 years)",
        "relevanceScore": 80,
        "confidenceLevel": 82,
        "matchReasons": ["Sales leadership", "Revenue generation", "Team management"],
        "minExperienceYears": 6,
        "maxExperienceYears": 35,
        "minSalary": 80000,
        "maxSalary": 120000
    },
    {
        "title": "Marketing Manager",
        "careerType": "marketing-manager",
        "description": "Develop marketing strategies, manage campaigns, analyze market trends, oversee marketing teams.",
        "salaryRange": "$70,000 - $105,000",
        "experienceLevel": "senior",
        "requiredTechnicalSkills": ["Marketing Strategy", "Digital Marketing", "Analytics", "Brand Management"],
        "requiredSoftSkills": ["Creativity", "Communication", "Leadership", "Analytical Thinking"],
        "companies": ["Consumer Goods", "Technology", "Healthcare", "Retail"],
        "learningPath": "Bachelor's in Marketing + Experience (5-8 years)",
        "relevanceScore": 82,
        "confidenceLevel": 85,
        "matchReasons": ["Marketing expertise", "Brand development", "Campaign management"],
        "minExperienceYears": 5,
        "maxExperienceYears": 30,
        "minSalary": 70000,
        "maxSalary": 105000
    },
    {
        "title": "Business Development Manager",
        "careerType": "business-development-manager",
        "description": "Identify growth opportunities, develop partnerships, expand market presence, drive revenue growth.",
        "salaryRange": "$75,000 - $115,000",
        "experienceLevel": "senior",
        "requiredTechnicalSkills": ["Business Development", "Market Analysis", "Partnership Management", "Sales"],
        "requiredSoftSkills": ["Relationship Building", "Communication", "Strategic Thinking", "Negotiation"],
        "companies": ["Technology", "Consulting", "Healthcare", "Financial Services"],
        "learningPath": "Bachelor's + Business Development Experience (5-8 years)",
        "relevanceScore": 85,
        "confidenceLevel": 88,
        "matchReasons": ["Growth focus", "Partnership building", "Strategic development"],
        "minExperienceYears": 5,
        "maxExperienceYears": 30,
        "minSalary": 75000,
        "maxSalary": 115000
    },
    {
        "title": "Sales Director",
        "careerType": "sales-director",
        "description": "Lead regional or national sales organizations, develop sales strategies, manage key accounts.",
        "salaryRange": "$110,000 - $180,000",
        "experienceLevel": "senior",
        "requiredTechnicalSkills": ["Sales Leadership", "Strategic Planning", "Key Account Management", "Sales Analytics"],
        "requiredSoftSkills": ["Executive Leadership", "Strategic Thinking", "Communication", "Negotiation"],
        "companies": ["Large Corporations", "Technology", "Pharmaceuticals", "Manufacturing"],
        "learningPath": "Bachelor's + MBA + Sales Leadership Experience (10-15 years)",
        "relevanceScore": 85,
        "confidenceLevel": 88,
        "matchReasons": ["Executive sales leadership", "Strategic planning", "Revenue responsibility"],
        "minExperienceYears": 10,
        "maxExperienceYears": 35,
        "minSalary": 110000,
        "maxSalary": 180000
    },
    {
        "title": "Marketing Analyst",
        "careerType": "marketing-analyst",
        "description": "Analyze marketing data, measure campaign effectiveness, provide insights for marketing decisions.",
        "salaryRange": "$55,000 - $80,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Marketing Analytics", "Data Analysis", "Statistical Analysis", "Marketing Tools"],
        "requiredSoftSkills": ["Analytical Thinking", "Communication", "Attention to Detail", "Problem Solving"],
        "companies": ["Marketing Agencies", "Corporations", "E-commerce", "Technology"],
        "learningPath": "Bachelor's in Marketing/Analytics (3-5 years)",
        "relevanceScore": 80,
        "confidenceLevel": 82,
        "matchReasons": ["Data analysis", "Marketing insights", "Performance measurement"],
        "minExperienceYears": 2,
        "maxExperienceYears": 20,
        "minSalary": 55000,
        "maxSalary": 80000
    },
    {
        "title": "Digital Marketing Specialist",
        "careerType": "digital-marketing-specialist",
        "description": "Manage digital marketing campaigns, optimize online presence, analyze digital marketing metrics.",
        "salaryRange": "$50,000 - $75,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Digital Marketing", "SEO/SEM", "Social Media", "Google Analytics"],
        "requiredSoftSkills": ["Creativity", "Analytical Thinking", "Communication", "Adaptability"],
        "companies": ["Digital Agencies", "E-commerce", "Technology", "Retail"],
        "learningPath": "Bachelor's + Digital Marketing Certifications (3-5 years)",
        "relevanceScore": 78,
        "confidenceLevel": 80,
        "matchReasons": ["Digital expertise", "Online marketing", "Data-driven approach"],
        "minExperienceYears": 2,
        "maxExperienceYears": 15,
        "minSalary": 50000,
        "maxSalary": 75000
    },
    {
        "title": "Account Manager",
        "careerType": "account-manager",
        "description": "Manage client relationships, ensure customer satisfaction, identify upselling opportunities.",
        "salaryRange": "$55,000 - $85,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Account Management", "CRM Software", "Sales", "Customer Service"],
        "requiredSoftSkills": ["Relationship Building", "Communication", "Problem Solving", "Organization"],
        "companies": ["Advertising Agencies", "Technology", "Professional Services", "Manufacturing"],
        "learningPath": "Bachelor's + Account Management Experience (3-6 years)",
        "relevanceScore": 78,
        "confidenceLevel": 80,
        "matchReasons": ["Client relationship management", "Customer focus", "Business development"],
        "minExperienceYears": 2,
        "maxExperienceYears": 25,
        "minSalary": 55000,
        "maxSalary": 85000
    },
    {
        "title": "Brand Manager",
        "careerType": "brand-manager",
        "description": "Develop and execute brand strategies, manage brand positioning, oversee brand communications.",
        "salaryRange": "$70,000 - $105,000",
        "experienceLevel": "senior",
        "requiredTechnicalSkills": ["Brand Management", "Marketing Strategy", "Market Research", "Creative Development"],
        "requiredSoftSkills": ["Strategic Thinking", "Creativity", "Communication", "Leadership"],
        "companies": ["Consumer Goods", "Retail", "Technology", "Healthcare"],
        "learningPath": "Bachelor's in Marketing + Brand Management Experience (5-8 years)",
        "relevanceScore": 82,
        "confidenceLevel": 85,
        "matchReasons": ["Brand expertise", "Strategic marketing", "Creative leadership"],
        "minExperienceYears": 5,
        "maxExperienceYears": 25,
        "minSalary": 70000,
        "maxSalary": 105000
    },

    # HUMAN RESOURCES
    {
        "title": "HR Manager",
        "careerType": "hr-manager",
        "description": "Manage human resources functions, recruit talent, handle employee relations, ensure compliance.",
        "salaryRange": "$70,000 - $100,000",
        "experienceLevel": "senior",
        "requiredTechnicalSkills": ["HR Management", "Recruitment", "Employee Relations", "Compliance"],
        "requiredSoftSkills": ["Communication", "Empathy", "Problem Solving", "Confidentiality"],
        "companies": ["Corporations", "Non-Profits", "Government", "Healthcare"],
        "learningPath": "Bachelor's in HR + SHRM Certification (5-8 years)",
        "relevanceScore": 80,
        "confidenceLevel": 82,
        "matchReasons": ["People management", "Organizational development", "Employee support"],
        "minExperienceYears": 5,
        "maxExperienceYears": 35,
        "minSalary": 70000,
        "maxSalary": 100000
    },
    {
        "title": "Recruiter",
        "careerType": "recruiter",
        "description": "Source and recruit candidates, conduct interviews, manage hiring process, build talent pipelines.",
        "salaryRange": "$50,000 - $75,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Recruiting", "Interviewing", "ATS Software", "Sourcing"],
        "requiredSoftSkills": ["Communication", "Relationship Building", "Persuasion", "Organization"],
        "companies": ["Recruiting Firms", "Corporations", "Staffing Agencies"],
        "learningPath": "Bachelor's + Recruiting Experience (3-5 years)",
        "relevanceScore": 75,
        "confidenceLevel": 78,
        "matchReasons": ["People skills", "Talent identification", "Relationship building"],
        "minExperienceYears": 2,
        "maxExperienceYears": 25,
        "minSalary": 50000,
        "maxSalary": 75000
    },
    {
        "title": "Compensation Analyst",
        "careerType": "compensation-analyst",
        "description": "Analyze compensation data, develop pay structures, ensure competitive and equitable compensation.",
        "salaryRange": "$60,000 - $85,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Compensation Analysis", "Job Evaluation", "Market Research", "HRIS Systems"],
        "requiredSoftSkills": ["Analytical Thinking", "Attention to Detail", "Communication", "Confidentiality"],
        "companies": ["Corporations", "Consulting Firms", "Government", "Non-Profits"],
        "learningPath": "Bachelor's in HR/Business + Compensation Certification (4-6 years)",
        "relevanceScore": 78,
        "confidenceLevel": 80,
        "matchReasons": ["Data analysis", "Compensation expertise", "Market research"],
        "minExperienceYears": 2,
        "maxExperienceYears": 20,
        "minSalary": 60000,
        "maxSalary": 85000
    },
    {
        "title": "Training and Development Manager",
        "careerType": "training-development-manager",
        "description": "Design and implement employee training programs, assess training needs, measure program effectiveness.",
        "salaryRange": "$65,000 - $95,000",
        "experienceLevel": "senior",
        "requiredTechnicalSkills": ["Training Design", "Learning Management Systems", "Curriculum Development", "Performance Management"],
        "requiredSoftSkills": ["Communication", "Leadership", "Creativity", "Empathy"],
        "companies": ["Corporations", "Training Companies", "Government", "Healthcare"],
        "learningPath": "Bachelor's + Training Certification (5-8 years)",
        "relevanceScore": 80,
        "confidenceLevel": 82,
        "matchReasons": ["Employee development", "Training expertise", "Organizational improvement"],
        "minExperienceYears": 5,
        "maxExperienceYears": 30,
        "minSalary": 65000,
        "maxSalary": 95000
    },
    {
        "title": "HR Business Partner",
        "careerType": "hr-business-partner",
        "description": "Partner with business leaders on HR strategy, provide HR consultation, drive organizational change.",
        "salaryRange": "$80,000 - $115,000",
        "experienceLevel": "senior",
        "requiredTechnicalSkills": ["HR Strategy", "Business Consulting", "Change Management", "Organizational Development"],
        "requiredSoftSkills": ["Strategic Thinking", "Communication", "Relationship Building", "Problem Solving"],
        "companies": ["Large Corporations", "Technology", "Healthcare", "Financial Services"],
        "learningPath": "Bachelor's in HR + Business Experience (6-10 years)",
        "relevanceScore": 85,
        "confidenceLevel": 88,
        "matchReasons": ["Strategic HR", "Business partnership", "Organizational impact"],
        "minExperienceYears": 6,
        "maxExperienceYears": 30,
        "minSalary": 80000,
        "maxSalary": 115000
    },
    {
        "title": "Benefits Administrator",
        "careerType": "benefits-administrator",
        "description": "Manage employee benefits programs, handle enrollment, ensure compliance with benefits regulations.",
        "salaryRange": "$45,000 - $65,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Benefits Administration", "HRIS Systems", "Compliance", "Employee Communication"],
        "requiredSoftSkills": ["Attention to Detail", "Communication", "Organization", "Customer Service"],
        "companies": ["Corporations", "Government", "Non-Profits", "Healthcare"],
        "learningPath": "Bachelor's + Benefits Certification (3-5 years)",
        "relevanceScore": 72,
        "confidenceLevel": 75,
        "matchReasons": ["Benefits expertise", "Employee support", "Administrative skills"],
        "minExperienceYears": 2,
        "maxExperienceYears": 20,
        "minSalary": 45000,
        "maxSalary": 65000
    },

    # ENTRY LEVEL BUSINESS
    {
        "title": "Business Analyst",
        "careerType": "business-analyst",
        "description": "Analyze business processes, identify improvement opportunities, gather requirements, support decision making.",
        "salaryRange": "$60,000 - $85,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Business Analysis", "Data Analysis", "Process Mapping", "Requirements Gathering"],
        "requiredSoftSkills": ["Analytical Thinking", "Communication", "Problem Solving", "Attention to Detail"],
        "companies": ["Consulting", "Technology", "Healthcare", "Financial Services"],
        "learningPath": "Bachelor's + Business Analysis Certification (3-5 years)",
        "relevanceScore": 85,
        "confidenceLevel": 88,
        "matchReasons": ["Analytical skills", "Process improvement", "Business understanding"],
        "minExperienceYears": 2,
        "maxExperienceYears": 20,
        "minSalary": 60000,
        "maxSalary": 85000
    },
    {
        "title": "Administrative Assistant",
        "careerType": "administrative-assistant",
        "description": "Provide administrative support, manage schedules, handle correspondence, organize meetings.",
        "salaryRange": "$35,000 - $50,000",
        "experienceLevel": "junior",
        "requiredTechnicalSkills": ["Office Software", "Scheduling", "Data Entry", "Communication"],
        "requiredSoftSkills": ["Organization", "Communication", "Attention to Detail", "Multitasking"],
        "companies": ["All Industries", "Government", "Non-Profits", "Healthcare"],
        "learningPath": "High School + Office Skills Training (1-2 years)",
        "relevanceScore": 65,
        "confidenceLevel": 70,
        "matchReasons": ["Organizational skills", "Support role", "Office environment"],
        "minExperienceYears": 0,
        "maxExperienceYears": 30,
        "minSalary": 35000,
        "maxSalary": 50000
    },
    {
        "title": "Executive Assistant",
        "careerType": "executive-assistant",
        "description": "Provide high-level administrative support to executives, manage complex schedules, coordinate meetings.",
        "salaryRange": "$55,000 - $80,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Executive Support", "Project Coordination", "Travel Planning", "Office Software"],
        "requiredSoftSkills": ["Discretion", "Organization", "Communication", "Multitasking"],
        "companies": ["Corporations", "Executive Offices", "Non-Profits", "Government"],
        "learningPath": "Bachelor's + Executive Assistant Experience (4-6 years)",
        "relevanceScore": 75,
        "confidenceLevel": 78,
        "matchReasons": ["Executive support", "High-level organization", "Professional communication"],
        "minExperienceYears": 3,
        "maxExperienceYears": 25,
        "minSalary": 55000,
        "maxSalary": 80000
    },
    {
        "title": "Data Analyst",
        "careerType": "data-analyst",
        "description": "Collect, process, and analyze data to provide business insights and support decision-making.",
        "salaryRange": "$60,000 - $90,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Data Analysis", "SQL", "Excel", "Statistical Analysis", "Data Visualization"],
        "requiredSoftSkills": ["Analytical Thinking", "Problem Solving", "Communication", "Attention to Detail"],
        "companies": ["Technology", "Finance", "Healthcare", "Retail"],
        "learningPath": "Bachelor's in Analytics/Statistics (3-5 years)",
        "relevanceScore": 88,
        "confidenceLevel": 90,
        "matchReasons": ["Data expertise", "Analytical skills", "Business insights"],
        "minExperienceYears": 2,
        "maxExperienceYears": 20,
        "minSalary": 60000,
        "maxSalary": 90000
    },
    {
        "title": "Risk Manager",
        "careerType": "risk-manager",
        "description": "Identify, assess, and mitigate business risks, develop risk management strategies and policies.",
        "salaryRange": "$85,000 - $125,000",
        "experienceLevel": "senior",
        "requiredTechnicalSkills": ["Risk Assessment", "Risk Management", "Compliance", "Financial Analysis"],
        "requiredSoftSkills": ["Analytical Thinking", "Problem Solving", "Communication", "Strategic Thinking"],
        "companies": ["Financial Services", "Insurance", "Corporations", "Government"],
        "learningPath": "Bachelor's + Risk Management Certification (6-8 years)",
        "relevanceScore": 85,
        "confidenceLevel": 88,
        "matchReasons": ["Risk expertise", "Strategic thinking", "Analytical skills"],
        "minExperienceYears": 6,
        "maxExperienceYears": 30,
        "minSalary": 85000,
        "maxSalary": 125000
    },
    {
        "title": "Compliance Officer",
        "careerType": "compliance-officer",
        "description": "Ensure organizational compliance with laws and regulations, develop compliance programs.",
        "salaryRange": "$70,000 - $105,000",
        "experienceLevel": "senior",
        "requiredTechnicalSkills": ["Compliance", "Regulatory Knowledge", "Risk Assessment", "Policy Development"],
        "requiredSoftSkills": ["Attention to Detail", "Ethics", "Communication", "Problem Solving"],
        "companies": ["Financial Services", "Healthcare", "Government", "Corporations"],
        "learningPath": "Bachelor's + Compliance Certification (5-8 years)",
        "relevanceScore": 82,
        "confidenceLevel": 85,
        "matchReasons": ["Compliance expertise", "Regulatory knowledge", "Risk management"],
        "minExperienceYears": 5,
        "maxExperienceYears": 30,
        "minSalary": 70000,
        "maxSalary": 105000
    },
    {
        "title": "Quality Assurance Manager",
        "careerType": "quality-assurance-manager",
        "description": "Develop and implement quality control processes, ensure products and services meet standards.",
        "salaryRange": "$75,000 - $110,000",
        "experienceLevel": "senior",
        "requiredTechnicalSkills": ["Quality Management", "Process Improvement", "Statistical Analysis", "Auditing"],
        "requiredSoftSkills": ["Attention to Detail", "Leadership", "Problem Solving", "Communication"],
        "companies": ["Manufacturing", "Healthcare", "Technology", "Automotive"],
        "learningPath": "Bachelor's + Quality Management Certification (6-10 years)",
        "relevanceScore": 80,
        "confidenceLevel": 82,
        "matchReasons": ["Quality expertise", "Process improvement", "Leadership skills"],
        "minExperienceYears": 6,
        "maxExperienceYears": 30,
        "minSalary": 75000,
        "maxSalary": 110000
    },
    {
        "title": "Procurement Manager",
        "careerType": "procurement-manager",
        "description": "Manage purchasing processes, negotiate with suppliers, optimize procurement strategies.",
        "salaryRange": "$70,000 - $105,000",
        "experienceLevel": "senior",
        "requiredTechnicalSkills": ["Procurement", "Contract Negotiation", "Supplier Management", "Cost Analysis"],
        "requiredSoftSkills": ["Negotiation", "Communication", "Analytical Thinking", "Relationship Building"],
        "companies": ["Manufacturing", "Government", "Healthcare", "Retail"],
        "learningPath": "Bachelor's + Procurement Certification (5-8 years)",
        "relevanceScore": 78,
        "confidenceLevel": 80,
        "matchReasons": ["Procurement expertise", "Negotiation skills", "Cost optimization"],
        "minExperienceYears": 5,
        "maxExperienceYears": 30,
        "minSalary": 70000,
        "maxSalary": 105000
    },
    {
        "title": "Customer Success Manager",
        "careerType": "customer-success-manager",
        "description": "Ensure customer satisfaction and retention, manage customer relationships, drive product adoption.",
        "salaryRange": "$65,000 - $95,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Customer Success", "CRM Software", "Data Analysis", "Product Knowledge"],
        "requiredSoftSkills": ["Communication", "Empathy", "Problem Solving", "Relationship Building"],
        "companies": ["SaaS Companies", "Technology", "Professional Services", "E-commerce"],
        "learningPath": "Bachelor's + Customer Success Experience (4-6 years)",
        "relevanceScore": 82,
        "confidenceLevel": 85,
        "matchReasons": ["Customer focus", "Relationship management", "Business growth"],
        "minExperienceYears": 3,
        "maxExperienceYears": 25,
        "minSalary": 65000,
        "maxSalary": 95000
    },
    {
        "title": "Product Manager",
        "careerType": "product-manager",
        "description": "Define product strategy, manage product development lifecycle, coordinate cross-functional teams.",
        "salaryRange": "$90,000 - $140,000",
        "experienceLevel": "senior",
        "requiredTechnicalSkills": ["Product Management", "Market Research", "Data Analysis", "Agile/Scrum"],
        "requiredSoftSkills": ["Strategic Thinking", "Leadership", "Communication", "Problem Solving"],
        "companies": ["Technology", "Software", "Consumer Goods", "Healthcare"],
        "learningPath": "Bachelor's + MBA + Product Experience (6-10 years)",
        "relevanceScore": 90,
        "confidenceLevel": 92,
        "matchReasons": ["Strategic product leadership", "Cross-functional coordination", "Market focus"],
        "minExperienceYears": 5,
        "maxExperienceYears": 25,
        "minSalary": 90000,
        "maxSalary": 140000
    },
    {
        "title": "Logistics Coordinator",
        "careerType": "logistics-coordinator",
        "description": "Coordinate shipping and receiving operations, manage inventory, optimize logistics processes.",
        "salaryRange": "$45,000 - $65,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Logistics", "Inventory Management", "Transportation", "Supply Chain Software"],
        "requiredSoftSkills": ["Organization", "Problem Solving", "Communication", "Attention to Detail"],
        "companies": ["Manufacturing", "Retail", "E-commerce", "Logistics Companies"],
        "learningPath": "Bachelor's + Logistics Experience (3-5 years)",
        "relevanceScore": 75,
        "confidenceLevel": 78,
        "matchReasons": ["Operations coordination", "Process optimization", "Supply chain management"],
        "minExperienceYears": 2,
        "maxExperienceYears": 20,
        "minSalary": 45000,
        "maxSalary": 65000
    },
    {
        "title": "Financial Controller",
        "careerType": "financial-controller",
        "description": "Oversee financial reporting, manage accounting team, ensure financial compliance and accuracy.",
        "salaryRange": "$100,000 - $150,000",
        "experienceLevel": "senior",
        "requiredTechnicalSkills": ["Financial Reporting", "Accounting", "Budgeting", "Team Management"],
        "requiredSoftSkills": ["Leadership", "Analytical Thinking", "Communication", "Problem Solving"],
        "companies": ["Corporations", "Non-Profits", "Government", "Healthcare"],
        "learningPath": "CPA + Controller Experience (10-15 years)",
        "relevanceScore": 88,
        "confidenceLevel": 90,
        "matchReasons": ["Financial leadership", "Accounting expertise", "Team management"],
        "minExperienceYears": 10,
        "maxExperienceYears": 35,
        "minSalary": 100000,
        "maxSalary": 150000
    },
    {
        "title": "Chief Financial Officer (CFO)",
        "careerType": "cfo",
        "description": "Lead financial strategy, oversee all financial operations, provide executive financial leadership.",
        "salaryRange": "$150,000 - $300,000",
        "experienceLevel": "senior",
        "requiredTechnicalSkills": ["Financial Strategy", "Executive Leadership", "Financial Reporting", "Strategic Planning"],
        "requiredSoftSkills": ["Executive Leadership", "Strategic Thinking", "Communication", "Decision Making"],
        "companies": ["Corporations", "Startups", "Non-Profits", "Public Companies"],
        "learningPath": "CPA + MBA + Executive Experience (15-20 years)",
        "relevanceScore": 95,
        "confidenceLevel": 98,
        "matchReasons": ["Executive financial leadership", "Strategic oversight", "Organizational impact"],
        "minExperienceYears": 15,
        "maxExperienceYears": 40,
        "minSalary": 150000,
        "maxSalary": 300000
    }
]