"""
Creative & Arts career database with comprehensive roles across all experience levels.
Includes traditional arts, digital media, entertainment, design, and creative technology roles.
"""

CREATIVE_ARTS_CAREERS = [
    # EXECUTIVE LEVEL (15+ years, $150k+)
    {
        "title": "Creative Director",
        "careerType": "creative-director",
        "description": "Lead creative vision and strategy across all creative projects, manage creative teams, oversee brand identity and campaigns.",
        "salaryRange": "$150,000 - $250,000",
        "experienceLevel": "executive",
        "requiredTechnicalSkills": ["Creative Strategy", "Brand Development", "Team Leadership", "Campaign Management", "Design Systems"],
        "requiredSoftSkills": ["Creative Vision", "Leadership", "Communication", "Strategic Thinking", "Innovation"],
        "companies": ["Nike", "Apple", "Disney", "Netflix", "Adobe", "Spotify"],
        "learningPath": "Creative Leadership Program (6-12 months)",
        "relevanceScore": 85,
        "confidenceLevel": 80,
        "matchReasons": ["Creative leadership experience", "Brand strategy background"],
        "minExperienceYears": 15,
        "maxExperienceYears": 30,
        "minSalary": 150000,
        "maxSalary": 250000
    },
    {
        "title": "Art Director",
        "careerType": "art-director",
        "description": "Oversee visual style and artistic elements of creative projects, lead design teams, ensure brand consistency.",
        "salaryRange": "$120,000 - $200,000",
        "experienceLevel": "executive",
        "requiredTechnicalSkills": ["Visual Design", "Brand Identity", "Creative Direction", "Design Software", "Project Management"],
        "requiredSoftSkills": ["Artistic Vision", "Leadership", "Communication", "Attention to Detail", "Collaboration"],
        "companies": ["Ogilvy", "BBDO", "Wieden+Kennedy", "Droga5", "R/GA", "72andSunny"],
        "learningPath": "Art Direction Mastery (6-8 months)",
        "relevanceScore": 88,
        "confidenceLevel": 85,
        "matchReasons": ["Visual design expertise", "Creative team leadership"],
        "minExperienceYears": 12,
        "maxExperienceYears": 25,
        "minSalary": 120000,
        "maxSalary": 200000
    },
    {
        "title": "Head of Design",
        "careerType": "head-of-design",
        "description": "Lead design organization, establish design culture, drive design strategy across product and brand.",
        "salaryRange": "$160,000 - $280,000",
        "experienceLevel": "executive",
        "requiredTechnicalSkills": ["Design Leadership", "Design Systems", "User Experience", "Design Strategy", "Team Management"],
        "requiredSoftSkills": ["Strategic Vision", "Leadership", "Communication", "Innovation", "Mentoring"],
        "companies": ["Apple", "Google", "Airbnb", "Uber", "Netflix", "Spotify"],
        "learningPath": "Design Leadership Program (6-12 months)",
        "relevanceScore": 90,
        "confidenceLevel": 88,
        "matchReasons": ["Design leadership experience", "Strategic design thinking"],
        "minExperienceYears": 15,
        "maxExperienceYears": 30,
        "minSalary": 160000,
        "maxSalary": 280000
    },
    {
        "title": "Chief Creative Officer",
        "careerType": "chief-creative-officer",
        "description": "Lead creative strategy across the entire organization, oversee all creative output, drive innovation and brand vision.",
        "salaryRange": "$200,000 - $400,000",
        "experienceLevel": "executive",
        "requiredTechnicalSkills": ["Creative Strategy", "Brand Leadership", "Innovation Management", "Creative Operations", "Digital Transformation"],
        "requiredSoftSkills": ["Executive Leadership", "Creative Vision", "Strategic Thinking", "Communication", "Innovation"],
        "companies": ["Disney", "Nike", "Apple", "Netflix", "Adobe", "Warner Bros"],
        "learningPath": "Chief Creative Officer Program (6-12 months)",
        "relevanceScore": 85,
        "confidenceLevel": 82,
        "matchReasons": ["Executive creative leadership", "Brand strategy expertise"],
        "minExperienceYears": 20,
        "maxExperienceYears": 35,
        "minSalary": 200000,
        "maxSalary": 400000
    },

    # SENIOR LEVEL (8-15 years, $80k-180k)
    {
        "title": "Senior UX Designer",
        "careerType": "senior-ux-designer",
        "description": "Lead user experience design projects, conduct user research, create design systems, mentor junior designers.",
        "salaryRange": "$110,000 - $170,000",
        "experienceLevel": "senior",
        "requiredTechnicalSkills": ["UX Design", "User Research", "Prototyping", "Design Systems", "Usability Testing"],
        "requiredSoftSkills": ["Empathy", "Problem Solving", "Communication", "Collaboration", "Critical Thinking"],
        "companies": ["Google", "Apple", "Microsoft", "Adobe", "Figma", "Airbnb"],
        "learningPath": "Senior UX Design Certification (4-6 months)",
        "relevanceScore": 88,
        "confidenceLevel": 85,
        "matchReasons": ["User-centered design thinking", "Research and analysis skills"],
        "minExperienceYears": 8,
        "maxExperienceYears": 15,
        "minSalary": 110000,
        "maxSalary": 170000
    },
    {
        "title": "Senior Graphic Designer",
        "careerType": "senior-graphic-designer",
        "description": "Create visual concepts and designs for print and digital media, lead design projects, maintain brand consistency.",
        "salaryRange": "$75,000 - $120,000",
        "experienceLevel": "senior",
        "requiredTechnicalSkills": ["Adobe Creative Suite", "Typography", "Brand Design", "Print Design", "Digital Design"],
        "requiredSoftSkills": ["Creativity", "Attention to Detail", "Communication", "Time Management", "Problem Solving"],
        "companies": ["Pentagram", "IDEO", "Frog Design", "Adobe", "Nike", "Apple"],
        "learningPath": "Advanced Graphic Design (4-6 months)",
        "relevanceScore": 85,
        "confidenceLevel": 82,
        "matchReasons": ["Visual design skills", "Brand understanding"],
        "minExperienceYears": 8,
        "maxExperienceYears": 15,
        "minSalary": 75000,
        "maxSalary": 120000
    },
    {
        "title": "Motion Graphics Designer",
        "careerType": "motion-graphics-designer",
        "description": "Create animated graphics and visual effects for video, film, television, and digital media.",
        "salaryRange": "$80,000 - $130,000",
        "experienceLevel": "senior",
        "requiredTechnicalSkills": ["After Effects", "Cinema 4D", "Motion Design", "Video Editing", "3D Animation"],
        "requiredSoftSkills": ["Creativity", "Storytelling", "Attention to Detail", "Time Management", "Collaboration"],
        "companies": ["Pixar", "Disney", "Netflix", "Adobe", "Buck", "Giant Ant"],
        "learningPath": "Motion Graphics Mastery (4-6 months)",
        "relevanceScore": 82,
        "confidenceLevel": 80,
        "matchReasons": ["Animation and motion skills", "Visual storytelling"],
        "minExperienceYears": 8,
        "maxExperienceYears": 15,
        "minSalary": 80000,
        "maxSalary": 130000
    },
    {
        "title": "Brand Designer",
        "careerType": "brand-designer",
        "description": "Develop brand identities, create brand guidelines, design marketing materials, ensure brand consistency.",
        "salaryRange": "$85,000 - $135,000",
        "experienceLevel": "senior",
        "requiredTechnicalSkills": ["Brand Identity", "Logo Design", "Typography", "Brand Guidelines", "Marketing Design"],
        "requiredSoftSkills": ["Strategic Thinking", "Creativity", "Communication", "Attention to Detail", "Business Acumen"],
        "companies": ["Pentagram", "Landor", "Interbrand", "Nike", "Apple", "Coca-Cola"],
        "learningPath": "Brand Design Specialization (4-6 months)",
        "relevanceScore": 88,
        "confidenceLevel": 85,
        "matchReasons": ["Brand strategy understanding", "Visual identity skills"],
        "minExperienceYears": 8,
        "maxExperienceYears": 15,
        "minSalary": 85000,
        "maxSalary": 135000
    },
    {
        "title": "Creative Producer",
        "careerType": "creative-producer",
        "description": "Manage creative projects from concept to completion, coordinate teams, ensure quality and timely delivery.",
        "salaryRange": "$90,000 - $150,000",
        "experienceLevel": "senior",
        "requiredTechnicalSkills": ["Project Management", "Creative Production", "Budget Management", "Team Coordination", "Quality Control"],
        "requiredSoftSkills": ["Leadership", "Organization", "Communication", "Problem Solving", "Time Management"],
        "companies": ["Disney", "Netflix", "Warner Bros", "Universal", "Sony Pictures", "Paramount"],
        "learningPath": "Creative Production Management (4-6 months)",
        "relevanceScore": 85,
        "confidenceLevel": 82,
        "matchReasons": ["Project management skills", "Creative coordination"],
        "minExperienceYears": 8,
        "maxExperienceYears": 15,
        "minSalary": 90000,
        "maxSalary": 150000
    },

    # MID LEVEL (4-10 years, $50k-120k)
    {
        "title": "UX/UI Designer",
        "careerType": "ux-ui-designer",
        "description": "Design user interfaces and experiences, create wireframes and prototypes, conduct user research.",
        "salaryRange": "$70,000 - $110,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["UI/UX Design", "Figma/Sketch", "Prototyping", "User Research", "Wireframing"],
        "requiredSoftSkills": ["Empathy", "Problem Solving", "Communication", "Creativity", "Analytical Thinking"],
        "companies": ["Google", "Apple", "Microsoft", "Adobe", "Figma", "Airbnb"],
        "learningPath": "UX/UI Design Certification (3-4 months)",
        "relevanceScore": 85,
        "confidenceLevel": 82,
        "matchReasons": ["User-centered thinking", "Design problem solving"],
        "minExperienceYears": 4,
        "maxExperienceYears": 10,
        "minSalary": 70000,
        "maxSalary": 110000
    },
    {
        "title": "Graphic Designer",
        "careerType": "graphic-designer",
        "description": "Create visual designs for print and digital media, develop marketing materials, maintain brand consistency.",
        "salaryRange": "$50,000 - $80,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Adobe Creative Suite", "Typography", "Layout Design", "Print Design", "Digital Design"],
        "requiredSoftSkills": ["Creativity", "Attention to Detail", "Communication", "Time Management", "Adaptability"],
        "companies": ["Design agencies", "Marketing firms", "In-house teams", "Freelance", "Startups", "Corporations"],
        "learningPath": "Graphic Design Fundamentals (3-4 months)",
        "relevanceScore": 80,
        "confidenceLevel": 78,
        "matchReasons": ["Visual design skills", "Creative problem solving"],
        "minExperienceYears": 4,
        "maxExperienceYears": 10,
        "minSalary": 50000,
        "maxSalary": 80000
    },
    {
        "title": "Web Designer",
        "careerType": "web-designer",
        "description": "Design websites and web applications, create responsive layouts, optimize user experience.",
        "salaryRange": "$55,000 - $90,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Web Design", "HTML/CSS", "Responsive Design", "Adobe Creative Suite", "Figma"],
        "requiredSoftSkills": ["Creativity", "Problem Solving", "Attention to Detail", "Communication", "Adaptability"],
        "companies": ["Web agencies", "Tech companies", "Startups", "E-commerce", "Digital agencies", "Freelance"],
        "learningPath": "Web Design Certification (3-4 months)",
        "relevanceScore": 82,
        "confidenceLevel": 80,
        "matchReasons": ["Digital design skills", "Technical creativity"],
        "minExperienceYears": 4,
        "maxExperienceYears": 10,
        "minSalary": 55000,
        "maxSalary": 90000
    },
    {
        "title": "Video Editor",
        "careerType": "video-editor",
        "description": "Edit video content for various media, create compelling narratives, work with motion graphics and sound.",
        "salaryRange": "$60,000 - $95,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Video Editing", "Adobe Premiere", "Final Cut Pro", "After Effects", "Color Correction"],
        "requiredSoftSkills": ["Storytelling", "Attention to Detail", "Creativity", "Time Management", "Collaboration"],
        "companies": ["Netflix", "Disney", "YouTube", "Production companies", "Marketing agencies", "News outlets"],
        "learningPath": "Video Editing Mastery (3-4 months)",
        "relevanceScore": 78,
        "confidenceLevel": 75,
        "matchReasons": ["Visual storytelling", "Technical creativity"],
        "minExperienceYears": 4,
        "maxExperienceYears": 10,
        "minSalary": 60000,
        "maxSalary": 95000
    },
    {
        "title": "Photographer",
        "careerType": "photographer",
        "description": "Capture and edit photographs for commercial, artistic, or documentary purposes across various specializations.",
        "salaryRange": "$45,000 - $85,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Photography", "Photo Editing", "Lightroom", "Photoshop", "Studio Lighting"],
        "requiredSoftSkills": ["Artistic Vision", "Attention to Detail", "Communication", "Patience", "Adaptability"],
        "companies": ["Studios", "Agencies", "Publications", "Freelance", "E-commerce", "Events"],
        "learningPath": "Professional Photography (3-6 months)",
        "relevanceScore": 75,
        "confidenceLevel": 72,
        "matchReasons": ["Visual artistry", "Technical skills"],
        "minExperienceYears": 3,
        "maxExperienceYears": 10,
        "minSalary": 45000,
        "maxSalary": 85000
    },
    {
        "title": "Illustrator",
        "careerType": "illustrator",
        "description": "Create original artwork and illustrations for books, magazines, advertising, and digital media.",
        "salaryRange": "$50,000 - $80,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Digital Illustration", "Adobe Illustrator", "Photoshop", "Drawing", "Concept Art"],
        "requiredSoftSkills": ["Creativity", "Artistic Vision", "Communication", "Time Management", "Adaptability"],
        "companies": ["Publishing", "Advertising", "Gaming", "Animation", "Freelance", "Design agencies"],
        "learningPath": "Digital Illustration Mastery (3-4 months)",
        "relevanceScore": 80,
        "confidenceLevel": 78,
        "matchReasons": ["Artistic creativity", "Visual communication"],
        "minExperienceYears": 3,
        "maxExperienceYears": 10,
        "minSalary": 50000,
        "maxSalary": 80000
    },

    # JUNIOR/ENTRY LEVEL (0-5 years, $35k-70k)
    {
        "title": "Junior Graphic Designer",
        "careerType": "junior-graphic-designer",
        "description": "Support design projects, create basic marketing materials, learn design principles and software.",
        "salaryRange": "$35,000 - $55,000",
        "experienceLevel": "junior",
        "requiredTechnicalSkills": ["Adobe Creative Suite", "Basic Typography", "Layout Design", "File Preparation", "Brand Guidelines"],
        "requiredSoftSkills": ["Creativity", "Learning Agility", "Attention to Detail", "Communication", "Teamwork"],
        "companies": ["Design agencies", "Marketing firms", "Startups", "Non-profits", "Small businesses", "In-house teams"],
        "learningPath": "Graphic Design Fundamentals (2-3 months)",
        "relevanceScore": 75,
        "confidenceLevel": 78,
        "matchReasons": ["Creative potential", "Visual thinking"],
        "minExperienceYears": 0,
        "maxExperienceYears": 3,
        "minSalary": 35000,
        "maxSalary": 55000
    },
    {
        "title": "Junior UX Designer",
        "careerType": "junior-ux-designer",
        "description": "Assist with user research, create wireframes and prototypes, learn UX methodologies and tools.",
        "salaryRange": "$50,000 - $75,000",
        "experienceLevel": "junior",
        "requiredTechnicalSkills": ["Figma/Sketch", "Wireframing", "Prototyping", "User Research Basics", "Design Thinking"],
        "requiredSoftSkills": ["Empathy", "Problem Solving", "Communication", "Learning Agility", "Curiosity"],
        "companies": ["Tech startups", "Digital agencies", "Software companies", "E-commerce", "SaaS companies", "Consulting"],
        "learningPath": "UX Design Bootcamp (3-4 months)",
        "relevanceScore": 80,
        "confidenceLevel": 78,
        "matchReasons": ["User-centered thinking", "Problem-solving approach"],
        "minExperienceYears": 0,
        "maxExperienceYears": 3,
        "minSalary": 50000,
        "maxSalary": 75000
    },
    {
        "title": "Social Media Designer",
        "careerType": "social-media-designer",
        "description": "Create visual content for social media platforms, design posts, stories, and campaigns.",
        "salaryRange": "$40,000 - $65,000",
        "experienceLevel": "junior",
        "requiredTechnicalSkills": ["Social Media Design", "Adobe Creative Suite", "Canva", "Video Editing", "Brand Guidelines"],
        "requiredSoftSkills": ["Creativity", "Trend Awareness", "Communication", "Time Management", "Adaptability"],
        "companies": ["Social media agencies", "Marketing firms", "Brands", "Influencers", "Startups", "E-commerce"],
        "learningPath": "Social Media Design (2-3 months)",
        "relevanceScore": 72,
        "confidenceLevel": 75,
        "matchReasons": ["Digital creativity", "Trend awareness"],
        "minExperienceYears": 0,
        "maxExperienceYears": 4,
        "minSalary": 40000,
        "maxSalary": 65000
    },
    {
        "title": "Production Assistant",
        "careerType": "production-assistant",
        "description": "Support film, TV, or digital content production, assist with logistics, equipment, and coordination.",
        "salaryRange": "$35,000 - $50,000",
        "experienceLevel": "junior",
        "requiredTechnicalSkills": ["Production Support", "Equipment Handling", "Scheduling", "Basic Editing", "File Management"],
        "requiredSoftSkills": ["Organization", "Communication", "Teamwork", "Adaptability", "Problem Solving"],
        "companies": ["Production companies", "Studios", "Streaming services", "Advertising agencies", "News outlets", "YouTube"],
        "learningPath": "Production Fundamentals (1-2 months)",
        "relevanceScore": 68,
        "confidenceLevel": 70,
        "matchReasons": ["Production interest", "Team collaboration"],
        "minExperienceYears": 0,
        "maxExperienceYears": 2,
        "minSalary": 35000,
        "maxSalary": 50000
    },
    {
        "title": "Content Creator",
        "careerType": "content-creator",
        "description": "Create engaging content for digital platforms, develop creative concepts, manage content calendars.",
        "salaryRange": "$40,000 - $70,000",
        "experienceLevel": "junior",
        "requiredTechnicalSkills": ["Content Creation", "Social Media", "Basic Video Editing", "Photography", "Writing"],
        "requiredSoftSkills": ["Creativity", "Communication", "Storytelling", "Trend Awareness", "Self-Motivation"],
        "companies": ["Brands", "Agencies", "Influencer networks", "Startups", "Media companies", "Freelance"],
        "learningPath": "Content Creation Mastery (2-3 months)",
        "relevanceScore": 75,
        "confidenceLevel": 72,
        "matchReasons": ["Creative storytelling", "Digital native skills"],
        "minExperienceYears": 0,
        "maxExperienceYears": 4,
        "minSalary": 40000,
        "maxSalary": 70000
    },
    {
        "title": "Art Teacher",
        "careerType": "art-teacher",
        "description": "Teach art techniques and creative expression to students, develop curriculum, inspire artistic growth.",
        "salaryRange": "$45,000 - $70,000",
        "experienceLevel": "junior",
        "requiredTechnicalSkills": ["Art Techniques", "Curriculum Development", "Classroom Management", "Art History", "Various Media"],
        "requiredSoftSkills": ["Teaching", "Patience", "Communication", "Inspiration", "Empathy"],
        "companies": ["Schools", "Art centers", "Community colleges", "Private studios", "Museums", "Online platforms"],
        "learningPath": "Art Education Certification (4-6 months)",
        "relevanceScore": 70,
        "confidenceLevel": 72,
        "matchReasons": ["Teaching passion", "Artistic knowledge"],
        "minExperienceYears": 0,
        "maxExperienceYears": 5,
        "minSalary": 45000,
        "maxSalary": 70000
    },

    # SPECIALIZED CREATIVE ROLES
    {
        "title": "3D Artist",
        "careerType": "3d-artist",
        "description": "Create 3D models, animations, and visual effects for games, films, and digital media.",
        "salaryRange": "$65,000 - $110,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["3D Modeling", "Maya/Blender", "Texturing", "Lighting", "Rendering"],
        "requiredSoftSkills": ["Creativity", "Attention to Detail", "Problem Solving", "Patience", "Collaboration"],
        "companies": ["Pixar", "Disney", "Epic Games", "Blizzard", "ILM", "Weta Digital"],
        "learningPath": "3D Art and Animation (4-6 months)",
        "relevanceScore": 82,
        "confidenceLevel": 80,
        "matchReasons": ["3D visualization skills", "Technical artistry"],
        "minExperienceYears": 3,
        "maxExperienceYears": 10,
        "minSalary": 65000,
        "maxSalary": 110000
    },
    {
        "title": "Game Artist",
        "careerType": "game-artist",
        "description": "Create visual assets for video games including characters, environments, and UI elements.",
        "salaryRange": "$60,000 - $100,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Game Art", "3D Modeling", "Texturing", "Concept Art", "Unity/Unreal"],
        "requiredSoftSkills": ["Creativity", "Gaming Passion", "Collaboration", "Problem Solving", "Adaptability"],
        "companies": ["Epic Games", "Blizzard", "EA", "Ubisoft", "Riot Games", "Indie studios"],
        "learningPath": "Game Art Specialization (4-6 months)",
        "relevanceScore": 78,
        "confidenceLevel": 75,
        "matchReasons": ["Gaming interest", "Digital art skills"],
        "minExperienceYears": 3,
        "maxExperienceYears": 10,
        "minSalary": 60000,
        "maxSalary": 100000
    },
    {
        "title": "Concept Artist",
        "careerType": "concept-artist",
        "description": "Create visual concepts and designs for entertainment media, games, films, and products.",
        "salaryRange": "$70,000 - $120,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Concept Art", "Digital Painting", "Photoshop", "3D Sketching", "Visual Development"],
        "requiredSoftSkills": ["Imagination", "Artistic Vision", "Communication", "Adaptability", "Storytelling"],
        "companies": ["Disney", "Pixar", "Marvel", "Blizzard", "Riot Games", "Netflix"],
        "learningPath": "Concept Art Mastery (4-6 months)",
        "relevanceScore": 85,
        "confidenceLevel": 82,
        "matchReasons": ["Conceptual thinking", "Visual storytelling"],
        "minExperienceYears": 4,
        "maxExperienceYears": 12,
        "minSalary": 70000,
        "maxSalary": 120000
    },
    {
        "title": "Sound Designer",
        "careerType": "sound-designer",
        "description": "Create and edit audio content for films, games, and digital media, design sound effects and atmospheres.",
        "salaryRange": "$55,000 - $95,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Audio Editing", "Pro Tools", "Sound Design", "Foley", "Audio Post-Production"],
        "requiredSoftSkills": ["Creativity", "Attention to Detail", "Patience", "Collaboration", "Technical Aptitude"],
        "companies": ["Skywalker Sound", "Disney", "Netflix", "Game studios", "Audio post facilities", "Freelance"],
        "learningPath": "Sound Design Certification (3-4 months)",
        "relevanceScore": 75,
        "confidenceLevel": 72,
        "matchReasons": ["Audio creativity", "Technical skills"],
        "minExperienceYears": 3,
        "maxExperienceYears": 10,
        "minSalary": 55000,
        "maxSalary": 95000
    },
    {
        "title": "Animator",
        "careerType": "animator",
        "description": "Create animated sequences for films, TV shows, games, and digital media using various animation techniques.",
        "salaryRange": "$60,000 - $105,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["2D/3D Animation", "Maya", "After Effects", "Character Animation", "Storyboarding"],
        "requiredSoftSkills": ["Creativity", "Storytelling", "Patience", "Attention to Detail", "Collaboration"],
        "companies": ["Pixar", "Disney", "DreamWorks", "Netflix", "Cartoon Network", "Animation studios"],
        "learningPath": "Animation Fundamentals (4-6 months)",
        "relevanceScore": 80,
        "confidenceLevel": 78,
        "matchReasons": ["Animation interest", "Visual storytelling"],
        "minExperienceYears": 3,
        "maxExperienceYears": 10,
        "minSalary": 60000,
        "maxSalary": 105000
    }
]