"""
Education & Training Career Database
Part of comprehensive career database expansion
"""

EDUCATION_CAREERS = [
    # K-12 EDUCATION
    {
        "title": "Elementary School Teacher",
        "careerType": "elementary-teacher",
        "description": "Teach basic academic subjects to elementary school students, develop lesson plans, assess student progress.",
        "salaryRange": "$45,000 - $65,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Curriculum Development", "Classroom Management", "Educational Technology", "Assessment"],
        "requiredSoftSkills": ["Patience", "Communication", "Creativity", "Empathy"],
        "companies": ["Public Schools", "Private Schools", "Charter Schools", "International Schools"],
        "learningPath": "Bachelor's in Education + Teaching License (4-5 years)",
        "relevanceScore": 75,
        "confidenceLevel": 80,
        "matchReasons": ["Teaching passion", "Working with children", "Educational impact"],
        "minExperienceYears": 0,
        "maxExperienceYears": 40,
        "minSalary": 45000,
        "maxSalary": 65000
    },
    {
        "title": "High School Teacher",
        "careerType": "high-school-teacher",
        "description": "Teach specific subjects to high school students, prepare students for college and careers.",
        "salaryRange": "$48,000 - $70,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Subject Matter Expertise", "Curriculum Development", "Educational Technology", "Assessment"],
        "requiredSoftSkills": ["Communication", "Leadership", "Patience", "Adaptability"],
        "companies": ["Public Schools", "Private Schools", "Charter Schools", "Online Schools"],
        "learningPath": "Bachelor's in Subject + Teaching Certification (4-5 years)",
        "relevanceScore": 78,
        "confidenceLevel": 82,
        "matchReasons": ["Subject expertise", "Adolescent development", "Academic preparation"],
        "minExperienceYears": 0,
        "maxExperienceYears": 40,
        "minSalary": 48000,
        "maxSalary": 70000
    },
    {
        "title": "School Principal",
        "careerType": "school-principal",
        "description": "Lead school operations, manage staff, ensure educational quality, handle administrative duties.",
        "salaryRange": "$85,000 - $120,000",
        "experienceLevel": "senior",
        "requiredTechnicalSkills": ["Educational Leadership", "Budget Management", "Staff Development", "Curriculum Oversight"],
        "requiredSoftSkills": ["Leadership", "Communication", "Problem Solving", "Decision Making"],
        "companies": ["Public Schools", "Private Schools", "Charter Schools"],
        "learningPath": "Teaching Experience + Master's in Educational Leadership (8-12 years)",
        "relevanceScore": 82,
        "confidenceLevel": 85,
        "matchReasons": ["Educational leadership", "Administrative skills", "School management"],
        "minExperienceYears": 8,
        "maxExperienceYears": 35,
        "minSalary": 85000,
        "maxSalary": 120000
    },
    {
        "title": "School Counselor",
        "careerType": "school-counselor",
        "description": "Provide academic and personal counseling to students, help with college and career planning.",
        "salaryRange": "$50,000 - $70,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Counseling", "Student Assessment", "Career Guidance", "Crisis Intervention"],
        "requiredSoftSkills": ["Empathy", "Communication", "Problem Solving", "Confidentiality"],
        "companies": ["Public Schools", "Private Schools", "Community Colleges"],
        "learningPath": "Master's in School Counseling + Certification (5-6 years)",
        "relevanceScore": 80,
        "confidenceLevel": 83,
        "matchReasons": ["Student support", "Counseling skills", "Educational guidance"],
        "minExperienceYears": 2,
        "maxExperienceYears": 35,
        "minSalary": 50000,
        "maxSalary": 70000
    },
    {
        "title": "Middle School Teacher",
        "careerType": "middle-school-teacher",
        "description": "Teach middle grade students during critical developmental years, bridge elementary and high school education.",
        "salaryRange": "$46,000 - $68,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Adolescent Development", "Subject Integration", "Classroom Management", "Differentiated Instruction"],
        "requiredSoftSkills": ["Patience", "Flexibility", "Communication", "Understanding"],
        "companies": ["Public Schools", "Private Schools", "Charter Schools"],
        "learningPath": "Bachelor's in Education + Middle Grades Certification (4-5 years)",
        "relevanceScore": 76,
        "confidenceLevel": 81,
        "matchReasons": ["Middle grade expertise", "Adolescent development", "Educational transition"],
        "minExperienceYears": 0,
        "maxExperienceYears": 40,
        "minSalary": 46000,
        "maxSalary": 68000
    },
    {
        "title": "Special Education Teacher",
        "careerType": "special-education-teacher",
        "description": "Work with students with disabilities, develop individualized education programs, provide specialized instruction.",
        "salaryRange": "$50,000 - $75,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Special Education Law", "IEP Development", "Behavioral Interventions", "Assistive Technology"],
        "requiredSoftSkills": ["Patience", "Empathy", "Advocacy", "Collaboration"],
        "companies": ["Public Schools", "Private Schools", "Special Education Centers"],
        "learningPath": "Bachelor's in Special Education + Certification (4-5 years)",
        "relevanceScore": 85,
        "confidenceLevel": 88,
        "matchReasons": ["Special needs advocacy", "Individualized instruction", "Inclusive education"],
        "minExperienceYears": 0,
        "maxExperienceYears": 35,
        "minSalary": 50000,
        "maxSalary": 75000
    },
    {
        "title": "Assistant Principal",
        "careerType": "assistant-principal",
        "description": "Support principal in school administration, handle discipline, supervise staff, manage daily operations.",
        "salaryRange": "$65,000 - $90,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Educational Administration", "Staff Supervision", "Student Discipline", "Curriculum Support"],
        "requiredSoftSkills": ["Leadership", "Communication", "Problem Solving", "Diplomacy"],
        "companies": ["Public Schools", "Private Schools", "Charter Schools"],
        "learningPath": "Teaching Experience + Master's in Educational Leadership (6-8 years)",
        "relevanceScore": 79,
        "confidenceLevel": 82,
        "matchReasons": ["Administrative leadership", "Educational management", "Staff development"],
        "minExperienceYears": 5,
        "maxExperienceYears": 30,
        "minSalary": 65000,
        "maxSalary": 90000
    },
    {
        "title": "Curriculum Coordinator",
        "careerType": "curriculum-coordinator",
        "description": "Develop and implement curriculum standards, train teachers, evaluate educational programs.",
        "salaryRange": "$60,000 - $85,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Curriculum Development", "Educational Standards", "Teacher Training", "Program Evaluation"],
        "requiredSoftSkills": ["Leadership", "Communication", "Analytical Thinking", "Collaboration"],
        "companies": ["School Districts", "Educational Publishers", "State Education Departments"],
        "learningPath": "Teaching Experience + Master's in Curriculum & Instruction (6-8 years)",
        "relevanceScore": 81,
        "confidenceLevel": 84,
        "matchReasons": ["Curriculum expertise", "Educational leadership", "Program development"],
        "minExperienceYears": 5,
        "maxExperienceYears": 30,
        "minSalary": 60000,
        "maxSalary": 85000
    },
    {
        "title": "School Psychologist",
        "careerType": "school-psychologist",
        "description": "Assess student learning and behavioral needs, provide counseling, support special education services.",
        "salaryRange": "$65,000 - $95,000",
        "experienceLevel": "senior",
        "requiredTechnicalSkills": ["Psychological Assessment", "Behavioral Analysis", "Crisis Intervention", "Special Education Law"],
        "requiredSoftSkills": ["Empathy", "Communication", "Problem Solving", "Confidentiality"],
        "companies": ["Public Schools", "Private Schools", "Educational Clinics"],
        "learningPath": "Master's/Specialist in School Psychology + Certification (6-7 years)",
        "relevanceScore": 83,
        "confidenceLevel": 86,
        "matchReasons": ["Student mental health", "Educational psychology", "Assessment skills"],
        "minExperienceYears": 3,
        "maxExperienceYears": 35,
        "minSalary": 65000,
        "maxSalary": 95000
    },
    {
        "title": "Reading Specialist",
        "careerType": "reading-specialist",
        "description": "Provide specialized reading instruction, assess reading difficulties, support literacy programs.",
        "salaryRange": "$52,000 - $72,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Reading Assessment", "Literacy Instruction", "Phonics", "Reading Intervention"],
        "requiredSoftSkills": ["Patience", "Communication", "Analytical Thinking", "Encouragement"],
        "companies": ["Public Schools", "Private Schools", "Tutoring Centers"],
        "learningPath": "Teaching Experience + Master's in Reading Education (5-7 years)",
        "relevanceScore": 78,
        "confidenceLevel": 81,
        "matchReasons": ["Literacy expertise", "Reading intervention", "Student support"],
        "minExperienceYears": 3,
        "maxExperienceYears": 30,
        "minSalary": 52000,
        "maxSalary": 72000
    },
    {
        "title": "ESL Teacher",
        "careerType": "esl-teacher",
        "description": "Teach English to non-native speakers, develop language learning programs, support multicultural education.",
        "salaryRange": "$48,000 - $70,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Second Language Acquisition", "ESL Methodology", "Cultural Competency", "Language Assessment"],
        "requiredSoftSkills": ["Cultural Sensitivity", "Patience", "Communication", "Adaptability"],
        "companies": ["Public Schools", "Language Schools", "Community Colleges", "International Schools"],
        "learningPath": "Bachelor's + ESL Certification or TESOL (4-5 years)",
        "relevanceScore": 80,
        "confidenceLevel": 83,
        "matchReasons": ["Language instruction", "Cultural diversity", "Communication skills"],
        "minExperienceYears": 0,
        "maxExperienceYears": 35,
        "minSalary": 48000,
        "maxSalary": 70000
    },
    {
        "title": "Substitute Teacher",
        "careerType": "substitute-teacher",
        "description": "Provide temporary classroom instruction, maintain classroom management, follow lesson plans.",
        "salaryRange": "$25,000 - $45,000",
        "experienceLevel": "entry",
        "requiredTechnicalSkills": ["Classroom Management", "Adaptability", "Basic Subject Knowledge", "Following Instructions"],
        "requiredSoftSkills": ["Flexibility", "Communication", "Quick Learning", "Patience"],
        "companies": ["Public Schools", "Private Schools", "Substitute Services"],
        "learningPath": "Bachelor's Degree + Substitute Certification (4 years)",
        "relevanceScore": 70,
        "confidenceLevel": 75,
        "matchReasons": ["Teaching interest", "Flexibility", "Educational support"],
        "minExperienceYears": 0,
        "maxExperienceYears": 40,
        "minSalary": 25000,
        "maxSalary": 45000
    },

    # HIGHER EDUCATION
    {
        "title": "College Professor",
        "careerType": "college-professor",
        "description": "Teach undergraduate and graduate courses, conduct research, publish academic work.",
        "salaryRange": "$65,000 - $120,000",
        "experienceLevel": "senior",
        "requiredTechnicalSkills": ["Research", "Academic Writing", "Teaching", "Grant Writing"],
        "requiredSoftSkills": ["Critical Thinking", "Communication", "Mentoring", "Intellectual Curiosity"],
        "companies": ["Universities", "Community Colleges", "Research Institutions"],
        "learningPath": "PhD in Field + Postdoc Experience (8-12 years)",
        "relevanceScore": 85,
        "confidenceLevel": 88,
        "matchReasons": ["Academic expertise", "Research interest", "Higher education passion"],
        "minExperienceYears": 6,
        "maxExperienceYears": 40,
        "minSalary": 65000,
        "maxSalary": 120000
    },
    {
        "title": "University Administrator",
        "careerType": "university-administrator",
        "description": "Manage university operations, student services, academic programs, and institutional planning.",
        "salaryRange": "$75,000 - $130,000",
        "experienceLevel": "senior",
        "requiredTechnicalSkills": ["Higher Education Administration", "Budget Management", "Policy Development", "Strategic Planning"],
        "requiredSoftSkills": ["Leadership", "Communication", "Problem Solving", "Collaboration"],
        "companies": ["Universities", "Community Colleges", "Educational Organizations"],
        "learningPath": "Master's in Higher Education Administration (5-8 years)",
        "relevanceScore": 80,
        "confidenceLevel": 82,
        "matchReasons": ["Administrative skills", "Higher education focus", "Institutional leadership"],
        "minExperienceYears": 5,
        "maxExperienceYears": 35,
        "minSalary": 75000,
        "maxSalary": 130000
    },
    {
        "title": "Academic Advisor",
        "careerType": "academic-advisor",
        "description": "Guide students in course selection, degree planning, and academic goal achievement.",
        "salaryRange": "$40,000 - $60,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Academic Planning", "Degree Requirements", "Student Information Systems", "Career Counseling"],
        "requiredSoftSkills": ["Communication", "Empathy", "Problem Solving", "Organization"],
        "companies": ["Universities", "Community Colleges", "Online Universities"],
        "learningPath": "Bachelor's + Student Affairs Experience (4-6 years)",
        "relevanceScore": 77,
        "confidenceLevel": 80,
        "matchReasons": ["Student guidance", "Academic planning", "Educational support"],
        "minExperienceYears": 1,
        "maxExperienceYears": 30,
        "minSalary": 40000,
        "maxSalary": 60000
    },
    {
        "title": "Research Scientist",
        "careerType": "research-scientist",
        "description": "Conduct scientific research, publish findings, secure funding, mentor graduate students.",
        "salaryRange": "$70,000 - $110,000",
        "experienceLevel": "senior",
        "requiredTechnicalSkills": ["Research Methodology", "Data Analysis", "Grant Writing", "Scientific Writing"],
        "requiredSoftSkills": ["Critical Thinking", "Problem Solving", "Collaboration", "Persistence"],
        "companies": ["Universities", "Research Institutes", "Government Labs", "Private Research"],
        "learningPath": "PhD + Postdoc Experience (8-12 years)",
        "relevanceScore": 88,
        "confidenceLevel": 90,
        "matchReasons": ["Research expertise", "Scientific inquiry", "Knowledge advancement"],
        "minExperienceYears": 6,
        "maxExperienceYears": 40,
        "minSalary": 70000,
        "maxSalary": 110000
    },
    {
        "title": "Dean of Students",
        "careerType": "dean-of-students",
        "description": "Oversee student life, manage student services, handle disciplinary matters, support student success.",
        "salaryRange": "$90,000 - $140,000",
        "experienceLevel": "senior",
        "requiredTechnicalSkills": ["Student Affairs", "Crisis Management", "Policy Development", "Program Management"],
        "requiredSoftSkills": ["Leadership", "Communication", "Empathy", "Decision Making"],
        "companies": ["Universities", "Community Colleges", "Private Colleges"],
        "learningPath": "Master's in Student Affairs + Administrative Experience (8-12 years)",
        "relevanceScore": 82,
        "confidenceLevel": 85,
        "matchReasons": ["Student leadership", "Higher education administration", "Student development"],
        "minExperienceYears": 8,
        "maxExperienceYears": 35,
        "minSalary": 90000,
        "maxSalary": 140000
    },
    {
        "title": "Admissions Counselor",
        "careerType": "admissions-counselor",
        "description": "Recruit prospective students, evaluate applications, conduct campus tours, support enrollment goals.",
        "salaryRange": "$38,000 - $55,000",
        "experienceLevel": "entry",
        "requiredTechnicalSkills": ["Admissions Process", "Student Recruitment", "Application Review", "Data Analysis"],
        "requiredSoftSkills": ["Communication", "Sales Skills", "Organization", "Relationship Building"],
        "companies": ["Universities", "Community Colleges", "Private Colleges"],
        "learningPath": "Bachelor's Degree + Admissions Training (4-5 years)",
        "relevanceScore": 75,
        "confidenceLevel": 78,
        "matchReasons": ["Student recruitment", "Higher education", "Communication skills"],
        "minExperienceYears": 0,
        "maxExperienceYears": 25,
        "minSalary": 38000,
        "maxSalary": 55000
    },
    {
        "title": "Registrar",
        "careerType": "registrar",
        "description": "Manage student records, oversee registration processes, ensure academic policy compliance.",
        "salaryRange": "$55,000 - $80,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Student Information Systems", "Academic Records", "Registration Systems", "Data Management"],
        "requiredSoftSkills": ["Attention to Detail", "Organization", "Communication", "Problem Solving"],
        "companies": ["Universities", "Community Colleges", "Private Schools"],
        "learningPath": "Bachelor's + Higher Education Experience (4-6 years)",
        "relevanceScore": 76,
        "confidenceLevel": 79,
        "matchReasons": ["Data management", "Academic administration", "Student services"],
        "minExperienceYears": 2,
        "maxExperienceYears": 30,
        "minSalary": 55000,
        "maxSalary": 80000
    },
    {
        "title": "Student Affairs Coordinator",
        "careerType": "student-affairs-coordinator",
        "description": "Coordinate student programs, manage campus activities, support student organizations.",
        "salaryRange": "$42,000 - $62,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Program Planning", "Event Management", "Student Development", "Budget Management"],
        "requiredSoftSkills": ["Organization", "Communication", "Leadership", "Creativity"],
        "companies": ["Universities", "Community Colleges", "Student Organizations"],
        "learningPath": "Bachelor's in Student Affairs or related field (4-5 years)",
        "relevanceScore": 78,
        "confidenceLevel": 81,
        "matchReasons": ["Student engagement", "Program coordination", "Campus life"],
        "minExperienceYears": 1,
        "maxExperienceYears": 25,
        "minSalary": 42000,
        "maxSalary": 62000
    },

    # CORPORATE TRAINING
    {
        "title": "Corporate Trainer",
        "careerType": "corporate-trainer",
        "description": "Design and deliver training programs for employees, assess training needs, measure effectiveness.",
        "salaryRange": "$55,000 - $85,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Training Design", "Adult Learning", "Presentation Skills", "Learning Management Systems"],
        "requiredSoftSkills": ["Communication", "Facilitation", "Adaptability", "Patience"],
        "companies": ["Corporations", "Training Companies", "Consulting Firms", "Government"],
        "learningPath": "Bachelor's + Training Certification (4-6 years)",
        "relevanceScore": 78,
        "confidenceLevel": 80,
        "matchReasons": ["Training expertise", "Adult education", "Professional development"],
        "minExperienceYears": 2,
        "maxExperienceYears": 30,
        "minSalary": 55000,
        "maxSalary": 85000
    },
    {
        "title": "Instructional Designer",
        "careerType": "instructional-designer",
        "description": "Create educational content and curricula, design online learning experiences, develop training materials.",
        "salaryRange": "$60,000 - $90,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Instructional Design", "E-Learning Development", "Learning Management Systems", "Educational Technology"],
        "requiredSoftSkills": ["Creativity", "Problem Solving", "Communication", "Attention to Detail"],
        "companies": ["Educational Technology", "Corporations", "Universities", "Training Companies"],
        "learningPath": "Master's in Instructional Design (4-6 years)",
        "relevanceScore": 82,
        "confidenceLevel": 85,
        "matchReasons": ["Educational technology", "Content creation", "Learning design"],
        "minExperienceYears": 2,
        "maxExperienceYears": 25,
        "minSalary": 60000,
        "maxSalary": 90000
    },
    {
        "title": "Learning and Development Manager",
        "careerType": "learning-development-manager",
        "description": "Lead organizational learning initiatives, manage training teams, develop learning strategies.",
        "salaryRange": "$75,000 - $110,000",
        "experienceLevel": "senior",
        "requiredTechnicalSkills": ["Learning Strategy", "Team Management", "Budget Management", "Performance Analysis"],
        "requiredSoftSkills": ["Leadership", "Strategic Thinking", "Communication", "Change Management"],
        "companies": ["Large Corporations", "Consulting Firms", "Government Agencies"],
        "learningPath": "Bachelor's + L&D Experience + Management Training (6-10 years)",
        "relevanceScore": 85,
        "confidenceLevel": 87,
        "matchReasons": ["Learning leadership", "Strategic development", "Team management"],
        "minExperienceYears": 5,
        "maxExperienceYears": 30,
        "minSalary": 75000,
        "maxSalary": 110000
    },
    {
        "title": "Training Specialist",
        "careerType": "training-specialist",
        "description": "Develop specific training programs, conduct skills assessments, provide specialized instruction.",
        "salaryRange": "$48,000 - $70,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Training Development", "Skills Assessment", "Adult Learning Principles", "Training Evaluation"],
        "requiredSoftSkills": ["Communication", "Patience", "Analytical Thinking", "Adaptability"],
        "companies": ["Corporations", "Training Organizations", "Government", "Non-profits"],
        "learningPath": "Bachelor's + Training Certification (4-5 years)",
        "relevanceScore": 76,
        "confidenceLevel": 79,
        "matchReasons": ["Specialized training", "Skills development", "Adult education"],
        "minExperienceYears": 1,
        "maxExperienceYears": 25,
        "minSalary": 48000,
        "maxSalary": 70000
    },
    {
        "title": "E-Learning Developer",
        "careerType": "elearning-developer",
        "description": "Create interactive online learning content, develop multimedia educational materials, maintain learning platforms.",
        "salaryRange": "$58,000 - $85,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["E-Learning Authoring Tools", "Multimedia Development", "HTML/CSS", "Learning Management Systems"],
        "requiredSoftSkills": ["Creativity", "Technical Problem Solving", "Attention to Detail", "Communication"],
        "companies": ["EdTech Companies", "Corporations", "Universities", "Training Providers"],
        "learningPath": "Bachelor's in Education/IT + E-Learning Certification (4-6 years)",
        "relevanceScore": 83,
        "confidenceLevel": 86,
        "matchReasons": ["Digital learning", "Technology skills", "Content development"],
        "minExperienceYears": 2,
        "maxExperienceYears": 25,
        "minSalary": 58000,
        "maxSalary": 85000
    },
    {
        "title": "Organizational Development Consultant",
        "careerType": "od-consultant",
        "description": "Help organizations improve performance through training, change management, and development programs.",
        "salaryRange": "$70,000 - $120,000",
        "experienceLevel": "senior",
        "requiredTechnicalSkills": ["Organizational Psychology", "Change Management", "Training Design", "Performance Analysis"],
        "requiredSoftSkills": ["Consulting Skills", "Communication", "Strategic Thinking", "Relationship Building"],
        "companies": ["Consulting Firms", "Large Corporations", "Government", "Non-profits"],
        "learningPath": "Master's in OD/Psychology + Consulting Experience (6-10 years)",
        "relevanceScore": 87,
        "confidenceLevel": 89,
        "matchReasons": ["Organizational improvement", "Strategic consulting", "Change leadership"],
        "minExperienceYears": 5,
        "maxExperienceYears": 35,
        "minSalary": 70000,
        "maxSalary": 120000
    },

    # EDUCATIONAL SUPPORT
    {
        "title": "Librarian",
        "careerType": "librarian",
        "description": "Manage library resources, help patrons find information, organize collections, provide research assistance.",
        "salaryRange": "$45,000 - $65,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Information Science", "Database Management", "Research Skills", "Digital Resources"],
        "requiredSoftSkills": ["Organization", "Communication", "Customer Service", "Attention to Detail"],
        "companies": ["Public Libraries", "Academic Libraries", "School Libraries", "Special Libraries"],
        "learningPath": "Master's in Library Science (5-6 years)",
        "relevanceScore": 75,
        "confidenceLevel": 78,
        "matchReasons": ["Information management", "Research skills", "Public service"],
        "minExperienceYears": 0,
        "maxExperienceYears": 35,
        "minSalary": 45000,
        "maxSalary": 65000
    },
    {
        "title": "Education Technology Specialist",
        "careerType": "edtech-specialist",
        "description": "Support technology integration in education, train teachers on educational software, manage school technology.",
        "salaryRange": "$50,000 - $75,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Educational Technology", "Network Administration", "Software Training", "Technical Support"],
        "requiredSoftSkills": ["Problem Solving", "Communication", "Patience", "Training"],
        "companies": ["School Districts", "Educational Technology Companies", "Universities"],
        "learningPath": "Bachelor's in Education/IT + Technology Certification (4-6 years)",
        "relevanceScore": 80,
        "confidenceLevel": 82,
        "matchReasons": ["Technology skills", "Educational focus", "Training abilities"],
        "minExperienceYears": 2,
        "maxExperienceYears": 30,
        "minSalary": 50000,
        "maxSalary": 75000
    },
    {
        "title": "Tutor",
        "careerType": "tutor",
        "description": "Provide individualized academic support, help students with specific subjects, improve learning outcomes.",
        "salaryRange": "$25,000 - $50,000",
        "experienceLevel": "entry",
        "requiredTechnicalSkills": ["Subject Matter Expertise", "Assessment", "Learning Strategies", "Progress Tracking"],
        "requiredSoftSkills": ["Patience", "Communication", "Encouragement", "Adaptability"],
        "companies": ["Tutoring Centers", "Private Practice", "Schools", "Online Platforms"],
        "learningPath": "Bachelor's Degree + Subject Expertise (4 years)",
        "relevanceScore": 72,
        "confidenceLevel": 75,
        "matchReasons": ["Individual instruction", "Academic support", "Student success"],
        "minExperienceYears": 0,
        "maxExperienceYears": 30,
        "minSalary": 25000,
        "maxSalary": 50000
    },
    {
        "title": "Educational Consultant",
        "careerType": "educational-consultant",
        "description": "Advise schools and organizations on educational practices, curriculum development, and improvement strategies.",
        "salaryRange": "$60,000 - $100,000",
        "experienceLevel": "senior",
        "requiredTechnicalSkills": ["Educational Assessment", "Curriculum Design", "School Improvement", "Data Analysis"],
        "requiredSoftSkills": ["Consulting Skills", "Communication", "Problem Solving", "Leadership"],
        "companies": ["Consulting Firms", "Independent Practice", "Educational Organizations"],
        "learningPath": "Advanced Degree + Educational Experience (8-12 years)",
        "relevanceScore": 84,
        "confidenceLevel": 87,
        "matchReasons": ["Educational expertise", "Consulting skills", "School improvement"],
        "minExperienceYears": 8,
        "maxExperienceYears": 35,
        "minSalary": 60000,
        "maxSalary": 100000
    },
    {
        "title": "Education Program Coordinator",
        "careerType": "education-program-coordinator",
        "description": "Coordinate educational programs, manage resources, support program implementation and evaluation.",
        "salaryRange": "$45,000 - $65,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Program Management", "Resource Coordination", "Budget Planning", "Evaluation"],
        "requiredSoftSkills": ["Organization", "Communication", "Leadership", "Problem Solving"],
        "companies": ["Non-profits", "Government Agencies", "Educational Organizations", "Foundations"],
        "learningPath": "Bachelor's in Education/Management + Program Experience (4-6 years)",
        "relevanceScore": 79,
        "confidenceLevel": 82,
        "matchReasons": ["Program coordination", "Educational impact", "Resource management"],
        "minExperienceYears": 2,
        "maxExperienceYears": 25,
        "minSalary": 45000,
        "maxSalary": 65000
    },
    {
        "title": "Academic Coach",
        "careerType": "academic-coach",
        "description": "Provide one-on-one academic support, help students develop study skills and learning strategies.",
        "salaryRange": "$35,000 - $55,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Learning Strategies", "Study Skills", "Academic Assessment", "Goal Setting"],
        "requiredSoftSkills": ["Mentoring", "Patience", "Motivation", "Communication"],
        "companies": ["Tutoring Centers", "Schools", "Private Practice", "Online Platforms"],
        "learningPath": "Bachelor's + Academic Coaching Certification (4-5 years)",
        "relevanceScore": 74,
        "confidenceLevel": 77,
        "matchReasons": ["Student mentoring", "Academic support", "Individual coaching"],
        "minExperienceYears": 1,
        "maxExperienceYears": 20,
        "minSalary": 35000,
        "maxSalary": 55000
    },
    {
        "title": "Museum Educator",
        "careerType": "museum-educator",
        "description": "Develop and deliver educational programs in museums, create interactive learning experiences.",
        "salaryRange": "$40,000 - $60,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Museum Studies", "Program Development", "Public Speaking", "Educational Design"],
        "requiredSoftSkills": ["Creativity", "Communication", "Cultural Awareness", "Enthusiasm"],
        "companies": ["Museums", "Cultural Institutions", "Science Centers", "Historical Sites"],
        "learningPath": "Bachelor's in Education/Museum Studies (4-5 years)",
        "relevanceScore": 76,
        "confidenceLevel": 79,
        "matchReasons": ["Cultural education", "Public engagement", "Creative instruction"],
        "minExperienceYears": 1,
        "maxExperienceYears": 30,
        "minSalary": 40000,
        "maxSalary": 60000
    },
    {
        "title": "Adult Education Instructor",
        "careerType": "adult-education-instructor",
        "description": "Teach adult learners in continuing education, GED preparation, and professional development programs.",
        "salaryRange": "$42,000 - $62,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Adult Learning Principles", "Curriculum Adaptation", "Assessment", "Program Planning"],
        "requiredSoftSkills": ["Patience", "Flexibility", "Encouragement", "Cultural Sensitivity"],
        "companies": ["Community Colleges", "Adult Learning Centers", "Community Organizations"],
        "learningPath": "Bachelor's + Adult Education Certification (4-5 years)",
        "relevanceScore": 77,
        "confidenceLevel": 80,
        "matchReasons": ["Adult education", "Lifelong learning", "Community impact"],
        "minExperienceYears": 1,
        "maxExperienceYears": 35,
        "minSalary": 42000,
        "maxSalary": 62000
    },
    {
        "title": "Educational Writer",
        "careerType": "educational-writer",
        "description": "Create educational content, textbooks, curriculum materials, and learning resources.",
        "salaryRange": "$50,000 - $75,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Educational Writing", "Curriculum Design", "Research", "Content Development"],
        "requiredSoftSkills": ["Writing Skills", "Creativity", "Attention to Detail", "Subject Knowledge"],
        "companies": ["Educational Publishers", "EdTech Companies", "Freelance", "Curriculum Companies"],
        "learningPath": "Bachelor's in Education/English + Writing Experience (4-6 years)",
        "relevanceScore": 81,
        "confidenceLevel": 84,
        "matchReasons": ["Content creation", "Educational impact", "Writing expertise"],
        "minExperienceYears": 2,
        "maxExperienceYears": 30,
        "minSalary": 50000,
        "maxSalary": 75000
    },
    {
        "title": "Education Policy Analyst",
        "careerType": "education-policy-analyst",
        "description": "Research and analyze education policies, provide recommendations for policy improvements.",
        "salaryRange": "$65,000 - $95,000",
        "experienceLevel": "senior",
        "requiredTechnicalSkills": ["Policy Analysis", "Research Methods", "Data Analysis", "Report Writing"],
        "requiredSoftSkills": ["Critical Thinking", "Communication", "Problem Solving", "Analytical Skills"],
        "companies": ["Government Agencies", "Think Tanks", "Research Organizations", "Non-profits"],
        "learningPath": "Master's in Public Policy/Education + Research Experience (6-8 years)",
        "relevanceScore": 86,
        "confidenceLevel": 88,
        "matchReasons": ["Policy expertise", "Educational research", "System improvement"],
        "minExperienceYears": 5,
        "maxExperienceYears": 35,
        "minSalary": 65000,
        "maxSalary": 95000
    },
    {
        "title": "Distance Learning Coordinator",
        "careerType": "distance-learning-coordinator",
        "description": "Manage online education programs, support remote learning initiatives, coordinate virtual instruction.",
        "salaryRange": "$55,000 - $80,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Online Learning Platforms", "Educational Technology", "Program Management", "Technical Support"],
        "requiredSoftSkills": ["Organization", "Communication", "Problem Solving", "Adaptability"],
        "companies": ["Universities", "K-12 Schools", "Corporate Training", "EdTech Companies"],
        "learningPath": "Bachelor's in Education + Online Learning Certification (4-6 years)",
        "relevanceScore": 82,
        "confidenceLevel": 85,
        "matchReasons": ["Digital education", "Remote learning", "Technology integration"],
        "minExperienceYears": 3,
        "maxExperienceYears": 25,
        "minSalary": 55000,
        "maxSalary": 80000
    },
    {
        "title": "Education Data Analyst",
        "careerType": "education-data-analyst",
        "description": "Analyze educational data, create reports on student performance, support data-driven decision making.",
        "salaryRange": "$60,000 - $85,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Data Analysis", "Statistical Software", "Database Management", "Report Generation"],
        "requiredSoftSkills": ["Analytical Thinking", "Attention to Detail", "Communication", "Problem Solving"],
        "companies": ["School Districts", "State Education Departments", "Research Organizations", "EdTech Companies"],
        "learningPath": "Bachelor's in Education/Statistics + Data Analysis Training (4-6 years)",
        "relevanceScore": 84,
        "confidenceLevel": 87,
        "matchReasons": ["Data expertise", "Educational research", "Evidence-based improvement"],
        "minExperienceYears": 2,
        "maxExperienceYears": 30,
        "minSalary": 60000,
        "maxSalary": 85000
    },
    {
        "title": "Preschool Teacher",
        "careerType": "preschool-teacher",
        "description": "Teach and care for young children, develop early childhood education programs, support child development.",
        "salaryRange": "$30,000 - $45,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Early Childhood Development", "Play-Based Learning", "Child Assessment", "Safety Protocols"],
        "requiredSoftSkills": ["Patience", "Nurturing", "Communication", "Creativity"],
        "companies": ["Preschools", "Daycare Centers", "Head Start Programs", "Private Centers"],
        "learningPath": "Associate's/Bachelor's in Early Childhood Education (2-4 years)",
        "relevanceScore": 73,
        "confidenceLevel": 76,
        "matchReasons": ["Early childhood focus", "Child development", "Educational foundation"],
        "minExperienceYears": 0,
        "maxExperienceYears": 35,
        "minSalary": 30000,
        "maxSalary": 45000
    },
    {
        "title": "Education Grant Writer",
        "careerType": "education-grant-writer",
        "description": "Write grant proposals to secure funding for educational programs and initiatives.",
        "salaryRange": "$50,000 - $75,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Grant Writing", "Research", "Budget Development", "Project Planning"],
        "requiredSoftSkills": ["Writing Skills", "Attention to Detail", "Persuasion", "Organization"],
        "companies": ["Schools", "Non-profits", "Universities", "Educational Organizations"],
        "learningPath": "Bachelor's + Grant Writing Experience/Certification (4-6 years)",
        "relevanceScore": 80,
        "confidenceLevel": 83,
        "matchReasons": ["Funding expertise", "Educational support", "Writing skills"],
        "minExperienceYears": 2,
        "maxExperienceYears": 30,
        "minSalary": 50000,
        "maxSalary": 75000
    }
]