"""
Education & Training Career Database
Part of comprehensive career database expansion
"""

EDUCATION_CAREERS = [
    # K-12 EDUCATION
    {
        "title": "Elementary School Teacher",
        "careerType": "elementary-teacher",
        "description": "Teach basic academic subjects to elementary school students, develop lesson plans, assess student progress.",
        "salaryRange": "$45,000 - $65,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Curriculum Development", "Classroom Management", "Educational Technology", "Assessment"],
        "requiredSoftSkills": ["Patience", "Communication", "Creativity", "Empathy"],
        "companies": ["Public Schools", "Private Schools", "Charter Schools", "International Schools"],
        "learningPath": "Bachelor's in Education + Teaching License (4-5 years)",
        "relevanceScore": 75,
        "confidenceLevel": 80,
        "matchReasons": ["Teaching passion", "Working with children", "Educational impact"],
        "minExperienceYears": 0,
        "maxExperienceYears": 40,
        "minSalary": 45000,
        "maxSalary": 65000
    },
    {
        "title": "High School Teacher",
        "careerType": "high-school-teacher",
        "description": "Teach specific subjects to high school students, prepare students for college and careers.",
        "salaryRange": "$48,000 - $70,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Subject Matter Expertise", "Curriculum Development", "Educational Technology", "Assessment"],
        "requiredSoftSkills": ["Communication", "Leadership", "Patience", "Adaptability"],
        "companies": ["Public Schools", "Private Schools", "Charter Schools", "Online Schools"],
        "learningPath": "Bachelor's in Subject + Teaching Certification (4-5 years)",
        "relevanceScore": 78,
        "confidenceLevel": 82,
        "matchReasons": ["Subject expertise", "Adolescent development", "Academic preparation"],
        "minExperienceYears": 0,
        "maxExperienceYears": 40,
        "minSalary": 48000,
        "maxSalary": 70000
    },
    {
        "title": "School Principal",
        "careerType": "school-principal",
        "description": "Lead school operations, manage staff, ensure educational quality, handle administrative duties.",
        "salaryRange": "$85,000 - $120,000",
        "experienceLevel": "senior",
        "requiredTechnicalSkills": ["Educational Leadership", "Budget Management", "Staff Development", "Curriculum Oversight"],
        "requiredSoftSkills": ["Leadership", "Communication", "Problem Solving", "Decision Making"],
        "companies": ["Public Schools", "Private Schools", "Charter Schools"],
        "learningPath": "Teaching Experience + Master's in Educational Leadership (8-12 years)",
        "relevanceScore": 82,
        "confidenceLevel": 85,
        "matchReasons": ["Educational leadership", "Administrative skills", "School management"],
        "minExperienceYears": 8,
        "maxExperienceYears": 35,
        "minSalary": 85000,
        "maxSalary": 120000
    },
    {
        "title": "School Counselor",
        "careerType": "school-counselor",
        "description": "Provide academic and personal counseling to students, help with college and career planning.",
        "salaryRange": "$50,000 - $70,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Counseling", "Student Assessment", "Career Guidance", "Crisis Intervention"],
        "requiredSoftSkills": ["Empathy", "Communication", "Problem Solving", "Confidentiality"],
        "companies": ["Public Schools", "Private Schools", "Community Colleges"],
        "learningPath": "Master's in School Counseling + Certification (5-6 years)",
        "relevanceScore": 80,
        "confidenceLevel": 83,
        "matchReasons": ["Student support", "Counseling skills", "Educational guidance"],
        "minExperienceYears": 2,
        "maxExperienceYears": 35,
        "minSalary": 50000,
        "maxSalary": 70000
    },

    # HIGHER EDUCATION
    {
        "title": "College Professor",
        "careerType": "college-professor",
        "description": "Teach undergraduate and graduate courses, conduct research, publish academic work.",
        "salaryRange": "$65,000 - $120,000",
        "experienceLevel": "senior",
        "requiredTechnicalSkills": ["Research", "Academic Writing", "Teaching", "Grant Writing"],
        "requiredSoftSkills": ["Critical Thinking", "Communication", "Mentoring", "Intellectual Curiosity"],
        "companies": ["Universities", "Community Colleges", "Research Institutions"],
        "learningPath": "PhD in Field + Postdoc Experience (8-12 years)",
        "relevanceScore": 85,
        "confidenceLevel": 88,
        "matchReasons": ["Academic expertise", "Research interest", "Higher education passion"],
        "minExperienceYears": 6,
        "maxExperienceYears": 40,
        "minSalary": 65000,
        "maxSalary": 120000
    },
    {
        "title": "University Administrator",
        "careerType": "university-administrator",
        "description": "Manage university operations, student services, academic programs, and institutional planning.",
        "salaryRange": "$75,000 - $130,000",
        "experienceLevel": "senior",
        "requiredTechnicalSkills": ["Higher Education Administration", "Budget Management", "Policy Development", "Strategic Planning"],
        "requiredSoftSkills": ["Leadership", "Communication", "Problem Solving", "Collaboration"],
        "companies": ["Universities", "Community Colleges", "Educational Organizations"],
        "learningPath": "Master's in Higher Education Administration (5-8 years)",
        "relevanceScore": 80,
        "confidenceLevel": 82,
        "matchReasons": ["Administrative skills", "Higher education focus", "Institutional leadership"],
        "minExperienceYears": 5,
        "maxExperienceYears": 35,
        "minSalary": 75000,
        "maxSalary": 130000
    },

    # CORPORATE TRAINING
    {
        "title": "Corporate Trainer",
        "careerType": "corporate-trainer",
        "description": "Design and deliver training programs for employees, assess training needs, measure effectiveness.",
        "salaryRange": "$55,000 - $85,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Training Design", "Adult Learning", "Presentation Skills", "Learning Management Systems"],
        "requiredSoftSkills": ["Communication", "Facilitation", "Adaptability", "Patience"],
        "companies": ["Corporations", "Training Companies", "Consulting Firms", "Government"],
        "learningPath": "Bachelor's + Training Certification (4-6 years)",
        "relevanceScore": 78,
        "confidenceLevel": 80,
        "matchReasons": ["Training expertise", "Adult education", "Professional development"],
        "minExperienceYears": 2,
        "maxExperienceYears": 30,
        "minSalary": 55000,
        "maxSalary": 85000
    },
    {
        "title": "Instructional Designer",
        "careerType": "instructional-designer",
        "description": "Create educational content and curricula, design online learning experiences, develop training materials.",
        "salaryRange": "$60,000 - $90,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Instructional Design", "E-Learning Development", "Learning Management Systems", "Educational Technology"],
        "requiredSoftSkills": ["Creativity", "Problem Solving", "Communication", "Attention to Detail"],
        "companies": ["Educational Technology", "Corporations", "Universities", "Training Companies"],
        "learningPath": "Master's in Instructional Design (4-6 years)",
        "relevanceScore": 82,
        "confidenceLevel": 85,
        "matchReasons": ["Educational technology", "Content creation", "Learning design"],
        "minExperienceYears": 2,
        "maxExperienceYears": 25,
        "minSalary": 60000,
        "maxSalary": 90000
    },

    # EDUCATIONAL SUPPORT
    {
        "title": "Librarian",
        "careerType": "librarian",
        "description": "Manage library resources, help patrons find information, organize collections, provide research assistance.",
        "salaryRange": "$45,000 - $65,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Information Science", "Database Management", "Research Skills", "Digital Resources"],
        "requiredSoftSkills": ["Organization", "Communication", "Customer Service", "Attention to Detail"],
        "companies": ["Public Libraries", "Academic Libraries", "School Libraries", "Special Libraries"],
        "learningPath": "Master's in Library Science (5-6 years)",
        "relevanceScore": 75,
        "confidenceLevel": 78,
        "matchReasons": ["Information management", "Research skills", "Public service"],
        "minExperienceYears": 0,
        "maxExperienceYears": 35,
        "minSalary": 45000,
        "maxSalary": 65000
    },
    {
        "title": "Education Technology Specialist",
        "careerType": "edtech-specialist",
        "description": "Support technology integration in education, train teachers on educational software, manage school technology.",
        "salaryRange": "$50,000 - $75,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Educational Technology", "Network Administration", "Software Training", "Technical Support"],
        "requiredSoftSkills": ["Problem Solving", "Communication", "Patience", "Training"],
        "companies": ["School Districts", "Educational Technology Companies", "Universities"],
        "learningPath": "Bachelor's in Education/IT + Technology Certification (4-6 years)",
        "relevanceScore": 80,
        "confidenceLevel": 82,
        "matchReasons": ["Technology skills", "Educational focus", "Training abilities"],
        "minExperienceYears": 2,
        "maxExperienceYears": 30,
        "minSalary": 50000,
        "maxSalary": 75000
    }
]