"""
Healthcare & Medical Career Database
Part of comprehensive career database expansion - Phase 1A
"""

HEALTHCARE_CAREERS = [
    # MEDICAL DOCTORS & SPECIALISTS
    {
        "title": "Family Medicine Physician",
        "careerType": "family-medicine-physician",
        "description": "Provide comprehensive primary care for patients of all ages, manage chronic conditions, preventive care.",
        "salaryRange": "$200,000 - $280,000",
        "experienceLevel": "senior",
        "requiredTechnicalSkills": ["Medical Diagnosis", "Patient Care", "Medical Records", "Clinical Decision Making"],
        "requiredSoftSkills": ["Empathy", "Communication", "Critical Thinking", "Attention to Detail"],
        "companies": ["Hospitals", "Private Practice", "Healthcare Systems", "Community Health Centers"],
        "learningPath": "Medical School + Family Medicine Residency (7-8 years)",
        "relevanceScore": 85,
        "confidenceLevel": 90,
        "matchReasons": ["Healthcare interest", "Science background", "People-focused"],
        "minExperienceYears": 8,
        "maxExperienceYears": 40,
        "minSalary": 200000,
        "maxSalary": 280000
    },
    {
        "title": "Cardiologist",
        "careerType": "cardiologist",
        "description": "Diagnose and treat heart and cardiovascular diseases, perform cardiac procedures, manage complex cases.",
        "salaryRange": "$350,000 - $500,000",
        "experienceLevel": "executive",
        "requiredTechnicalSkills": ["Cardiology", "Cardiac Procedures", "Diagnostic Imaging", "Critical Care"],
        "requiredSoftSkills": ["Precision", "Communication", "Decision Making", "Stress Management"],
        "companies": ["Hospitals", "Cardiac Centers", "Private Practice", "Academic Medical Centers"],
        "learningPath": "Medical School + Internal Medicine + Cardiology Fellowship (10+ years)",
        "relevanceScore": 85,
        "confidenceLevel": 90,
        "matchReasons": ["Advanced medical training", "Specialized expertise", "High-stakes decision making"],
        "minExperienceYears": 10,
        "maxExperienceYears": 40,
        "minSalary": 350000,
        "maxSalary": 500000
    },
    {
        "title": "Pediatrician",
        "careerType": "pediatrician",
        "description": "Provide medical care for infants, children, and adolescents, manage developmental health.",
        "salaryRange": "$180,000 - $250,000",
        "experienceLevel": "senior",
        "requiredTechnicalSkills": ["Pediatric Medicine", "Child Development", "Immunizations", "Family Counseling"],
        "requiredSoftSkills": ["Patience", "Communication", "Empathy", "Child Interaction"],
        "companies": ["Pediatric Clinics", "Hospitals", "Private Practice", "Children's Hospitals"],
        "learningPath": "Medical School + Pediatrics Residency (7-8 years)",
        "relevanceScore": 85,
        "confidenceLevel": 90,
        "matchReasons": ["Child-focused care", "Preventive medicine", "Family interaction"],
        "minExperienceYears": 8,
        "maxExperienceYears": 40,
        "minSalary": 180000,
        "maxSalary": 250000
    },
    {
        "title": "Surgeon (General)",
        "careerType": "general-surgeon",
        "description": "Perform surgical procedures, manage pre/post-operative care, handle emergency surgeries.",
        "salaryRange": "$300,000 - $450,000",
        "experienceLevel": "executive",
        "requiredTechnicalSkills": ["Surgical Procedures", "Anatomy", "Emergency Medicine", "Surgical Technology"],
        "requiredSoftSkills": ["Precision", "Decision Making", "Stress Management", "Leadership"],
        "companies": ["Hospitals", "Surgical Centers", "Trauma Centers", "Private Practice"],
        "learningPath": "Medical School + General Surgery Residency (9+ years)",
        "relevanceScore": 85,
        "confidenceLevel": 90,
        "matchReasons": ["Surgical skills", "High-pressure performance", "Technical precision"],
        "minExperienceYears": 9,
        "maxExperienceYears": 40,
        "minSalary": 300000,
        "maxSalary": 450000
    },

    # NURSING PROFESSIONALS
    {
        "title": "Registered Nurse (RN)",
        "careerType": "registered-nurse",
        "description": "Provide patient care, administer medications, monitor patient conditions, educate patients and families.",
        "salaryRange": "$70,000 - $95,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Patient Care", "Medical Equipment", "Medication Administration", "Health Assessment"],
        "requiredSoftSkills": ["Compassion", "Communication", "Attention to Detail", "Stress Management"],
        "companies": ["Hospitals", "Clinics", "Nursing Homes", "Home Healthcare"],
        "learningPath": "Nursing Degree + RN License (2-4 years)",
        "relevanceScore": 80,
        "confidenceLevel": 85,
        "matchReasons": ["Patient care focus", "Healthcare interest", "Helping others"],
        "minExperienceYears": 0,
        "maxExperienceYears": 40,
        "minSalary": 70000,
        "maxSalary": 95000
    },
    {
        "title": "Nurse Practitioner",
        "careerType": "nurse-practitioner",
        "description": "Provide advanced nursing care, diagnose conditions, prescribe medications, manage patient care.",
        "salaryRange": "$110,000 - $140,000",
        "experienceLevel": "senior",
        "requiredTechnicalSkills": ["Advanced Practice Nursing", "Diagnosis", "Prescriptive Authority", "Patient Management"],
        "requiredSoftSkills": ["Clinical Judgment", "Communication", "Leadership", "Patient Advocacy"],
        "companies": ["Hospitals", "Clinics", "Private Practice", "Specialty Centers"],
        "learningPath": "RN + Master's in Nursing + Certification (6-8 years)",
        "relevanceScore": 85,
        "confidenceLevel": 88,
        "matchReasons": ["Advanced nursing practice", "Independent practice", "Patient care leadership"],
        "minExperienceYears": 4,
        "maxExperienceYears": 40,
        "minSalary": 110000,
        "maxSalary": 140000
    },
    {
        "title": "Critical Care Nurse",
        "careerType": "critical-care-nurse",
        "description": "Provide intensive care for critically ill patients, monitor life support systems, emergency response.",
        "salaryRange": "$80,000 - $110,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Critical Care", "Life Support Systems", "Emergency Response", "Advanced Monitoring"],
        "requiredSoftSkills": ["Stress Management", "Quick Decision Making", "Attention to Detail", "Teamwork"],
        "companies": ["Hospitals", "ICUs", "Emergency Departments", "Trauma Centers"],
        "learningPath": "RN + Critical Care Certification (3-5 years)",
        "relevanceScore": 82,
        "confidenceLevel": 85,
        "matchReasons": ["High-intensity care", "Emergency response", "Advanced technical skills"],
        "minExperienceYears": 2,
        "maxExperienceYears": 30,
        "minSalary": 80000,
        "maxSalary": 110000
    },

    # ALLIED HEALTH PROFESSIONALS
    {
        "title": "Physical Therapist",
        "careerType": "physical-therapist",
        "description": "Help patients recover mobility and manage pain through therapeutic exercises and treatments.",
        "salaryRange": "$85,000 - $105,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Physical Therapy", "Rehabilitation", "Exercise Physiology", "Patient Assessment"],
        "requiredSoftSkills": ["Patience", "Motivation", "Communication", "Problem Solving"],
        "companies": ["Hospitals", "Rehabilitation Centers", "Sports Medicine", "Private Practice"],
        "learningPath": "Doctor of Physical Therapy (6-7 years)",
        "relevanceScore": 80,
        "confidenceLevel": 82,
        "matchReasons": ["Rehabilitation focus", "Hands-on therapy", "Patient recovery"],
        "minExperienceYears": 0,
        "maxExperienceYears": 35,
        "minSalary": 85000,
        "maxSalary": 105000
    },
    {
        "title": "Occupational Therapist",
        "careerType": "occupational-therapist",
        "description": "Help patients develop or recover skills needed for daily living and working activities.",
        "salaryRange": "$80,000 - $100,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Occupational Therapy", "Activity Analysis", "Adaptive Equipment", "Patient Assessment"],
        "requiredSoftSkills": ["Creativity", "Problem Solving", "Patience", "Communication"],
        "companies": ["Hospitals", "Rehabilitation Centers", "Schools", "Home Health"],
        "learningPath": "Master's in Occupational Therapy (5-6 years)",
        "relevanceScore": 78,
        "confidenceLevel": 80,
        "matchReasons": ["Functional improvement", "Creative problem solving", "Patient independence"],
        "minExperienceYears": 0,
        "maxExperienceYears": 35,
        "minSalary": 80000,
        "maxSalary": 100000
    },
    {
        "title": "Radiologic Technologist",
        "careerType": "radiologic-technologist",
        "description": "Perform diagnostic imaging procedures, operate imaging equipment, ensure patient safety during scans.",
        "salaryRange": "$55,000 - $75,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Medical Imaging", "Radiology Equipment", "Patient Positioning", "Radiation Safety"],
        "requiredSoftSkills": ["Attention to Detail", "Technical Aptitude", "Patient Care", "Communication"],
        "companies": ["Hospitals", "Imaging Centers", "Clinics", "Outpatient Centers"],
        "learningPath": "Associate Degree in Radiologic Technology (2-3 years)",
        "relevanceScore": 75,
        "confidenceLevel": 78,
        "matchReasons": ["Medical technology", "Diagnostic imaging", "Technical precision"],
        "minExperienceYears": 0,
        "maxExperienceYears": 30,
        "minSalary": 55000,
        "maxSalary": 75000
    },

    # MENTAL HEALTH PROFESSIONALS
    {
        "title": "Clinical Psychologist",
        "careerType": "clinical-psychologist",
        "description": "Diagnose and treat mental health disorders, provide therapy, conduct psychological assessments.",
        "salaryRange": "$90,000 - $130,000",
        "experienceLevel": "senior",
        "requiredTechnicalSkills": ["Psychology", "Therapy Techniques", "Psychological Assessment", "Mental Health Diagnosis"],
        "requiredSoftSkills": ["Empathy", "Active Listening", "Communication", "Emotional Intelligence"],
        "companies": ["Private Practice", "Hospitals", "Mental Health Centers", "Universities"],
        "learningPath": "Doctoral Degree in Psychology + Internship (8-10 years)",
        "relevanceScore": 85,
        "confidenceLevel": 88,
        "matchReasons": ["Mental health focus", "Therapeutic relationship", "Psychological understanding"],
        "minExperienceYears": 6,
        "maxExperienceYears": 40,
        "minSalary": 90000,
        "maxSalary": 130000
    },
    {
        "title": "Licensed Clinical Social Worker",
        "careerType": "clinical-social-worker",
        "description": "Provide mental health counseling, case management, connect clients with community resources.",
        "salaryRange": "$60,000 - $85,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Clinical Social Work", "Counseling", "Case Management", "Crisis Intervention"],
        "requiredSoftSkills": ["Empathy", "Communication", "Cultural Sensitivity", "Problem Solving"],
        "companies": ["Hospitals", "Mental Health Centers", "Private Practice", "Community Organizations"],
        "learningPath": "Master's in Social Work + Clinical License (4-6 years)",
        "relevanceScore": 80,
        "confidenceLevel": 82,
        "matchReasons": ["Social services", "Mental health support", "Community focus"],
        "minExperienceYears": 2,
        "maxExperienceYears": 35,
        "minSalary": 60000,
        "maxSalary": 85000
    },

    # MEDICAL SUPPORT & ADMINISTRATION
    {
        "title": "Medical Assistant",
        "careerType": "medical-assistant",
        "description": "Support healthcare providers with clinical and administrative tasks, patient care assistance.",
        "salaryRange": "$35,000 - $45,000",
        "experienceLevel": "junior",
        "requiredTechnicalSkills": ["Medical Procedures", "Medical Records", "Patient Care", "Medical Equipment"],
        "requiredSoftSkills": ["Organization", "Communication", "Attention to Detail", "Multitasking"],
        "companies": ["Clinics", "Hospitals", "Private Practice", "Specialty Centers"],
        "learningPath": "Medical Assistant Certificate (6 months - 2 years)",
        "relevanceScore": 70,
        "confidenceLevel": 75,
        "matchReasons": ["Healthcare support", "Patient interaction", "Medical environment"],
        "minExperienceYears": 0,
        "maxExperienceYears": 20,
        "minSalary": 35000,
        "maxSalary": 45000
    },
    {
        "title": "Healthcare Administrator",
        "careerType": "healthcare-administrator",
        "description": "Manage healthcare facilities, oversee operations, ensure regulatory compliance, manage budgets.",
        "salaryRange": "$95,000 - $140,000",
        "experienceLevel": "senior",
        "requiredTechnicalSkills": ["Healthcare Management", "Regulatory Compliance", "Budget Management", "Operations"],
        "requiredSoftSkills": ["Leadership", "Communication", "Problem Solving", "Strategic Thinking"],
        "companies": ["Hospitals", "Healthcare Systems", "Clinics", "Long-term Care Facilities"],
        "learningPath": "Bachelor's/Master's in Healthcare Administration (4-6 years)",
        "relevanceScore": 78,
        "confidenceLevel": 80,
        "matchReasons": ["Healthcare management", "Operations focus", "Leadership role"],
        "minExperienceYears": 5,
        "maxExperienceYears": 35,
        "minSalary": 95000,
        "maxSalary": 140000
    },
    {
        "title": "Medical Records Technician",
        "careerType": "medical-records-technician",
        "description": "Organize and manage health information data, ensure accuracy and accessibility of medical records.",
        "salaryRange": "$40,000 - $55,000",
        "experienceLevel": "junior",
        "requiredTechnicalSkills": ["Medical Records", "Health Information Systems", "Medical Coding", "Data Management"],
        "requiredSoftSkills": ["Attention to Detail", "Organization", "Confidentiality", "Computer Skills"],
        "companies": ["Hospitals", "Clinics", "Insurance Companies", "Government Agencies"],
        "learningPath": "Certificate in Health Information Technology (1-2 years)",
        "relevanceScore": 68,
        "confidenceLevel": 70,
        "matchReasons": ["Data management", "Healthcare support", "Detail-oriented work"],
        "minExperienceYears": 0,
        "maxExperienceYears": 25,
        "minSalary": 40000,
        "maxSalary": 55000
    }
]