"""
Healthcare & Medical Career Database
Part of comprehensive career database expansion - Phase 1A
"""

HEALTHCARE_CAREERS = [
    # MEDICAL DOCTORS & SPECIALISTS
    {
        "title": "Family Medicine Physician",
        "careerType": "family-medicine-physician",
        "description": "Provide comprehensive primary care for patients of all ages, manage chronic conditions, preventive care.",
        "salaryRange": "$200,000 - $280,000",
        "experienceLevel": "senior",
        "requiredTechnicalSkills": ["Medical Diagnosis", "Patient Care", "Medical Records", "Clinical Decision Making"],
        "requiredSoftSkills": ["Empathy", "Communication", "Critical Thinking", "Attention to Detail"],
        "companies": ["Hospitals", "Private Practice", "Healthcare Systems", "Community Health Centers"],
        "learningPath": "Medical School + Family Medicine Residency (7-8 years)",
        "relevanceScore": 85,
        "confidenceLevel": 90,
        "matchReasons": ["Healthcare interest", "Science background", "People-focused"],
        "minExperienceYears": 8,
        "maxExperienceYears": 40,
        "minSalary": 200000,
        "maxSalary": 280000
    },
    {
        "title": "Cardiologist",
        "careerType": "cardiologist",
        "description": "Diagnose and treat heart and cardiovascular diseases, perform cardiac procedures, manage complex cases.",
        "salaryRange": "$350,000 - $500,000",
        "experienceLevel": "executive",
        "requiredTechnicalSkills": ["Cardiology", "Cardiac Procedures", "Diagnostic Imaging", "Critical Care"],
        "requiredSoftSkills": ["Precision", "Communication", "Decision Making", "Stress Management"],
        "companies": ["Hospitals", "Cardiac Centers", "Private Practice", "Academic Medical Centers"],
        "learningPath": "Medical School + Internal Medicine + Cardiology Fellowship (10+ years)",
        "relevanceScore": 85,
        "confidenceLevel": 90,
        "matchReasons": ["Advanced medical training", "Specialized expertise", "High-stakes decision making"],
        "minExperienceYears": 10,
        "maxExperienceYears": 40,
        "minSalary": 350000,
        "maxSalary": 500000
    },
    {
        "title": "Pediatrician",
        "careerType": "pediatrician",
        "description": "Provide medical care for infants, children, and adolescents, manage developmental health.",
        "salaryRange": "$180,000 - $250,000",
        "experienceLevel": "senior",
        "requiredTechnicalSkills": ["Pediatric Medicine", "Child Development", "Immunizations", "Family Counseling"],
        "requiredSoftSkills": ["Patience", "Communication", "Empathy", "Child Interaction"],
        "companies": ["Pediatric Clinics", "Hospitals", "Private Practice", "Children's Hospitals"],
        "learningPath": "Medical School + Pediatrics Residency (7-8 years)",
        "relevanceScore": 85,
        "confidenceLevel": 90,
        "matchReasons": ["Child-focused care", "Preventive medicine", "Family interaction"],
        "minExperienceYears": 8,
        "maxExperienceYears": 40,
        "minSalary": 180000,
        "maxSalary": 250000
    },
    {
        "title": "Surgeon (General)",
        "careerType": "general-surgeon",
        "description": "Perform surgical procedures, manage pre/post-operative care, handle emergency surgeries.",
        "salaryRange": "$300,000 - $450,000",
        "experienceLevel": "executive",
        "requiredTechnicalSkills": ["Surgical Procedures", "Anatomy", "Emergency Medicine", "Surgical Technology"],
        "requiredSoftSkills": ["Precision", "Decision Making", "Stress Management", "Leadership"],
        "companies": ["Hospitals", "Surgical Centers", "Trauma Centers", "Private Practice"],
        "learningPath": "Medical School + General Surgery Residency (9+ years)",
        "relevanceScore": 85,
        "confidenceLevel": 90,
        "matchReasons": ["Surgical skills", "High-pressure performance", "Technical precision"],
        "minExperienceYears": 9,
        "maxExperienceYears": 40,
        "minSalary": 300000,
        "maxSalary": 450000
    },
    {
        "title": "Orthopedic Surgeon",
        "careerType": "orthopedic-surgeon",
        "description": "Specialize in surgical treatment of musculoskeletal system, bones, joints, ligaments, and tendons.",
        "salaryRange": "$400,000 - $600,000",
        "experienceLevel": "executive",
        "requiredTechnicalSkills": ["Orthopedic Surgery", "Musculoskeletal Anatomy", "Surgical Instruments", "Sports Medicine"],
        "requiredSoftSkills": ["Precision", "Physical Stamina", "Problem Solving", "Communication"],
        "companies": ["Hospitals", "Orthopedic Centers", "Sports Medicine Clinics", "Private Practice"],
        "learningPath": "Medical School + Orthopedic Surgery Residency (10+ years)",
        "relevanceScore": 88,
        "confidenceLevel": 92,
        "matchReasons": ["Surgical expertise", "Sports medicine interest", "High earning potential"],
        "minExperienceYears": 10,
        "maxExperienceYears": 40,
        "minSalary": 400000,
        "maxSalary": 600000
    },
    {
        "title": "Neurologist",
        "careerType": "neurologist",
        "description": "Diagnose and treat disorders of the nervous system, brain, spinal cord, and peripheral nerves.",
        "salaryRange": "$280,000 - $400,000",
        "experienceLevel": "executive",
        "requiredTechnicalSkills": ["Neurology", "Neurological Testing", "Brain Imaging", "Neurological Disorders"],
        "requiredSoftSkills": ["Analytical Thinking", "Patience", "Communication", "Attention to Detail"],
        "companies": ["Hospitals", "Neurology Centers", "Academic Medical Centers", "Private Practice"],
        "learningPath": "Medical School + Neurology Residency (8+ years)",
        "relevanceScore": 87,
        "confidenceLevel": 90,
        "matchReasons": ["Complex problem solving", "Neurological expertise", "Research opportunities"],
        "minExperienceYears": 8,
        "maxExperienceYears": 40,
        "minSalary": 280000,
        "maxSalary": 400000
    },
    {
        "title": "Emergency Medicine Physician",
        "careerType": "emergency-medicine-physician",
        "description": "Provide immediate medical care in emergency situations, manage trauma cases, critical decision making.",
        "salaryRange": "$280,000 - $380,000",
        "experienceLevel": "senior",
        "requiredTechnicalSkills": ["Emergency Medicine", "Trauma Care", "Critical Care", "Rapid Assessment"],
        "requiredSoftSkills": ["Quick Decision Making", "Stress Management", "Leadership", "Communication"],
        "companies": ["Hospitals", "Emergency Departments", "Trauma Centers", "Urgent Care"],
        "learningPath": "Medical School + Emergency Medicine Residency (7-8 years)",
        "relevanceScore": 86,
        "confidenceLevel": 88,
        "matchReasons": ["High-pressure environment", "Immediate impact", "Diverse medical cases"],
        "minExperienceYears": 7,
        "maxExperienceYears": 40,
        "minSalary": 280000,
        "maxSalary": 380000
    },
    {
        "title": "Dermatologist",
        "careerType": "dermatologist",
        "description": "Diagnose and treat skin, hair, and nail conditions, perform cosmetic procedures, skin cancer screening.",
        "salaryRange": "$350,000 - $500,000",
        "experienceLevel": "executive",
        "requiredTechnicalSkills": ["Dermatology", "Skin Pathology", "Cosmetic Procedures", "Dermatologic Surgery"],
        "requiredSoftSkills": ["Attention to Detail", "Aesthetic Sense", "Communication", "Patience"],
        "companies": ["Dermatology Clinics", "Hospitals", "Cosmetic Centers", "Private Practice"],
        "learningPath": "Medical School + Dermatology Residency (8+ years)",
        "relevanceScore": 84,
        "confidenceLevel": 87,
        "matchReasons": ["Aesthetic medicine", "Preventive care", "Work-life balance"],
        "minExperienceYears": 8,
        "maxExperienceYears": 40,
        "minSalary": 350000,
        "maxSalary": 500000
    },
    {
        "title": "Anesthesiologist",
        "careerType": "anesthesiologist",
        "description": "Administer anesthesia during surgeries, monitor patients during procedures, manage pain control.",
        "salaryRange": "$350,000 - $480,000",
        "experienceLevel": "executive",
        "requiredTechnicalSkills": ["Anesthesiology", "Patient Monitoring", "Pain Management", "Pharmacology"],
        "requiredSoftSkills": ["Attention to Detail", "Calm Under Pressure", "Communication", "Technical Precision"],
        "companies": ["Hospitals", "Surgical Centers", "Pain Management Clinics", "Academic Medical Centers"],
        "learningPath": "Medical School + Anesthesiology Residency (8+ years)",
        "relevanceScore": 85,
        "confidenceLevel": 89,
        "matchReasons": ["Technical expertise", "Critical patient care", "High compensation"],
        "minExperienceYears": 8,
        "maxExperienceYears": 40,
        "minSalary": 350000,
        "maxSalary": 480000
    },

    # NURSING PROFESSIONALS
    {
        "title": "Registered Nurse (RN)",
        "careerType": "registered-nurse",
        "description": "Provide patient care, administer medications, monitor patient conditions, educate patients and families.",
        "salaryRange": "$70,000 - $95,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Patient Care", "Medical Equipment", "Medication Administration", "Health Assessment"],
        "requiredSoftSkills": ["Compassion", "Communication", "Attention to Detail", "Stress Management"],
        "companies": ["Hospitals", "Clinics", "Nursing Homes", "Home Healthcare"],
        "learningPath": "Nursing Degree + RN License (2-4 years)",
        "relevanceScore": 80,
        "confidenceLevel": 85,
        "matchReasons": ["Patient care focus", "Healthcare interest", "Helping others"],
        "minExperienceYears": 0,
        "maxExperienceYears": 40,
        "minSalary": 70000,
        "maxSalary": 95000
    },
    {
        "title": "Nurse Practitioner",
        "careerType": "nurse-practitioner",
        "description": "Provide advanced nursing care, diagnose conditions, prescribe medications, manage patient care.",
        "salaryRange": "$110,000 - $140,000",
        "experienceLevel": "senior",
        "requiredTechnicalSkills": ["Advanced Practice Nursing", "Diagnosis", "Prescriptive Authority", "Patient Management"],
        "requiredSoftSkills": ["Clinical Judgment", "Communication", "Leadership", "Patient Advocacy"],
        "companies": ["Hospitals", "Clinics", "Private Practice", "Specialty Centers"],
        "learningPath": "RN + Master's in Nursing + Certification (6-8 years)",
        "relevanceScore": 85,
        "confidenceLevel": 88,
        "matchReasons": ["Advanced nursing practice", "Independent practice", "Patient care leadership"],
        "minExperienceYears": 4,
        "maxExperienceYears": 40,
        "minSalary": 110000,
        "maxSalary": 140000
    },
    {
        "title": "Critical Care Nurse",
        "careerType": "critical-care-nurse",
        "description": "Provide intensive care for critically ill patients, monitor life support systems, emergency response.",
        "salaryRange": "$80,000 - $110,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Critical Care", "Life Support Systems", "Emergency Response", "Advanced Monitoring"],
        "requiredSoftSkills": ["Stress Management", "Quick Decision Making", "Attention to Detail", "Teamwork"],
        "companies": ["Hospitals", "ICUs", "Emergency Departments", "Trauma Centers"],
        "learningPath": "RN + Critical Care Certification (3-5 years)",
        "relevanceScore": 82,
        "confidenceLevel": 85,
        "matchReasons": ["High-intensity care", "Emergency response", "Advanced technical skills"],
        "minExperienceYears": 2,
        "maxExperienceYears": 30,
        "minSalary": 80000,
        "maxSalary": 110000
    },
    {
        "title": "Pediatric Nurse",
        "careerType": "pediatric-nurse",
        "description": "Specialize in nursing care for infants, children, and adolescents, family-centered care approach.",
        "salaryRange": "$75,000 - $100,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Pediatric Nursing", "Child Development", "Family Education", "Pediatric Medications"],
        "requiredSoftSkills": ["Patience", "Child Communication", "Empathy", "Family Support"],
        "companies": ["Children's Hospitals", "Pediatric Clinics", "Schools", "Specialty Centers"],
        "learningPath": "RN + Pediatric Nursing Certification (3-4 years)",
        "relevanceScore": 83,
        "confidenceLevel": 86,
        "matchReasons": ["Child-focused care", "Family interaction", "Specialized nursing"],
        "minExperienceYears": 1,
        "maxExperienceYears": 35,
        "minSalary": 75000,
        "maxSalary": 100000
    },
    {
        "title": "Operating Room Nurse",
        "careerType": "operating-room-nurse",
        "description": "Assist in surgical procedures, maintain sterile environment, manage surgical instruments and supplies.",
        "salaryRange": "$78,000 - $105,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Surgical Procedures", "Sterile Technique", "Surgical Instruments", "Patient Positioning"],
        "requiredSoftSkills": ["Attention to Detail", "Teamwork", "Stress Management", "Communication"],
        "companies": ["Hospitals", "Surgical Centers", "Outpatient Surgery", "Specialty Clinics"],
        "learningPath": "RN + Operating Room Training (2-3 years)",
        "relevanceScore": 81,
        "confidenceLevel": 84,
        "matchReasons": ["Surgical environment", "Technical precision", "Team collaboration"],
        "minExperienceYears": 1,
        "maxExperienceYears": 35,
        "minSalary": 78000,
        "maxSalary": 105000
    },
    {
        "title": "Nurse Anesthetist (CRNA)",
        "careerType": "nurse-anesthetist",
        "description": "Administer anesthesia, monitor patients during procedures, manage anesthesia equipment and medications.",
        "salaryRange": "$170,000 - $220,000",
        "experienceLevel": "executive",
        "requiredTechnicalSkills": ["Anesthesia Administration", "Patient Monitoring", "Pharmacology", "Airway Management"],
        "requiredSoftSkills": ["Critical Thinking", "Attention to Detail", "Communication", "Stress Management"],
        "companies": ["Hospitals", "Surgical Centers", "Pain Management Clinics", "Dental Offices"],
        "learningPath": "RN + Master's in Nurse Anesthesia (7-8 years)",
        "relevanceScore": 88,
        "confidenceLevel": 91,
        "matchReasons": ["Advanced practice", "High compensation", "Critical patient care"],
        "minExperienceYears": 5,
        "maxExperienceYears": 40,
        "minSalary": 170000,
        "maxSalary": 220000
    },

    # ALLIED HEALTH PROFESSIONALS
    {
        "title": "Physical Therapist",
        "careerType": "physical-therapist",
        "description": "Help patients recover mobility and manage pain through therapeutic exercises and treatments.",
        "salaryRange": "$85,000 - $105,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Physical Therapy", "Rehabilitation", "Exercise Physiology", "Patient Assessment"],
        "requiredSoftSkills": ["Patience", "Motivation", "Communication", "Problem Solving"],
        "companies": ["Hospitals", "Rehabilitation Centers", "Sports Medicine", "Private Practice"],
        "learningPath": "Doctor of Physical Therapy (6-7 years)",
        "relevanceScore": 80,
        "confidenceLevel": 82,
        "matchReasons": ["Rehabilitation focus", "Hands-on therapy", "Patient recovery"],
        "minExperienceYears": 0,
        "maxExperienceYears": 35,
        "minSalary": 85000,
        "maxSalary": 105000
    },
    {
        "title": "Occupational Therapist",
        "careerType": "occupational-therapist",
        "description": "Help patients develop or recover skills needed for daily living and working activities.",
        "salaryRange": "$80,000 - $100,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Occupational Therapy", "Activity Analysis", "Adaptive Equipment", "Patient Assessment"],
        "requiredSoftSkills": ["Creativity", "Problem Solving", "Patience", "Communication"],
        "companies": ["Hospitals", "Rehabilitation Centers", "Schools", "Home Health"],
        "learningPath": "Master's in Occupational Therapy (5-6 years)",
        "relevanceScore": 78,
        "confidenceLevel": 80,
        "matchReasons": ["Functional improvement", "Creative problem solving", "Patient independence"],
        "minExperienceYears": 0,
        "maxExperienceYears": 35,
        "minSalary": 80000,
        "maxSalary": 100000
    },
    {
        "title": "Radiologic Technologist",
        "careerType": "radiologic-technologist",
        "description": "Perform diagnostic imaging procedures, operate imaging equipment, ensure patient safety during scans.",
        "salaryRange": "$55,000 - $75,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Medical Imaging", "Radiology Equipment", "Patient Positioning", "Radiation Safety"],
        "requiredSoftSkills": ["Attention to Detail", "Technical Aptitude", "Patient Care", "Communication"],
        "companies": ["Hospitals", "Imaging Centers", "Clinics", "Outpatient Centers"],
        "learningPath": "Associate Degree in Radiologic Technology (2-3 years)",
        "relevanceScore": 75,
        "confidenceLevel": 78,
        "matchReasons": ["Medical technology", "Diagnostic imaging", "Technical precision"],
        "minExperienceYears": 0,
        "maxExperienceYears": 30,
        "minSalary": 55000,
        "maxSalary": 75000
    },
    {
        "title": "Speech-Language Pathologist",
        "careerType": "speech-language-pathologist",
        "description": "Assess and treat speech, language, voice, and swallowing disorders in patients of all ages.",
        "salaryRange": "$75,000 - $95,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Speech Therapy", "Language Assessment", "Swallowing Disorders", "Communication Devices"],
        "requiredSoftSkills": ["Patience", "Communication", "Creativity", "Problem Solving"],
        "companies": ["Hospitals", "Schools", "Rehabilitation Centers", "Private Practice"],
        "learningPath": "Master's in Speech-Language Pathology (6 years)",
        "relevanceScore": 79,
        "confidenceLevel": 82,
        "matchReasons": ["Communication focus", "Patient rehabilitation", "Diverse patient population"],
        "minExperienceYears": 0,
        "maxExperienceYears": 35,
        "minSalary": 75000,
        "maxSalary": 95000
    },
    {
        "title": "Respiratory Therapist",
        "careerType": "respiratory-therapist",
        "description": "Treat patients with breathing disorders, operate ventilators, provide pulmonary rehabilitation.",
        "salaryRange": "$60,000 - $80,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Respiratory Care", "Ventilator Management", "Pulmonary Function Testing", "Oxygen Therapy"],
        "requiredSoftSkills": ["Attention to Detail", "Communication", "Compassion", "Technical Aptitude"],
        "companies": ["Hospitals", "Long-term Care", "Home Healthcare", "Sleep Centers"],
        "learningPath": "Associate Degree in Respiratory Therapy (2-3 years)",
        "relevanceScore": 77,
        "confidenceLevel": 80,
        "matchReasons": ["Respiratory care", "Critical patient support", "Technical skills"],
        "minExperienceYears": 0,
        "maxExperienceYears": 35,
        "minSalary": 60000,
        "maxSalary": 80000
    },
    {
        "title": "Pharmacy Technician",
        "careerType": "pharmacy-technician",
        "description": "Assist pharmacists in dispensing medications, manage inventory, process prescriptions.",
        "salaryRange": "$35,000 - $50,000",
        "experienceLevel": "junior",
        "requiredTechnicalSkills": ["Pharmacy Operations", "Medication Dispensing", "Inventory Management", "Prescription Processing"],
        "requiredSoftSkills": ["Attention to Detail", "Customer Service", "Organization", "Communication"],
        "companies": ["Retail Pharmacies", "Hospitals", "Mail-order Pharmacies", "Long-term Care"],
        "learningPath": "Pharmacy Technician Certificate (6 months - 2 years)",
        "relevanceScore": 72,
        "confidenceLevel": 75,
        "matchReasons": ["Healthcare support", "Medication expertise", "Customer interaction"],
        "minExperienceYears": 0,
        "maxExperienceYears": 25,
        "minSalary": 35000,
        "maxSalary": 50000
    },
    {
        "title": "Medical Laboratory Technologist",
        "careerType": "medical-laboratory-technologist",
        "description": "Perform complex laboratory tests, analyze specimens, operate sophisticated laboratory equipment.",
        "salaryRange": "$55,000 - $75,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Laboratory Testing", "Microscopy", "Laboratory Equipment", "Quality Control"],
        "requiredSoftSkills": ["Attention to Detail", "Analytical Thinking", "Problem Solving", "Technical Aptitude"],
        "companies": ["Hospitals", "Reference Laboratories", "Clinics", "Research Facilities"],
        "learningPath": "Bachelor's in Medical Laboratory Science (4 years)",
        "relevanceScore": 76,
        "confidenceLevel": 79,
        "matchReasons": ["Laboratory science", "Diagnostic testing", "Technical precision"],
        "minExperienceYears": 0,
        "maxExperienceYears": 35,
        "minSalary": 55000,
        "maxSalary": 75000
    },
    {
        "title": "Ultrasound Technologist",
        "careerType": "ultrasound-technologist",
        "description": "Perform ultrasound examinations, operate sonographic equipment, assist in diagnostic procedures.",
        "salaryRange": "$70,000 - $90,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Ultrasound Technology", "Sonographic Equipment", "Anatomy Knowledge", "Image Analysis"],
        "requiredSoftSkills": ["Patient Care", "Attention to Detail", "Communication", "Technical Skills"],
        "companies": ["Hospitals", "Imaging Centers", "Obstetric Clinics", "Cardiology Centers"],
        "learningPath": "Associate Degree in Diagnostic Medical Sonography (2-4 years)",
        "relevanceScore": 78,
        "confidenceLevel": 81,
        "matchReasons": ["Medical imaging", "Patient interaction", "Technical expertise"],
        "minExperienceYears": 0,
        "maxExperienceYears": 30,
        "minSalary": 70000,
        "maxSalary": 90000
    },
    {
        "title": "Dietitian/Nutritionist",
        "careerType": "dietitian-nutritionist",
        "description": "Provide nutrition counseling, develop meal plans, educate patients about healthy eating habits.",
        "salaryRange": "$55,000 - $75,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Nutrition Science", "Meal Planning", "Dietary Assessment", "Medical Nutrition Therapy"],
        "requiredSoftSkills": ["Communication", "Empathy", "Teaching", "Problem Solving"],
        "companies": ["Hospitals", "Clinics", "Schools", "Sports Teams"],
        "learningPath": "Bachelor's in Nutrition + Dietetic Internship (4-5 years)",
        "relevanceScore": 74,
        "confidenceLevel": 77,
        "matchReasons": ["Nutrition focus", "Patient education", "Preventive health"],
        "minExperienceYears": 0,
        "maxExperienceYears": 35,
        "minSalary": 55000,
        "maxSalary": 75000
    },

    # MENTAL HEALTH PROFESSIONALS
    {
        "title": "Clinical Psychologist",
        "careerType": "clinical-psychologist",
        "description": "Diagnose and treat mental health disorders, provide therapy, conduct psychological assessments.",
        "salaryRange": "$90,000 - $130,000",
        "experienceLevel": "senior",
        "requiredTechnicalSkills": ["Psychology", "Therapy Techniques", "Psychological Assessment", "Mental Health Diagnosis"],
        "requiredSoftSkills": ["Empathy", "Active Listening", "Communication", "Emotional Intelligence"],
        "companies": ["Private Practice", "Hospitals", "Mental Health Centers", "Universities"],
        "learningPath": "Doctoral Degree in Psychology + Internship (8-10 years)",
        "relevanceScore": 85,
        "confidenceLevel": 88,
        "matchReasons": ["Mental health focus", "Therapeutic relationship", "Psychological understanding"],
        "minExperienceYears": 6,
        "maxExperienceYears": 40,
        "minSalary": 90000,
        "maxSalary": 130000
    },
    {
        "title": "Licensed Clinical Social Worker",
        "careerType": "clinical-social-worker",
        "description": "Provide mental health counseling, case management, connect clients with community resources.",
        "salaryRange": "$60,000 - $85,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Clinical Social Work", "Counseling", "Case Management", "Crisis Intervention"],
        "requiredSoftSkills": ["Empathy", "Communication", "Cultural Sensitivity", "Problem Solving"],
        "companies": ["Hospitals", "Mental Health Centers", "Private Practice", "Community Organizations"],
        "learningPath": "Master's in Social Work + Clinical License (4-6 years)",
        "relevanceScore": 80,
        "confidenceLevel": 82,
        "matchReasons": ["Social services", "Mental health support", "Community focus"],
        "minExperienceYears": 2,
        "maxExperienceYears": 35,
        "minSalary": 60000,
        "maxSalary": 85000
    },
    {
        "title": "Psychiatrist",
        "careerType": "psychiatrist",
        "description": "Diagnose and treat mental health disorders, prescribe psychiatric medications, provide therapy.",
        "salaryRange": "$220,000 - $320,000",
        "experienceLevel": "executive",
        "requiredTechnicalSkills": ["Psychiatry", "Psychopharmacology", "Mental Health Diagnosis", "Therapy Techniques"],
        "requiredSoftSkills": ["Empathy", "Communication", "Analytical Thinking", "Patience"],
        "companies": ["Hospitals", "Mental Health Centers", "Private Practice", "Academic Medical Centers"],
        "learningPath": "Medical School + Psychiatry Residency (8+ years)",
        "relevanceScore": 87,
        "confidenceLevel": 90,
        "matchReasons": ["Mental health medicine", "Medication management", "Complex cases"],
        "minExperienceYears": 8,
        "maxExperienceYears": 40,
        "minSalary": 220000,
        "maxSalary": 320000
    },
    {
        "title": "Marriage and Family Therapist",
        "careerType": "marriage-family-therapist",
        "description": "Provide counseling for couples and families, address relationship issues, family dynamics.",
        "salaryRange": "$55,000 - $80,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Family Therapy", "Couples Counseling", "Relationship Dynamics", "Conflict Resolution"],
        "requiredSoftSkills": ["Empathy", "Communication", "Neutrality", "Problem Solving"],
        "companies": ["Private Practice", "Family Service Centers", "Mental Health Clinics", "Community Centers"],
        "learningPath": "Master's in Marriage & Family Therapy + License (4-6 years)",
        "relevanceScore": 78,
        "confidenceLevel": 81,
        "matchReasons": ["Relationship focus", "Family systems", "Counseling skills"],
        "minExperienceYears": 2,
        "maxExperienceYears": 35,
        "minSalary": 55000,
        "maxSalary": 80000
    },
    {
        "title": "Substance Abuse Counselor",
        "careerType": "substance-abuse-counselor",
        "description": "Provide counseling and support for individuals with addiction, develop treatment plans, group therapy.",
        "salaryRange": "$45,000 - $65,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Addiction Counseling", "Group Therapy", "Treatment Planning", "Crisis Intervention"],
        "requiredSoftSkills": ["Empathy", "Non-judgmental", "Communication", "Patience"],
        "companies": ["Rehabilitation Centers", "Hospitals", "Outpatient Clinics", "Community Centers"],
        "learningPath": "Bachelor's/Master's in Addiction Counseling + License (4-6 years)",
        "relevanceScore": 76,
        "confidenceLevel": 79,
        "matchReasons": ["Addiction recovery", "Helping others", "Mental health support"],
        "minExperienceYears": 2,
        "maxExperienceYears": 35,
        "minSalary": 45000,
        "maxSalary": 65000
    },

    # MEDICAL SUPPORT & ADMINISTRATION
    {
        "title": "Medical Assistant",
        "careerType": "medical-assistant",
        "description": "Support healthcare providers with clinical and administrative tasks, patient care assistance.",
        "salaryRange": "$35,000 - $45,000",
        "experienceLevel": "junior",
        "requiredTechnicalSkills": ["Medical Procedures", "Medical Records", "Patient Care", "Medical Equipment"],
        "requiredSoftSkills": ["Organization", "Communication", "Attention to Detail", "Multitasking"],
        "companies": ["Clinics", "Hospitals", "Private Practice", "Specialty Centers"],
        "learningPath": "Medical Assistant Certificate (6 months - 2 years)",
        "relevanceScore": 70,
        "confidenceLevel": 75,
        "matchReasons": ["Healthcare support", "Patient interaction", "Medical environment"],
        "minExperienceYears": 0,
        "maxExperienceYears": 20,
        "minSalary": 35000,
        "maxSalary": 45000
    },
    {
        "title": "Healthcare Administrator",
        "careerType": "healthcare-administrator",
        "description": "Manage healthcare facilities, oversee operations, ensure regulatory compliance, manage budgets.",
        "salaryRange": "$95,000 - $140,000",
        "experienceLevel": "senior",
        "requiredTechnicalSkills": ["Healthcare Management", "Regulatory Compliance", "Budget Management", "Operations"],
        "requiredSoftSkills": ["Leadership", "Communication", "Problem Solving", "Strategic Thinking"],
        "companies": ["Hospitals", "Healthcare Systems", "Clinics", "Long-term Care Facilities"],
        "learningPath": "Bachelor's/Master's in Healthcare Administration (4-6 years)",
        "relevanceScore": 78,
        "confidenceLevel": 80,
        "matchReasons": ["Healthcare management", "Operations focus", "Leadership role"],
        "minExperienceYears": 5,
        "maxExperienceYears": 35,
        "minSalary": 95000,
        "maxSalary": 140000
    },
    {
        "title": "Medical Records Technician",
        "careerType": "medical-records-technician",
        "description": "Organize and manage health information data, ensure accuracy and accessibility of medical records.",
        "salaryRange": "$40,000 - $55,000",
        "experienceLevel": "junior",
        "requiredTechnicalSkills": ["Medical Records", "Health Information Systems", "Medical Coding", "Data Management"],
        "requiredSoftSkills": ["Attention to Detail", "Organization", "Confidentiality", "Computer Skills"],
        "companies": ["Hospitals", "Clinics", "Insurance Companies", "Government Agencies"],
        "learningPath": "Certificate in Health Information Technology (1-2 years)",
        "relevanceScore": 68,
        "confidenceLevel": 70,
        "matchReasons": ["Data management", "Healthcare support", "Detail-oriented work"],
        "minExperienceYears": 0,
        "maxExperienceYears": 25,
        "minSalary": 40000,
        "maxSalary": 55000
    },
    {
        "title": "Medical Billing Specialist",
        "careerType": "medical-billing-specialist",
        "description": "Process medical claims, handle insurance billing, manage patient accounts and payment processing.",
        "salaryRange": "$38,000 - $52,000",
        "experienceLevel": "junior",
        "requiredTechnicalSkills": ["Medical Billing", "Insurance Claims", "Medical Coding", "Healthcare Software"],
        "requiredSoftSkills": ["Attention to Detail", "Organization", "Communication", "Problem Solving"],
        "companies": ["Hospitals", "Clinics", "Billing Companies", "Insurance Companies"],
        "learningPath": "Medical Billing Certificate (6 months - 2 years)",
        "relevanceScore": 69,
        "confidenceLevel": 72,
        "matchReasons": ["Healthcare administration", "Detail-oriented work", "Insurance knowledge"],
        "minExperienceYears": 0,
        "maxExperienceYears": 25,
        "minSalary": 38000,
        "maxSalary": 52000
    },
    {
        "title": "Health Information Manager",
        "careerType": "health-information-manager",
        "description": "Oversee health information systems, ensure data quality, manage electronic health records.",
        "salaryRange": "$75,000 - $100,000",
        "experienceLevel": "senior",
        "requiredTechnicalSkills": ["Health Information Systems", "Data Management", "Electronic Health Records", "Healthcare Analytics"],
        "requiredSoftSkills": ["Leadership", "Problem Solving", "Communication", "Project Management"],
        "companies": ["Hospitals", "Healthcare Systems", "Government Agencies", "Consulting Firms"],
        "learningPath": "Bachelor's in Health Information Management (4 years)",
        "relevanceScore": 77,
        "confidenceLevel": 80,
        "matchReasons": ["Healthcare technology", "Data management", "System oversight"],
        "minExperienceYears": 3,
        "maxExperienceYears": 30,
        "minSalary": 75000,
        "maxSalary": 100000
    },
    {
        "title": "Patient Care Coordinator",
        "careerType": "patient-care-coordinator",
        "description": "Coordinate patient care services, schedule appointments, facilitate communication between providers.",
        "salaryRange": "$42,000 - $58,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Care Coordination", "Healthcare Systems", "Patient Scheduling", "Medical Terminology"],
        "requiredSoftSkills": ["Communication", "Organization", "Empathy", "Problem Solving"],
        "companies": ["Hospitals", "Clinics", "Healthcare Networks", "Specialty Centers"],
        "learningPath": "Associate Degree in Healthcare + Certification (2-3 years)",
        "relevanceScore": 73,
        "confidenceLevel": 76,
        "matchReasons": ["Patient advocacy", "Healthcare coordination", "Communication focus"],
        "minExperienceYears": 1,
        "maxExperienceYears": 25,
        "minSalary": 42000,
        "maxSalary": 58000
    },
    {
        "title": "Medical Equipment Technician",
        "careerType": "medical-equipment-technician",
        "description": "Install, maintain, and repair medical equipment, ensure proper functioning of healthcare technology.",
        "salaryRange": "$50,000 - $70,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Medical Equipment", "Electronics", "Troubleshooting", "Equipment Maintenance"],
        "requiredSoftSkills": ["Technical Aptitude", "Problem Solving", "Attention to Detail", "Communication"],
        "companies": ["Hospitals", "Medical Equipment Companies", "Service Contractors", "Healthcare Systems"],
        "learningPath": "Associate Degree in Biomedical Technology (2-3 years)",
        "relevanceScore": 74,
        "confidenceLevel": 77,
        "matchReasons": ["Technical skills", "Healthcare technology", "Equipment expertise"],
        "minExperienceYears": 0,
        "maxExperienceYears": 30,
        "minSalary": 50000,
        "maxSalary": 70000
    },
    {
        "title": "Hospital Social Worker",
        "careerType": "hospital-social-worker",
        "description": "Provide psychosocial support to patients and families, discharge planning, resource coordination.",
        "salaryRange": "$55,000 - $75,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Medical Social Work", "Discharge Planning", "Crisis Intervention", "Resource Coordination"],
        "requiredSoftSkills": ["Empathy", "Communication", "Cultural Sensitivity", "Problem Solving"],
        "companies": ["Hospitals", "Medical Centers", "Rehabilitation Facilities", "Long-term Care"],
        "learningPath": "Master's in Social Work + Healthcare Experience (4-6 years)",
        "relevanceScore": 79,
        "confidenceLevel": 82,
        "matchReasons": ["Patient support", "Healthcare social services", "Family advocacy"],
        "minExperienceYears": 2,
        "maxExperienceYears": 35,
        "minSalary": 55000,
        "maxSalary": 75000
    },
    {
        "title": "Pharmacist",
        "careerType": "pharmacist",
        "description": "Dispense medications, provide drug information, counsel patients on medication use and interactions.",
        "salaryRange": "$120,000 - $160,000",
        "experienceLevel": "senior",
        "requiredTechnicalSkills": ["Pharmacology", "Drug Interactions", "Medication Dispensing", "Patient Counseling"],
        "requiredSoftSkills": ["Attention to Detail", "Communication", "Problem Solving", "Customer Service"],
        "companies": ["Retail Pharmacies", "Hospitals", "Clinical Settings", "Long-term Care"],
        "learningPath": "Doctor of Pharmacy (6-8 years)",
        "relevanceScore": 83,
        "confidenceLevel": 86,
        "matchReasons": ["Medication expertise", "Patient counseling", "Healthcare knowledge"],
        "minExperienceYears": 0,
        "maxExperienceYears": 40,
        "minSalary": 120000,
        "maxSalary": 160000
    },
    {
        "title": "Biomedical Engineer",
        "careerType": "biomedical-engineer",
        "description": "Design and develop medical devices, analyze biological systems, improve healthcare technology.",
        "salaryRange": "$75,000 - $110,000",
        "experienceLevel": "senior",
        "requiredTechnicalSkills": ["Biomedical Engineering", "Medical Device Design", "Systems Analysis", "Technical Documentation"],
        "requiredSoftSkills": ["Problem Solving", "Innovation", "Communication", "Project Management"],
        "companies": ["Medical Device Companies", "Hospitals", "Research Institutions", "Consulting Firms"],
        "learningPath": "Bachelor's in Biomedical Engineering (4 years)",
        "relevanceScore": 81,
        "confidenceLevel": 84,
        "matchReasons": ["Engineering skills", "Healthcare technology", "Innovation focus"],
        "minExperienceYears": 0,
        "maxExperienceYears": 35,
        "minSalary": 75000,
        "maxSalary": 110000
    },
    {
        "title": "Clinical Research Coordinator",
        "careerType": "clinical-research-coordinator",
        "description": "Coordinate clinical trials, manage patient recruitment, ensure regulatory compliance, collect research data.",
        "salaryRange": "$50,000 - $70,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Clinical Research", "Regulatory Compliance", "Data Collection", "Patient Recruitment"],
        "requiredSoftSkills": ["Organization", "Attention to Detail", "Communication", "Problem Solving"],
        "companies": ["Research Institutions", "Hospitals", "Pharmaceutical Companies", "CROs"],
        "learningPath": "Bachelor's in Life Sciences + Clinical Research Training (4-5 years)",
        "relevanceScore": 75,
        "confidenceLevel": 78,
        "matchReasons": ["Research focus", "Healthcare environment", "Data management"],
        "minExperienceYears": 1,
        "maxExperienceYears": 25,
        "minSalary": 50000,
        "maxSalary": 70000
    }
]