"""
Hospitality & Service careers database with comprehensive career options.
Covers restaurants, hotels, tourism, customer service, and service industries.
"""

HOSPITALITY_SERVICE_CAREERS = [
    # EXECUTIVE LEVEL (15+ years, $150k+)
    {
        "title": "Hotel General Manager",
        "careerType": "hotel-general-manager",
        "description": "Oversee all hotel operations, manage staff, ensure guest satisfaction, drive revenue and profitability.",
        "salaryRange": "$150,000 - $250,000",
        "experienceLevel": "executive",
        "requiredTechnicalSkills": ["Hotel Management", "Revenue Management", "Staff Leadership", "Budget Management", "Property Management Systems"],
        "requiredSoftSkills": ["Leadership", "Customer Service", "Communication", "Problem Solving", "Strategic Planning"],
        "companies": ["Marriott", "Hilton", "Hyatt", "Four Seasons", "Ritz-Carlton", "Westin"],
        "learningPath": "Hotel Management Executive Program (6-12 months)",
        "relevanceScore": 85,
        "confidenceLevel": 82,
        "matchReasons": ["Hospitality leadership", "Operations management", "Customer service focus"],
        "minExperienceYears": 15,
        "maxExperienceYears": 30,
        "minSalary": 150000,
        "maxSalary": 250000
    },
    {
        "title": "Restaurant Chain Director",
        "careerType": "restaurant-chain-director",
        "description": "Manage multiple restaurant locations, develop operational standards, drive brand consistency and growth.",
        "salaryRange": "$140,000 - $220,000",
        "experienceLevel": "executive",
        "requiredTechnicalSkills": ["Multi-Unit Management", "Restaurant Operations", "Brand Management", "Supply Chain", "Financial Analysis"],
        "requiredSoftSkills": ["Leadership", "Strategic Thinking", "Communication", "Problem Solving", "Team Building"],
        "companies": ["McDonald's", "Starbucks", "Chipotle", "Subway", "Domino's", "KFC"],
        "learningPath": "Restaurant Management Leadership (6-8 months)",
        "relevanceScore": 82,
        "confidenceLevel": 80,
        "matchReasons": ["Multi-unit operations", "Brand management", "Service leadership"],
        "minExperienceYears": 12,
        "maxExperienceYears": 25,
        "minSalary": 140000,
        "maxSalary": 220000
    },
    {
        "title": "Tourism Director",
        "careerType": "tourism-director",
        "description": "Lead tourism development initiatives, manage destination marketing, coordinate with stakeholders.",
        "salaryRange": "$120,000 - $180,000",
        "experienceLevel": "executive",
        "requiredTechnicalSkills": ["Tourism Development", "Destination Marketing", "Event Management", "Stakeholder Relations", "Economic Development"],
        "requiredSoftSkills": ["Leadership", "Communication", "Strategic Planning", "Relationship Building", "Cultural Awareness"],
        "companies": ["Visit California", "NYC Tourism", "Disney", "Universal Studios", "Carnival Cruise", "Royal Caribbean"],
        "learningPath": "Tourism Management Executive Program (4-6 months)",
        "relevanceScore": 78,
        "confidenceLevel": 75,
        "matchReasons": ["Tourism industry knowledge", "Marketing experience", "Public relations"],
        "minExperienceYears": 10,
        "maxExperienceYears": 20,
        "minSalary": 120000,
        "maxSalary": 180000
    },

    # SENIOR LEVEL (8-15 years, $80k-150k)
    {
        "title": "Food & Beverage Manager",
        "careerType": "food-beverage-manager",
        "description": "Oversee restaurant and bar operations, manage staff, ensure quality standards and profitability.",
        "salaryRange": "$85,000 - $130,000",
        "experienceLevel": "senior",
        "requiredTechnicalSkills": ["Restaurant Management", "Food Safety", "Inventory Management", "Cost Control", "Staff Training"],
        "requiredSoftSkills": ["Leadership", "Customer Service", "Communication", "Problem Solving", "Attention to Detail"],
        "companies": ["Marriott", "Hilton", "Hyatt", "Four Seasons", "Ritz-Carlton", "Local Restaurants"],
        "learningPath": "Food & Beverage Management Certification (4-6 months)",
        "relevanceScore": 88,
        "confidenceLevel": 85,
        "matchReasons": ["Restaurant operations", "Team management", "Customer service"],
        "minExperienceYears": 8,
        "maxExperienceYears": 15,
        "minSalary": 85000,
        "maxSalary": 130000
    },
    {
        "title": "Event Manager",
        "careerType": "event-manager",
        "description": "Plan and execute events, coordinate vendors, manage budgets, ensure successful event delivery.",
        "salaryRange": "$75,000 - $120,000",
        "experienceLevel": "senior",
        "requiredTechnicalSkills": ["Event Planning", "Vendor Management", "Budget Management", "Project Management", "Marketing"],
        "requiredSoftSkills": ["Organization", "Communication", "Problem Solving", "Creativity", "Attention to Detail"],
        "companies": ["Marriott", "Hilton", "Event Companies", "Corporate Events", "Wedding Planners", "Convention Centers"],
        "learningPath": "Event Management Certification (3-4 months)",
        "relevanceScore": 85,
        "confidenceLevel": 82,
        "matchReasons": ["Project management", "Organization skills", "Client relations"],
        "minExperienceYears": 6,
        "maxExperienceYears": 12,
        "minSalary": 75000,
        "maxSalary": 120000
    },
    {
        "title": "Guest Services Manager",
        "careerType": "guest-services-manager",
        "description": "Lead guest services team, handle escalations, ensure exceptional customer experience.",
        "salaryRange": "$70,000 - $110,000",
        "experienceLevel": "senior",
        "requiredTechnicalSkills": ["Customer Service", "Conflict Resolution", "Staff Management", "Hotel Systems", "Quality Assurance"],
        "requiredSoftSkills": ["Leadership", "Communication", "Empathy", "Problem Solving", "Patience"],
        "companies": ["Marriott", "Hilton", "Hyatt", "Four Seasons", "Ritz-Carlton", "Boutique Hotels"],
        "learningPath": "Guest Services Leadership Program (3-4 months)",
        "relevanceScore": 90,
        "confidenceLevel": 88,
        "matchReasons": ["Customer service excellence", "Team leadership", "Problem resolution"],
        "minExperienceYears": 6,
        "maxExperienceYears": 12,
        "minSalary": 70000,
        "maxSalary": 110000
    },
    {
        "title": "Catering Manager",
        "careerType": "catering-manager",
        "description": "Manage catering operations, coordinate events, oversee food preparation and service delivery.",
        "salaryRange": "$65,000 - $100,000",
        "experienceLevel": "senior",
        "requiredTechnicalSkills": ["Catering Operations", "Food Safety", "Event Coordination", "Menu Planning", "Cost Control"],
        "requiredSoftSkills": ["Organization", "Communication", "Leadership", "Customer Service", "Attention to Detail"],
        "companies": ["Aramark", "Sodexo", "Compass Group", "Local Caterers", "Hotels", "Event Venues"],
        "learningPath": "Catering Management Program (3-4 months)",
        "relevanceScore": 82,
        "confidenceLevel": 80,
        "matchReasons": ["Food service management", "Event coordination", "Operations"],
        "minExperienceYears": 5,
        "maxExperienceYears": 10,
        "minSalary": 65000,
        "maxSalary": 100000
    },

    # MID LEVEL (4-8 years, $50k-85k)
    {
        "title": "Restaurant Manager",
        "careerType": "restaurant-manager",
        "description": "Manage daily restaurant operations, supervise staff, ensure customer satisfaction and profitability.",
        "salaryRange": "$55,000 - $85,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Restaurant Operations", "Staff Management", "Inventory Control", "Food Safety", "POS Systems"],
        "requiredSoftSkills": ["Leadership", "Customer Service", "Communication", "Problem Solving", "Multitasking"],
        "companies": ["Olive Garden", "Applebee's", "TGI Friday's", "Local Restaurants", "Fast Casual Chains", "Fine Dining"],
        "learningPath": "Restaurant Management Certification (3-4 months)",
        "relevanceScore": 85,
        "confidenceLevel": 82,
        "matchReasons": ["Operations management", "Team leadership", "Customer focus"],
        "minExperienceYears": 4,
        "maxExperienceYears": 8,
        "minSalary": 55000,
        "maxSalary": 85000
    },
    {
        "title": "Front Desk Manager",
        "careerType": "front-desk-manager",
        "description": "Oversee front desk operations, manage reservations, ensure smooth guest check-in/check-out processes.",
        "salaryRange": "$50,000 - $75,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Hotel Management Systems", "Reservation Management", "Customer Service", "Staff Training", "Revenue Management"],
        "requiredSoftSkills": ["Leadership", "Communication", "Problem Solving", "Organization", "Patience"],
        "companies": ["Marriott", "Hilton", "Hyatt", "Holiday Inn", "Best Western", "Independent Hotels"],
        "learningPath": "Front Office Management Program (2-3 months)",
        "relevanceScore": 88,
        "confidenceLevel": 85,
        "matchReasons": ["Customer service leadership", "Operations management", "Team coordination"],
        "minExperienceYears": 4,
        "maxExperienceYears": 8,
        "minSalary": 50000,
        "maxSalary": 75000
    },
    {
        "title": "Cruise Ship Officer",
        "careerType": "cruise-ship-officer",
        "description": "Manage cruise ship operations, ensure passenger safety and satisfaction, coordinate activities.",
        "salaryRange": "$60,000 - $90,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Maritime Operations", "Safety Protocols", "Guest Services", "International Regulations", "Emergency Procedures"],
        "requiredSoftSkills": ["Leadership", "Cultural Awareness", "Communication", "Problem Solving", "Adaptability"],
        "companies": ["Royal Caribbean", "Carnival", "Norwegian Cruise Line", "Princess Cruises", "Celebrity Cruises", "Disney Cruise Line"],
        "learningPath": "Maritime Hospitality Program (4-6 months)",
        "relevanceScore": 75,
        "confidenceLevel": 72,
        "matchReasons": ["International experience", "Operations management", "Customer service"],
        "minExperienceYears": 3,
        "maxExperienceYears": 8,
        "minSalary": 60000,
        "maxSalary": 90000
    },
    {
        "title": "Banquet Manager",
        "careerType": "banquet-manager",
        "description": "Coordinate banquet events, manage service staff, ensure successful event execution.",
        "salaryRange": "$48,000 - $72,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Banquet Operations", "Event Coordination", "Staff Management", "Menu Planning", "Setup Coordination"],
        "requiredSoftSkills": ["Organization", "Communication", "Leadership", "Attention to Detail", "Customer Service"],
        "companies": ["Hotels", "Event Venues", "Country Clubs", "Convention Centers", "Catering Companies", "Restaurants"],
        "learningPath": "Banquet Management Certification (2-3 months)",
        "relevanceScore": 80,
        "confidenceLevel": 78,
        "matchReasons": ["Event management", "Team coordination", "Service excellence"],
        "minExperienceYears": 3,
        "maxExperienceYears": 7,
        "minSalary": 48000,
        "maxSalary": 72000
    },

    # JUNIOR LEVEL (0-4 years, $30k-55k)
    {
        "title": "Hotel Front Desk Agent",
        "careerType": "hotel-front-desk-agent",
        "description": "Handle guest check-in/check-out, manage reservations, provide customer service and information.",
        "salaryRange": "$35,000 - $50,000",
        "experienceLevel": "junior",
        "requiredTechnicalSkills": ["Hotel Management Systems", "Customer Service", "Reservation Systems", "Cash Handling", "Basic Computer Skills"],
        "requiredSoftSkills": ["Communication", "Patience", "Problem Solving", "Attention to Detail", "Multitasking"],
        "companies": ["Marriott", "Hilton", "Hyatt", "Holiday Inn", "Best Western", "Independent Hotels"],
        "learningPath": "Hotel Front Desk Training (1-2 months)",
        "relevanceScore": 85,
        "confidenceLevel": 82,
        "matchReasons": ["Customer service skills", "Communication abilities", "Detail-oriented"],
        "minExperienceYears": 0,
        "maxExperienceYears": 3,
        "minSalary": 35000,
        "maxSalary": 50000
    },
    {
        "title": "Server/Waitstaff",
        "careerType": "server-waitstaff",
        "description": "Take orders, serve food and beverages, provide excellent customer service in restaurant settings.",
        "salaryRange": "$30,000 - $45,000",
        "experienceLevel": "junior",
        "requiredTechnicalSkills": ["POS Systems", "Food Service", "Menu Knowledge", "Cash Handling", "Order Management"],
        "requiredSoftSkills": ["Customer Service", "Communication", "Multitasking", "Patience", "Teamwork"],
        "companies": ["Restaurants", "Hotels", "Cafes", "Bars", "Catering Companies", "Event Venues"],
        "learningPath": "Food Service Training (1-2 months)",
        "relevanceScore": 80,
        "confidenceLevel": 78,
        "matchReasons": ["Customer interaction", "Service orientation", "Communication skills"],
        "minExperienceYears": 0,
        "maxExperienceYears": 3,
        "minSalary": 30000,
        "maxSalary": 45000
    },
    {
        "title": "Tour Guide",
        "careerType": "tour-guide",
        "description": "Lead tours, provide information about attractions, ensure visitor safety and satisfaction.",
        "salaryRange": "$32,000 - $48,000",
        "experienceLevel": "junior",
        "requiredTechnicalSkills": ["Tourism Knowledge", "Public Speaking", "Safety Protocols", "Group Management", "Cultural Knowledge"],
        "requiredSoftSkills": ["Communication", "Enthusiasm", "Cultural Awareness", "Patience", "Storytelling"],
        "companies": ["Tourism Companies", "Museums", "National Parks", "City Tours", "Adventure Companies", "Cruise Lines"],
        "learningPath": "Tour Guide Certification (1-2 months)",
        "relevanceScore": 75,
        "confidenceLevel": 72,
        "matchReasons": ["Public speaking", "Cultural interest", "People skills"],
        "minExperienceYears": 0,
        "maxExperienceYears": 3,
        "minSalary": 32000,
        "maxSalary": 48000
    },
    {
        "title": "Concierge",
        "careerType": "concierge",
        "description": "Assist guests with reservations, recommendations, and special requests to enhance their experience.",
        "salaryRange": "$38,000 - $55,000",
        "experienceLevel": "junior",
        "requiredTechnicalSkills": ["Local Knowledge", "Reservation Systems", "Customer Service", "Communication", "Problem Solving"],
        "requiredSoftSkills": ["Helpfulness", "Communication", "Cultural Awareness", "Patience", "Resourcefulness"],
        "companies": ["Luxury Hotels", "Resorts", "Apartment Buildings", "Corporate Buildings", "Cruise Ships", "Airports"],
        "learningPath": "Concierge Services Training (1-2 months)",
        "relevanceScore": 82,
        "confidenceLevel": 80,
        "matchReasons": ["Customer service excellence", "Problem solving", "Local knowledge"],
        "minExperienceYears": 0,
        "maxExperienceYears": 4,
        "minSalary": 38000,
        "maxSalary": 55000
    },
    {
        "title": "Bartender",
        "careerType": "bartender",
        "description": "Prepare and serve alcoholic and non-alcoholic beverages, provide customer service in bar settings.",
        "salaryRange": "$35,000 - $50,000",
        "experienceLevel": "junior",
        "requiredTechnicalSkills": ["Mixology", "POS Systems", "Inventory Management", "Cash Handling", "Alcohol Service Laws"],
        "requiredSoftSkills": ["Customer Service", "Communication", "Multitasking", "Creativity", "Patience"],
        "companies": ["Restaurants", "Hotels", "Bars", "Nightclubs", "Event Venues", "Cruise Ships"],
        "learningPath": "Bartending Certification (1-2 months)",
        "relevanceScore": 78,
        "confidenceLevel": 75,
        "matchReasons": ["Customer interaction", "Creativity", "Service skills"],
        "minExperienceYears": 0,
        "maxExperienceYears": 3,
        "minSalary": 35000,
        "maxSalary": 50000
    },
    {
        "title": "Customer Service Representative",
        "careerType": "customer-service-representative",
        "description": "Handle customer inquiries, resolve complaints, provide information and support via phone, email, or chat.",
        "salaryRange": "$32,000 - $45,000",
        "experienceLevel": "junior",
        "requiredTechnicalSkills": ["Customer Service Software", "Communication Systems", "Data Entry", "Problem Resolution", "Product Knowledge"],
        "requiredSoftSkills": ["Communication", "Patience", "Empathy", "Problem Solving", "Active Listening"],
        "companies": ["Call Centers", "Hotels", "Airlines", "Retail Companies", "Tech Companies", "Service Providers"],
        "learningPath": "Customer Service Excellence (1-2 months)",
        "relevanceScore": 88,
        "confidenceLevel": 85,
        "matchReasons": ["Communication skills", "Problem solving", "Customer focus"],
        "minExperienceYears": 0,
        "maxExperienceYears": 3,
        "minSalary": 32000,
        "maxSalary": 45000
    },
    {
        "title": "Housekeeper/Room Attendant",
        "careerType": "housekeeper-room-attendant",
        "description": "Clean and maintain guest rooms, ensure cleanliness standards, restock amenities.",
        "salaryRange": "$28,000 - $40,000",
        "experienceLevel": "junior",
        "requiredTechnicalSkills": ["Cleaning Procedures", "Time Management", "Attention to Detail", "Safety Protocols", "Equipment Operation"],
        "requiredSoftSkills": ["Reliability", "Attention to Detail", "Physical Stamina", "Time Management", "Teamwork"],
        "companies": ["Hotels", "Resorts", "Hospitals", "Cruise Ships", "Cleaning Services", "Residential Buildings"],
        "learningPath": "Housekeeping Training Program (1 month)",
        "relevanceScore": 70,
        "confidenceLevel": 68,
        "matchReasons": ["Attention to detail", "Reliability", "Service orientation"],
        "minExperienceYears": 0,
        "maxExperienceYears": 2,
        "minSalary": 28000,
        "maxSalary": 40000
    },

    # SPECIALIZED HOSPITALITY ROLES
    {
        "title": "Sommelier",
        "careerType": "sommelier",
        "description": "Wine expert who curates wine lists, provides wine recommendations, and enhances dining experiences.",
        "salaryRange": "$55,000 - $85,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Wine Knowledge", "Food Pairing", "Wine Service", "Inventory Management", "Tasting Skills"],
        "requiredSoftSkills": ["Communication", "Attention to Detail", "Customer Service", "Passion for Wine", "Cultural Awareness"],
        "companies": ["Fine Dining Restaurants", "Hotels", "Wine Bars", "Cruise Ships", "Wine Retailers", "Event Venues"],
        "learningPath": "Sommelier Certification (6-12 months)",
        "relevanceScore": 75,
        "confidenceLevel": 72,
        "matchReasons": ["Specialized expertise", "Customer service", "Attention to detail"],
        "minExperienceYears": 3,
        "maxExperienceYears": 10,
        "minSalary": 55000,
        "maxSalary": 85000
    },
    {
        "title": "Wedding Planner",
        "careerType": "wedding-planner",
        "description": "Plan and coordinate weddings, manage vendors, ensure perfect execution of special events.",
        "salaryRange": "$45,000 - $75,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Event Planning", "Vendor Management", "Budget Management", "Timeline Coordination", "Design Coordination"],
        "requiredSoftSkills": ["Organization", "Communication", "Creativity", "Attention to Detail", "Stress Management"],
        "companies": ["Wedding Planning Companies", "Event Venues", "Hotels", "Independent Planners", "Catering Companies", "Florists"],
        "learningPath": "Wedding Planning Certification (3-4 months)",
        "relevanceScore": 80,
        "confidenceLevel": 78,
        "matchReasons": ["Event coordination", "Attention to detail", "Client relations"],
        "minExperienceYears": 2,
        "maxExperienceYears": 8,
        "minSalary": 45000,
        "maxSalary": 75000
    },
    {
        "title": "Spa Manager",
        "careerType": "spa-manager",
        "description": "Manage spa operations, oversee treatments, ensure relaxing customer experience and staff coordination.",
        "salaryRange": "$50,000 - $80,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Spa Operations", "Treatment Knowledge", "Staff Management", "Inventory Control", "Health Regulations"],
        "requiredSoftSkills": ["Leadership", "Customer Service", "Wellness Focus", "Communication", "Attention to Detail"],
        "companies": ["Resort Spas", "Day Spas", "Hotels", "Cruise Ships", "Wellness Centers", "Medical Spas"],
        "learningPath": "Spa Management Certification (3-4 months)",
        "relevanceScore": 78,
        "confidenceLevel": 75,
        "matchReasons": ["Wellness focus", "Operations management", "Customer service"],
        "minExperienceYears": 3,
        "maxExperienceYears": 8,
        "minSalary": 50000,
        "maxSalary": 80000
    }
]