"""
Manufacturing & Industrial careers database with comprehensive career options.
Covers manufacturing, production, quality control, industrial engineering, and operations.
"""

MANUFACTURING_INDUSTRIAL_CAREERS = [
    # EXECUTIVE LEVEL (15+ years, $150k+)
    {
        "title": "Manufacturing Director",
        "careerType": "manufacturing-director",
        "description": "Lead manufacturing operations across multiple facilities, drive operational excellence, manage large teams.",
        "salaryRange": "$180,000 - $280,000",
        "experienceLevel": "executive",
        "requiredTechnicalSkills": ["Manufacturing Operations", "Lean Manufacturing", "Six Sigma", "Supply Chain Management", "Budget Management"],
        "requiredSoftSkills": ["Executive Leadership", "Strategic Planning", "Communication", "Problem Solving", "Change Management"],
        "companies": ["General Motors", "Ford", "Boeing", "Caterpillar", "3M", "General Electric"],
        "learningPath": "Manufacturing Leadership Program (6-12 months)",
        "relevanceScore": 85,
        "confidenceLevel": 82,
        "matchReasons": ["Operations leadership", "Manufacturing expertise", "Strategic planning"],
        "minExperienceYears": 15,
        "maxExperienceYears": 30,
        "minSalary": 180000,
        "maxSalary": 280000
    },
    {
        "title": "Plant Manager",
        "careerType": "plant-manager",
        "description": "Oversee entire manufacturing plant operations, ensure safety, quality, and productivity targets.",
        "salaryRange": "$150,000 - $250,000",
        "experienceLevel": "executive",
        "requiredTechnicalSkills": ["Plant Operations", "Production Management", "Safety Management", "Quality Control", "Team Leadership"],
        "requiredSoftSkills": ["Leadership", "Communication", "Problem Solving", "Decision Making", "Safety Focus"],
        "companies": ["Toyota", "Honda", "General Motors", "Ford", "Boeing", "Caterpillar"],
        "learningPath": "Plant Management Executive Program (6-8 months)",
        "relevanceScore": 88,
        "confidenceLevel": 85,
        "matchReasons": ["Plant operations", "Team leadership", "Production management"],
        "minExperienceYears": 12,
        "maxExperienceYears": 25,
        "minSalary": 150000,
        "maxSalary": 250000
    },
    {
        "title": "Operations Director",
        "careerType": "operations-director",
        "description": "Direct operational strategy, optimize processes, drive continuous improvement across manufacturing operations.",
        "salaryRange": "$160,000 - $240,000",
        "experienceLevel": "executive",
        "requiredTechnicalSkills": ["Operations Management", "Process Optimization", "Lean Six Sigma", "Strategic Planning", "Performance Management"],
        "requiredSoftSkills": ["Strategic Leadership", "Communication", "Change Management", "Problem Solving", "Team Building"],
        "companies": ["Intel", "AMD", "Texas Instruments", "Honeywell", "Emerson", "Rockwell Automation"],
        "learningPath": "Operations Leadership Program (6-8 months)",
        "relevanceScore": 82,
        "confidenceLevel": 80,
        "matchReasons": ["Operations strategy", "Process improvement", "Leadership"],
        "minExperienceYears": 12,
        "maxExperienceYears": 22,
        "minSalary": 160000,
        "maxSalary": 240000
    },

    # SENIOR LEVEL (8-15 years, $80k-150k)
    {
        "title": "Production Manager",
        "careerType": "production-manager",
        "description": "Manage production schedules, oversee manufacturing processes, ensure quality and efficiency targets.",
        "salaryRange": "$85,000 - $130,000",
        "experienceLevel": "senior",
        "requiredTechnicalSkills": ["Production Planning", "Manufacturing Processes", "Quality Control", "Team Management", "Lean Manufacturing"],
        "requiredSoftSkills": ["Leadership", "Problem Solving", "Communication", "Organization", "Attention to Detail"],
        "companies": ["General Motors", "Ford", "Toyota", "Honda", "Boeing", "Caterpillar"],
        "learningPath": "Production Management Certification (4-6 months)",
        "relevanceScore": 90,
        "confidenceLevel": 88,
        "matchReasons": ["Production expertise", "Team management", "Process optimization"],
        "minExperienceYears": 8,
        "maxExperienceYears": 15,
        "minSalary": 85000,
        "maxSalary": 130000
    },
    {
        "title": "Quality Assurance Manager",
        "careerType": "quality-assurance-manager",
        "description": "Lead quality control programs, implement quality systems, ensure compliance with standards.",
        "salaryRange": "$80,000 - $120,000",
        "experienceLevel": "senior",
        "requiredTechnicalSkills": ["Quality Management Systems", "Statistical Process Control", "ISO Standards", "Auditing", "Root Cause Analysis"],
        "requiredSoftSkills": ["Attention to Detail", "Leadership", "Communication", "Problem Solving", "Analytical Thinking"],
        "companies": ["3M", "Johnson & Johnson", "Pfizer", "Boeing", "General Electric", "Honeywell"],
        "learningPath": "Quality Management Certification (4-6 months)",
        "relevanceScore": 88,
        "confidenceLevel": 85,
        "matchReasons": ["Quality focus", "Process improvement", "Standards compliance"],
        "minExperienceYears": 6,
        "maxExperienceYears": 12,
        "minSalary": 80000,
        "maxSalary": 120000
    },
    {
        "title": "Industrial Engineer",
        "careerType": "industrial-engineer",
        "description": "Optimize manufacturing processes, improve efficiency, design production systems and workflows.",
        "salaryRange": "$75,000 - $115,000",
        "experienceLevel": "senior",
        "requiredTechnicalSkills": ["Process Engineering", "Lean Manufacturing", "Six Sigma", "Statistical Analysis", "CAD Software"],
        "requiredSoftSkills": ["Analytical Thinking", "Problem Solving", "Communication", "Project Management", "Attention to Detail"],
        "companies": ["General Electric", "Boeing", "Ford", "Toyota", "Intel", "Honeywell"],
        "learningPath": "Industrial Engineering Program (4-6 months)",
        "relevanceScore": 85,
        "confidenceLevel": 82,
        "matchReasons": ["Process optimization", "Engineering mindset", "Efficiency focus"],
        "minExperienceYears": 5,
        "maxExperienceYears": 12,
        "minSalary": 75000,
        "maxSalary": 115000
    },
    {
        "title": "Supply Chain Manager",
        "careerType": "supply-chain-manager",
        "description": "Manage supply chain operations, coordinate with suppliers, optimize inventory and logistics.",
        "salaryRange": "$85,000 - $125,000",
        "experienceLevel": "senior",
        "requiredTechnicalSkills": ["Supply Chain Management", "Inventory Management", "Logistics", "Procurement", "ERP Systems"],
        "requiredSoftSkills": ["Strategic Thinking", "Communication", "Negotiation", "Problem Solving", "Relationship Building"],
        "companies": ["Amazon", "Walmart", "General Motors", "Ford", "Boeing", "Caterpillar"],
        "learningPath": "Supply Chain Management Certification (4-6 months)",
        "relevanceScore": 82,
        "confidenceLevel": 80,
        "matchReasons": ["Supply chain expertise", "Strategic planning", "Operations management"],
        "minExperienceYears": 6,
        "maxExperienceYears": 12,
        "minSalary": 85000,
        "maxSalary": 125000
    },

    # MID LEVEL (4-8 years, $50k-85k)
    {
        "title": "Manufacturing Engineer",
        "careerType": "manufacturing-engineer",
        "description": "Design and improve manufacturing processes, implement automation, ensure production efficiency.",
        "salaryRange": "$70,000 - $100,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Manufacturing Processes", "Process Improvement", "Automation", "CAD Software", "Statistical Analysis"],
        "requiredSoftSkills": ["Problem Solving", "Analytical Thinking", "Communication", "Project Management", "Attention to Detail"],
        "companies": ["General Motors", "Ford", "Boeing", "Intel", "3M", "Caterpillar"],
        "learningPath": "Manufacturing Engineering Program (3-4 months)",
        "relevanceScore": 88,
        "confidenceLevel": 85,
        "matchReasons": ["Engineering background", "Process improvement", "Technical skills"],
        "minExperienceYears": 4,
        "maxExperienceYears": 8,
        "minSalary": 70000,
        "maxSalary": 100000
    },
    {
        "title": "Process Engineer",
        "careerType": "process-engineer",
        "description": "Develop and optimize manufacturing processes, troubleshoot production issues, implement improvements.",
        "salaryRange": "$68,000 - $95,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Process Engineering", "Statistical Process Control", "Lean Manufacturing", "Problem Solving", "Data Analysis"],
        "requiredSoftSkills": ["Analytical Thinking", "Communication", "Problem Solving", "Attention to Detail", "Teamwork"],
        "companies": ["Intel", "AMD", "Texas Instruments", "3M", "DuPont", "Dow Chemical"],
        "learningPath": "Process Engineering Certification (3-4 months)",
        "relevanceScore": 85,
        "confidenceLevel": 82,
        "matchReasons": ["Process optimization", "Engineering skills", "Data analysis"],
        "minExperienceYears": 3,
        "maxExperienceYears": 8,
        "minSalary": 68000,
        "maxSalary": 95000
    },
    {
        "title": "Quality Control Specialist",
        "careerType": "quality-control-specialist",
        "description": "Inspect products and processes, conduct quality tests, ensure compliance with quality standards.",
        "salaryRange": "$55,000 - $80,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Quality Control", "Statistical Analysis", "Testing Procedures", "Measurement Tools", "Documentation"],
        "requiredSoftSkills": ["Attention to Detail", "Analytical Thinking", "Communication", "Problem Solving", "Reliability"],
        "companies": ["3M", "Johnson & Johnson", "Pfizer", "Boeing", "General Electric", "Ford"],
        "learningPath": "Quality Control Certification (2-3 months)",
        "relevanceScore": 82,
        "confidenceLevel": 80,
        "matchReasons": ["Quality focus", "Attention to detail", "Analytical skills"],
        "minExperienceYears": 3,
        "maxExperienceYears": 7,
        "minSalary": 55000,
        "maxSalary": 80000
    },
    {
        "title": "Production Supervisor",
        "careerType": "production-supervisor",
        "description": "Supervise production workers, ensure safety protocols, monitor production schedules and quality.",
        "salaryRange": "$60,000 - $85,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Production Management", "Safety Protocols", "Team Leadership", "Quality Control", "Scheduling"],
        "requiredSoftSkills": ["Leadership", "Communication", "Problem Solving", "Decision Making", "Safety Focus"],
        "companies": ["General Motors", "Ford", "Toyota", "Honda", "Boeing", "Caterpillar"],
        "learningPath": "Production Supervision Program (2-3 months)",
        "relevanceScore": 85,
        "confidenceLevel": 82,
        "matchReasons": ["Team leadership", "Production experience", "Safety focus"],
        "minExperienceYears": 4,
        "maxExperienceYears": 8,
        "minSalary": 60000,
        "maxSalary": 85000
    },
    {
        "title": "Maintenance Manager",
        "careerType": "maintenance-manager",
        "description": "Manage equipment maintenance, plan preventive maintenance, ensure minimal downtime.",
        "salaryRange": "$70,000 - $100,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Maintenance Management", "Equipment Troubleshooting", "Preventive Maintenance", "CMMS Systems", "Safety Protocols"],
        "requiredSoftSkills": ["Leadership", "Problem Solving", "Organization", "Communication", "Planning"],
        "companies": ["General Electric", "Honeywell", "Emerson", "Rockwell Automation", "Siemens", "ABB"],
        "learningPath": "Maintenance Management Certification (3-4 months)",
        "relevanceScore": 80,
        "confidenceLevel": 78,
        "matchReasons": ["Equipment management", "Problem solving", "Technical skills"],
        "minExperienceYears": 5,
        "maxExperienceYears": 10,
        "minSalary": 70000,
        "maxSalary": 100000
    },

    # JUNIOR LEVEL (0-4 years, $35k-60k)
    {
        "title": "Production Worker",
        "careerType": "production-worker",
        "description": "Operate manufacturing equipment, assemble products, follow safety and quality procedures.",
        "salaryRange": "$35,000 - $50,000",
        "experienceLevel": "junior",
        "requiredTechnicalSkills": ["Equipment Operation", "Safety Procedures", "Quality Standards", "Basic Math", "Following Instructions"],
        "requiredSoftSkills": ["Reliability", "Attention to Detail", "Teamwork", "Physical Stamina", "Safety Consciousness"],
        "companies": ["General Motors", "Ford", "Toyota", "Honda", "Boeing", "Local Manufacturers"],
        "learningPath": "Manufacturing Operations Training (1-2 months)",
        "relevanceScore": 75,
        "confidenceLevel": 72,
        "matchReasons": ["Entry-level manufacturing", "Hands-on work", "Team environment"],
        "minExperienceYears": 0,
        "maxExperienceYears": 3,
        "minSalary": 35000,
        "maxSalary": 50000
    },
    {
        "title": "Quality Inspector",
        "careerType": "quality-inspector",
        "description": "Inspect products for defects, conduct quality tests, document findings and ensure standards compliance.",
        "salaryRange": "$40,000 - $60,000",
        "experienceLevel": "junior",
        "requiredTechnicalSkills": ["Quality Inspection", "Measurement Tools", "Documentation", "Testing Procedures", "Attention to Detail"],
        "requiredSoftSkills": ["Attention to Detail", "Reliability", "Communication", "Analytical Thinking", "Patience"],
        "companies": ["3M", "Johnson & Johnson", "Boeing", "General Electric", "Ford", "Local Manufacturers"],
        "learningPath": "Quality Inspection Training (1-2 months)",
        "relevanceScore": 80,
        "confidenceLevel": 78,
        "matchReasons": ["Quality focus", "Detail-oriented", "Analytical skills"],
        "minExperienceYears": 0,
        "maxExperienceYears": 4,
        "minSalary": 40000,
        "maxSalary": 60000
    },
    {
        "title": "Machine Operator",
        "careerType": "machine-operator",
        "description": "Operate manufacturing machinery, monitor production processes, perform basic maintenance tasks.",
        "salaryRange": "$38,000 - $55,000",
        "experienceLevel": "junior",
        "requiredTechnicalSkills": ["Machine Operation", "Safety Procedures", "Basic Maintenance", "Quality Control", "Production Monitoring"],
        "requiredSoftSkills": ["Reliability", "Attention to Detail", "Problem Solving", "Physical Stamina", "Safety Focus"],
        "companies": ["General Motors", "Ford", "Boeing", "Caterpillar", "3M", "Local Manufacturers"],
        "learningPath": "Machine Operation Training (1-2 months)",
        "relevanceScore": 78,
        "confidenceLevel": 75,
        "matchReasons": ["Technical operation", "Hands-on work", "Process monitoring"],
        "minExperienceYears": 0,
        "maxExperienceYears": 3,
        "minSalary": 38000,
        "maxSalary": 55000
    },
    {
        "title": "Warehouse Associate",
        "careerType": "warehouse-associate",
        "description": "Handle inventory, pick and pack orders, operate warehouse equipment, maintain organization.",
        "salaryRange": "$32,000 - $45,000",
        "experienceLevel": "junior",
        "requiredTechnicalSkills": ["Inventory Management", "Warehouse Equipment", "Order Fulfillment", "Safety Procedures", "Basic Computer Skills"],
        "requiredSoftSkills": ["Physical Stamina", "Attention to Detail", "Teamwork", "Reliability", "Organization"],
        "companies": ["Amazon", "Walmart", "FedEx", "UPS", "Target", "Local Warehouses"],
        "learningPath": "Warehouse Operations Training (1 month)",
        "relevanceScore": 75,
        "confidenceLevel": 72,
        "matchReasons": ["Logistics operations", "Physical work", "Organization skills"],
        "minExperienceYears": 0,
        "maxExperienceYears": 3,
        "minSalary": 32000,
        "maxSalary": 45000
    },
    {
        "title": "Assembly Line Worker",
        "careerType": "assembly-line-worker",
        "description": "Assemble products on production line, follow assembly procedures, maintain quality standards.",
        "salaryRange": "$33,000 - $48,000",
        "experienceLevel": "junior",
        "requiredTechnicalSkills": ["Assembly Procedures", "Hand Tools", "Quality Standards", "Safety Procedures", "Production Line Work"],
        "requiredSoftSkills": ["Attention to Detail", "Manual Dexterity", "Teamwork", "Reliability", "Physical Stamina"],
        "companies": ["General Motors", "Ford", "Toyota", "Honda", "Electronics Manufacturers", "Appliance Companies"],
        "learningPath": "Assembly Line Training (1 month)",
        "relevanceScore": 72,
        "confidenceLevel": 70,
        "matchReasons": ["Manufacturing experience", "Team environment", "Hands-on work"],
        "minExperienceYears": 0,
        "maxExperienceYears": 2,
        "minSalary": 33000,
        "maxSalary": 48000
    },

    # SPECIALIZED INDUSTRIAL ROLES
    {
        "title": "Automation Engineer",
        "careerType": "automation-engineer",
        "description": "Design and implement automated systems, program PLCs, optimize manufacturing automation.",
        "salaryRange": "$80,000 - $120,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["PLC Programming", "Industrial Automation", "SCADA Systems", "Robotics", "Control Systems"],
        "requiredSoftSkills": ["Problem Solving", "Analytical Thinking", "Communication", "Project Management", "Innovation"],
        "companies": ["Rockwell Automation", "Siemens", "ABB", "Honeywell", "Emerson", "General Electric"],
        "learningPath": "Industrial Automation Certification (4-6 months)",
        "relevanceScore": 88,
        "confidenceLevel": 85,
        "matchReasons": ["Automation expertise", "Technical skills", "Innovation focus"],
        "minExperienceYears": 4,
        "maxExperienceYears": 10,
        "minSalary": 80000,
        "maxSalary": 120000
    },
    {
        "title": "Safety Manager",
        "careerType": "safety-manager",
        "description": "Develop safety programs, conduct safety training, ensure OSHA compliance and workplace safety.",
        "salaryRange": "$75,000 - $110,000",
        "experienceLevel": "senior",
        "requiredTechnicalSkills": ["Safety Management", "OSHA Regulations", "Risk Assessment", "Safety Training", "Incident Investigation"],
        "requiredSoftSkills": ["Leadership", "Communication", "Attention to Detail", "Problem Solving", "Safety Focus"],
        "companies": ["General Motors", "Ford", "Boeing", "Caterpillar", "3M", "DuPont"],
        "learningPath": "Industrial Safety Management (3-4 months)",
        "relevanceScore": 82,
        "confidenceLevel": 80,
        "matchReasons": ["Safety leadership", "Regulatory knowledge", "Risk management"],
        "minExperienceYears": 6,
        "maxExperienceYears": 12,
        "minSalary": 75000,
        "maxSalary": 110000
    },
    {
        "title": "Lean Manufacturing Specialist",
        "careerType": "lean-manufacturing-specialist",
        "description": "Implement lean principles, eliminate waste, optimize processes for efficiency and quality.",
        "salaryRange": "$65,000 - $95,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Lean Manufacturing", "Six Sigma", "Value Stream Mapping", "Kaizen", "Statistical Analysis"],
        "requiredSoftSkills": ["Analytical Thinking", "Problem Solving", "Communication", "Change Management", "Continuous Improvement"],
        "companies": ["Toyota", "Honda", "General Electric", "Boeing", "3M", "Ford"],
        "learningPath": "Lean Six Sigma Certification (3-4 months)",
        "relevanceScore": 85,
        "confidenceLevel": 82,
        "matchReasons": ["Process improvement", "Efficiency focus", "Analytical skills"],
        "minExperienceYears": 3,
        "maxExperienceYears": 8,
        "minSalary": 65000,
        "maxSalary": 95000
    },
    {
        "title": "Materials Manager",
        "careerType": "materials-manager",
        "description": "Manage material flow, coordinate with suppliers, optimize inventory levels and procurement.",
        "salaryRange": "$70,000 - $105,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Materials Management", "Inventory Control", "Procurement", "ERP Systems", "Supply Chain"],
        "requiredSoftSkills": ["Organization", "Communication", "Negotiation", "Problem Solving", "Planning"],
        "companies": ["General Motors", "Ford", "Boeing", "Caterpillar", "3M", "Honeywell"],
        "learningPath": "Materials Management Certification (3-4 months)",
        "relevanceScore": 80,
        "confidenceLevel": 78,
        "matchReasons": ["Supply chain management", "Organization skills", "Planning focus"],
        "minExperienceYears": 4,
        "maxExperienceYears": 10,
        "minSalary": 70000,
        "maxSalary": 105000
    },
    {
        "title": "Industrial Maintenance Technician",
        "careerType": "industrial-maintenance-technician",
        "description": "Maintain and repair industrial equipment, perform preventive maintenance, troubleshoot mechanical issues.",
        "salaryRange": "$50,000 - $75,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Equipment Maintenance", "Troubleshooting", "Mechanical Repair", "Electrical Systems", "Preventive Maintenance"],
        "requiredSoftSkills": ["Problem Solving", "Attention to Detail", "Physical Stamina", "Safety Focus", "Reliability"],
        "companies": ["General Electric", "Honeywell", "Emerson", "Local Manufacturers", "Utilities", "Chemical Plants"],
        "learningPath": "Industrial Maintenance Training (2-3 months)",
        "relevanceScore": 78,
        "confidenceLevel": 75,
        "matchReasons": ["Technical skills", "Problem solving", "Hands-on work"],
        "minExperienceYears": 2,
        "maxExperienceYears": 8,
        "minSalary": 50000,
        "maxSalary": 75000
    }
]