
"""
Public Service & Government Career Database
Part of comprehensive career database expansion
"""

PUBLIC_SERVICE_CAREERS = [
    # FEDERAL GOVERNMENT - EXECUTIVE LEVEL
    {
        "title": "Federal Agency Director",
        "careerType": "federal-agency-director",
        "description": "Lead federal agencies, oversee policy implementation, manage large government organizations and budgets.",
        "salaryRange": "$180,000 - $220,000",
        "experienceLevel": "executive",
        "requiredTechnicalSkills": ["Public Administration", "Policy Development", "Budget Management", "Strategic Planning"],
        "requiredSoftSkills": ["Executive Leadership", "Public Speaking", "Political Acumen", "Crisis Management"],
        "companies": ["Department of Health", "Department of Education", "EPA", "Department of Transportation", "USDA"],
        "learningPath": "Master's in Public Administration + Senior Government Experience (15+ years)",
        "relevanceScore": 85,
        "confidenceLevel": 88,
        "matchReasons": ["Executive leadership experience", "Public service mission", "Policy expertise"],
        "minExperienceYears": 15,
        "maxExperienceYears": 35,
        "minSalary": 180000,
        "maxSalary": 220000
    },
    {
        "title": "Deputy Secretary",
        "careerType": "deputy-secretary",
        "description": "Serve as second-in-command of federal departments, assist Secretary with policy and operations.",
        "salaryRange": "$170,000 - $200,000",
        "experienceLevel": "executive",
        "requiredTechnicalSkills": ["Public Policy", "Government Operations", "Strategic Management", "Regulatory Affairs"],
        "requiredSoftSkills": ["Leadership", "Communication", "Negotiation", "Political Awareness"],
        "companies": ["Department of Defense", "Department of State", "Treasury Department", "Department of Justice"],
        "learningPath": "Advanced Degree + Senior Government Leadership (12+ years)",
        "relevanceScore": 82,
        "confidenceLevel": 85,
        "matchReasons": ["Senior leadership experience", "Policy background", "Government expertise"],
        "minExperienceYears": 12,
        "maxExperienceYears": 30,
        "minSalary": 170000,
        "maxSalary": 200000
    },
    {
        "title": "Assistant Secretary",
        "careerType": "assistant-secretary",
        "description": "Lead major divisions within federal departments, develop and implement specialized policies.",
        "salaryRange": "$160,000 - $185,000",
        "experienceLevel": "executive",
        "requiredTechnicalSkills": ["Policy Analysis", "Program Management", "Regulatory Knowledge", "Budget Planning"],
        "requiredSoftSkills": ["Leadership", "Strategic Thinking", "Communication", "Stakeholder Management"],
        "companies": ["HHS", "Department of Labor", "Department of Commerce", "Department of Energy"],
        "learningPath": "Master's Degree + Government Leadership Experience (10+ years)",
        "relevanceScore": 80,
        "confidenceLevel": 82,
        "matchReasons": ["Policy leadership", "Government experience", "Strategic management"],
        "minExperienceYears": 10,
        "maxExperienceYears": 25,
        "minSalary": 160000,
        "maxSalary": 185000
    },

    # FEDERAL GOVERNMENT - SENIOR LEVEL
    {
        "title": "Senior Executive Service (SES)",
        "careerType": "senior-executive-service",
        "description": "Serve in top leadership positions in federal government, bridge political and career staff.",
        "salaryRange": "$140,000 - $180,000",
        "experienceLevel": "senior",
        "requiredTechnicalSkills": ["Executive Leadership", "Public Administration", "Policy Implementation", "Change Management"],
        "requiredSoftSkills": ["Leadership", "Communication", "Strategic Vision", "Collaboration"],
        "companies": ["All Federal Agencies", "Department of Veterans Affairs", "Social Security Administration", "IRS"],
        "learningPath": "Federal Career Development + SES Candidate Development Program (8-15 years)",
        "relevanceScore": 88,
        "confidenceLevel": 90,
        "matchReasons": ["Senior government leadership", "Executive development", "Public service impact"],
        "minExperienceYears": 8,
        "maxExperienceYears": 20,
        "minSalary": 140000,
        "maxSalary": 180000
    },
    {
        "title": "GS-15 Program Manager",
        "careerType": "gs15-program-manager",
        "description": "Manage major federal programs, oversee complex projects, lead cross-functional teams.",
        "salaryRange": "$110,000 - $145,000",
        "experienceLevel": "senior",
        "requiredTechnicalSkills": ["Program Management", "Federal Regulations", "Budget Analysis", "Project Planning"],
        "requiredSoftSkills": ["Leadership", "Communication", "Problem Solving", "Team Management"],
        "companies": ["NASA", "CDC", "FBI", "Department of Defense", "Department of Homeland Security"],
        "learningPath": "Bachelor's + Federal Career Progression (8-12 years)",
        "relevanceScore": 85,
        "confidenceLevel": 87,
        "matchReasons": ["Program management experience", "Federal expertise", "Leadership skills"],
        "minExperienceYears": 8,
        "maxExperienceYears": 18,
        "minSalary": 110000,
        "maxSalary": 145000
    },
    {
        "title": "Federal Policy Analyst",
        "careerType": "federal-policy-analyst",
        "description": "Analyze policies, conduct research, provide recommendations to senior leadership on government initiatives.",
        "salaryRange": "$85,000 - $120,000",
        "experienceLevel": "senior",
        "requiredTechnicalSkills": ["Policy Analysis", "Research Methods", "Data Analysis", "Report Writing"],
        "requiredSoftSkills": ["Analytical Thinking", "Communication", "Critical Thinking", "Attention to Detail"],
        "companies": ["Congressional Budget Office", "Government Accountability Office", "OMB", "Policy Think Tanks"],
        "learningPath": "Master's in Public Policy + Government Experience (5-10 years)",
        "relevanceScore": 82,
        "confidenceLevel": 85,
        "matchReasons": ["Policy analysis skills", "Research background", "Government focus"],
        "minExperienceYears": 5,
        "maxExperienceYears": 15,
        "minSalary": 85000,
        "maxSalary": 120000
    },
    {
        "title": "Federal Contracting Officer",
        "careerType": "federal-contracting-officer",
        "description": "Manage government contracts, oversee procurement processes, ensure compliance with federal regulations.",
        "salaryRange": "$90,000 - $130,000",
        "experienceLevel": "senior",
        "requiredTechnicalSkills": ["Federal Acquisition Regulation", "Contract Management", "Procurement", "Negotiation"],
        "requiredSoftSkills": ["Attention to Detail", "Communication", "Problem Solving", "Ethical Judgment"],
        "companies": ["Department of Defense", "GSA", "Department of Energy", "NASA", "Department of Health"],
        "learningPath": "Bachelor's + Federal Acquisition Certification (5-8 years)",
        "relevanceScore": 78,
        "confidenceLevel": 80,
        "matchReasons": ["Contract management", "Federal regulations", "Business acumen"],
        "minExperienceYears": 5,
        "maxExperienceYears": 15,
        "minSalary": 90000,
        "maxSalary": 130000
    },

    # FEDERAL GOVERNMENT - MID LEVEL
    {
        "title": "GS-13 Management Analyst",
        "careerType": "gs13-management-analyst",
        "description": "Analyze organizational efficiency, recommend process improvements, support management decisions.",
        "salaryRange": "$75,000 - $105,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Process Analysis", "Data Analysis", "Project Management", "Performance Measurement"],
        "requiredSoftSkills": ["Analytical Thinking", "Communication", "Problem Solving", "Collaboration"],
        "companies": ["All Federal Agencies", "Department of Veterans Affairs", "Department of Agriculture", "Department of Commerce"],
        "learningPath": "Bachelor's + Federal Experience (3-7 years)",
        "relevanceScore": 80,
        "confidenceLevel": 82,
        "matchReasons": ["Management analysis", "Process improvement", "Government operations"],
        "minExperienceYears": 3,
        "maxExperienceYears": 10,
        "minSalary": 75000,
        "maxSalary": 105000
    },
    {
        "title": "Federal Budget Analyst",
        "careerType": "federal-budget-analyst",
        "description": "Analyze budget proposals, monitor spending, prepare financial reports for government programs.",
        "salaryRange": "$70,000 - $100,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Budget Analysis", "Financial Analysis", "Government Accounting", "Excel/Financial Software"],
        "requiredSoftSkills": ["Attention to Detail", "Analytical Thinking", "Communication", "Time Management"],
        "companies": ["OMB", "Treasury Department", "Department of Defense", "All Federal Agencies"],
        "learningPath": "Bachelor's in Finance/Economics + Government Experience (3-6 years)",
        "relevanceScore": 78,
        "confidenceLevel": 80,
        "matchReasons": ["Financial analysis", "Budget management", "Government finance"],
        "minExperienceYears": 3,
        "maxExperienceYears": 10,
        "minSalary": 70000,
        "maxSalary": 100000
    },
    {
        "title": "Federal Human Resources Specialist",
        "careerType": "federal-hr-specialist",
        "description": "Manage federal hiring processes, employee relations, benefits administration, and workforce planning.",
        "salaryRange": "$65,000 - $95,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Federal HR Regulations", "Recruitment", "Employee Relations", "Benefits Administration"],
        "requiredSoftSkills": ["Communication", "Interpersonal Skills", "Problem Solving", "Confidentiality"],
        "companies": ["OPM", "All Federal Agencies", "Department of Defense", "Department of Veterans Affairs"],
        "learningPath": "Bachelor's + HR Certification + Federal Experience (3-6 years)",
        "relevanceScore": 75,
        "confidenceLevel": 78,
        "matchReasons": ["HR expertise", "Federal employment", "People management"],
        "minExperienceYears": 3,
        "maxExperienceYears": 10,
        "minSalary": 65000,
        "maxSalary": 95000
    },
    {
        "title": "Federal IT Specialist",
        "careerType": "federal-it-specialist",
        "description": "Manage government IT systems, ensure cybersecurity, support digital transformation initiatives.",
        "salaryRange": "$80,000 - $115,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["IT Systems", "Cybersecurity", "Network Administration", "Government IT Standards"],
        "requiredSoftSkills": ["Problem Solving", "Communication", "Attention to Detail", "Continuous Learning"],
        "companies": ["GSA", "Department of Homeland Security", "All Federal Agencies", "Department of Defense"],
        "learningPath": "Bachelor's in IT + Security Clearance + Certifications (3-7 years)",
        "relevanceScore": 82,
        "confidenceLevel": 85,
        "matchReasons": ["IT expertise", "Cybersecurity focus", "Government technology"],
        "minExperienceYears": 3,
        "maxExperienceYears": 10,
        "minSalary": 80000,
        "maxSalary": 115000
    },

    # FEDERAL GOVERNMENT - ENTRY LEVEL
    {
        "title": "GS-11 Program Analyst",
        "careerType": "gs11-program-analyst",
        "description": "Support program operations, conduct basic analysis, assist with project coordination and reporting.",
        "salaryRange": "$55,000 - $75,000",
        "experienceLevel": "junior",
        "requiredTechnicalSkills": ["Data Analysis", "Report Writing", "Microsoft Office", "Basic Project Management"],
        "requiredSoftSkills": ["Communication", "Attention to Detail", "Learning Agility", "Teamwork"],
        "companies": ["All Federal Agencies", "Department of Education", "Department of Health", "EPA"],
        "learningPath": "Bachelor's Degree + Federal Entry Programs (0-3 years)",
        "relevanceScore": 72,
        "confidenceLevel": 75,
        "matchReasons": ["Entry-level government", "Analytical skills", "Program support"],
        "minExperienceYears": 0,
        "maxExperienceYears": 5,
        "minSalary": 55000,
        "maxSalary": 75000
    },
    {
        "title": "Federal Administrative Officer",
        "careerType": "federal-administrative-officer",
        "description": "Handle administrative functions, process paperwork, support government operations and services.",
        "salaryRange": "$45,000 - $65,000",
        "experienceLevel": "junior",
        "requiredTechnicalSkills": ["Administrative Procedures", "Government Regulations", "Data Entry", "Customer Service"],
        "requiredSoftSkills": ["Organization", "Communication", "Attention to Detail", "Public Service"],
        "companies": ["Social Security Administration", "IRS", "Department of Veterans Affairs", "All Federal Agencies"],
        "learningPath": "High School + Federal Training Programs (0-2 years)",
        "relevanceScore": 68,
        "confidenceLevel": 70,
        "matchReasons": ["Administrative skills", "Government service", "Entry-level opportunity"],
        "minExperienceYears": 0,
        "maxExperienceYears": 3,
        "minSalary": 45000,
        "maxSalary": 65000
    },

    # STATE GOVERNMENT
    {
        "title": "State Agency Director",
        "careerType": "state-agency-director",
        "description": "Lead state agencies, implement state policies, manage budgets and staff across state programs.",
        "salaryRange": "$120,000 - $180,000",
        "experienceLevel": "executive",
        "requiredTechnicalSkills": ["Public Administration", "State Government", "Policy Implementation", "Budget Management"],
        "requiredSoftSkills": ["Executive Leadership", "Political Acumen", "Communication", "Strategic Planning"],
        "companies": ["State Departments of Health", "State Education Departments", "State Transportation", "State Environmental"],
        "learningPath": "Master's in Public Administration + State Government Experience (10+ years)",
        "relevanceScore": 85,
        "confidenceLevel": 88,
        "matchReasons": ["State government leadership", "Policy expertise", "Executive experience"],
        "minExperienceYears": 10,
        "maxExperienceYears": 30,
        "minSalary": 120000,
        "maxSalary": 180000
    },
    {
        "title": "State Program Manager",
        "careerType": "state-program-manager",
        "description": "Manage state programs, coordinate with federal agencies, oversee program implementation and compliance.",
        "salaryRange": "$75,000 - $110,000",
        "experienceLevel": "senior",
        "requiredTechnicalSkills": ["Program Management", "State Regulations", "Federal Compliance", "Budget Analysis"],
        "requiredSoftSkills": ["Leadership", "Communication", "Problem Solving", "Collaboration"],
        "companies": ["State Health Departments", "State Education", "State Social Services", "State Environmental"],
        "learningPath": "Bachelor's + State Government Experience (5-10 years)",
        "relevanceScore": 80,
        "confidenceLevel": 82,
        "matchReasons": ["Program management", "State government", "Policy implementation"],
        "minExperienceYears": 5,
        "maxExperienceYears": 15,
        "minSalary": 75000,
        "maxSalary": 110000
    },
    {
        "title": "State Policy Analyst",
        "careerType": "state-policy-analyst",
        "description": "Analyze state policies, conduct research, provide recommendations to state leadership and legislators.",
        "salaryRange": "$60,000 - $85,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Policy Analysis", "Research Methods", "Data Analysis", "Legislative Process"],
        "requiredSoftSkills": ["Analytical Thinking", "Writing Skills", "Communication", "Critical Thinking"],
        "companies": ["State Legislatures", "Governor's Office", "State Budget Office", "State Planning Departments"],
        "learningPath": "Master's in Public Policy + State Experience (3-7 years)",
        "relevanceScore": 78,
        "confidenceLevel": 80,
        "matchReasons": ["Policy analysis", "Research skills", "State government focus"],
        "minExperienceYears": 3,
        "maxExperienceYears": 10,
        "minSalary": 60000,
        "maxSalary": 85000
    },
    {
        "title": "State Social Worker",
        "careerType": "state-social-worker",
        "description": "Provide social services, case management, and support to state residents in need.",
        "salaryRange": "$50,000 - $70,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Social Work", "Case Management", "State Regulations", "Crisis Intervention"],
        "requiredSoftSkills": ["Empathy", "Communication", "Problem Solving", "Cultural Sensitivity"],
        "companies": ["State Social Services", "State Child Protective Services", "State Mental Health", "State Aging Services"],
        "learningPath": "Master's in Social Work + State Licensure (2-5 years)",
        "relevanceScore": 82,
        "confidenceLevel": 85,
        "matchReasons": ["Social services", "Helping others", "State government service"],
        "minExperienceYears": 2,
        "maxExperienceYears": 12,
        "minSalary": 50000,
        "maxSalary": 70000
    },

    # LOCAL GOVERNMENT
    {
        "title": "City Manager",
        "careerType": "city-manager",
        "description": "Serve as chief executive of city government, implement city council policies, manage municipal operations.",
        "salaryRange": "$100,000 - $200,000",
        "experienceLevel": "executive",
        "requiredTechnicalSkills": ["Municipal Management", "Public Administration", "Budget Management", "Urban Planning"],
        "requiredSoftSkills": ["Executive Leadership", "Communication", "Political Acumen", "Crisis Management"],
        "companies": ["City Governments", "Municipal Corporations", "Town Governments"],
        "learningPath": "Master's in Public Administration + Municipal Experience (8-15 years)",
        "relevanceScore": 88,
        "confidenceLevel": 90,
        "matchReasons": ["Municipal leadership", "Executive management", "Local government"],
        "minExperienceYears": 8,
        "maxExperienceYears": 25,
        "minSalary": 100000,
        "maxSalary": 200000
    },
    {
        "title": "County Administrator",
        "careerType": "county-administrator",
        "description": "Manage county government operations, implement board policies, oversee county departments and services.",
        "salaryRange": "$90,000 - $160,000",
        "experienceLevel": "executive",
        "requiredTechnicalSkills": ["County Government", "Public Administration", "Budget Management", "Policy Implementation"],
        "requiredSoftSkills": ["Leadership", "Communication", "Strategic Planning", "Collaboration"],
        "companies": ["County Governments", "Regional Authorities", "Metropolitan Governments"],
        "learningPath": "Master's in Public Administration + County Experience (8-12 years)",
        "relevanceScore": 85,
        "confidenceLevel": 87,
        "matchReasons": ["County government leadership", "Administrative expertise", "Public service"],
        "minExperienceYears": 8,
        "maxExperienceYears": 20,
        "minSalary": 90000,
        "maxSalary": 160000
    },
    {
        "title": "Municipal Department Head",
        "careerType": "municipal-department-head",
        "description": "Lead city departments such as public works, parks and recreation, or community development.",
        "salaryRange": "$75,000 - $120,000",
        "experienceLevel": "senior",
        "requiredTechnicalSkills": ["Department Management", "Municipal Operations", "Budget Planning", "Staff Management"],
        "requiredSoftSkills": ["Leadership", "Communication", "Problem Solving", "Public Service"],
        "companies": ["City Public Works", "Parks and Recreation", "Community Development", "Municipal Utilities"],
        "learningPath": "Bachelor's + Municipal Experience + Department Expertise (6-12 years)",
        "relevanceScore": 82,
        "confidenceLevel": 85,
        "matchReasons": ["Department leadership", "Municipal operations", "Public service management"],
        "minExperienceYears": 6,
        "maxExperienceYears": 18,
        "minSalary": 75000,
        "maxSalary": 120000
    },
    {
        "title": "City Planner",
        "careerType": "city-planner",
        "description": "Develop land use plans, review development proposals, guide community growth and development.",
        "salaryRange": "$65,000 - $95,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Urban Planning", "Zoning", "GIS", "Land Use Planning", "Development Review"],
        "requiredSoftSkills": ["Analytical Thinking", "Communication", "Problem Solving", "Public Engagement"],
        "companies": ["City Planning Departments", "Regional Planning Commissions", "County Planning", "Consulting Firms"],
        "learningPath": "Master's in Urban Planning + Planning Experience (3-8 years)",
        "relevanceScore": 80,
        "confidenceLevel": 82,
        "matchReasons": ["Urban planning", "Community development", "Analytical skills"],
        "minExperienceYears": 3,
        "maxExperienceYears": 12,
        "minSalary": 65000,
        "maxSalary": 95000
    },
    {
        "title": "Municipal Finance Director",
        "careerType": "municipal-finance-director",
        "description": "Manage city finances, prepare budgets, oversee accounting and financial reporting for municipal government.",
        "salaryRange": "$80,000 - $130,000",
        "experienceLevel": "senior",
        "requiredTechnicalSkills": ["Municipal Finance", "Government Accounting", "Budget Management", "Financial Analysis"],
        "requiredSoftSkills": ["Leadership", "Attention to Detail", "Communication", "Ethical Standards"],
        "companies": ["City Governments", "County Governments", "Municipal Authorities", "Special Districts"],
        "learningPath": "Bachelor's in Finance/Accounting + CPA + Municipal Experience (6-10 years)",
        "relevanceScore": 85,
        "confidenceLevel": 87,
        "matchReasons": ["Financial management", "Municipal expertise", "Leadership skills"],
        "minExperienceYears": 6,
        "maxExperienceYears": 15,
        "minSalary": 80000,
        "maxSalary": 130000
    },

    # PUBLIC SAFETY
    {
        "title": "Police Chief",
        "careerType": "police-chief",
        "description": "Lead police department, develop law enforcement policies, ensure public safety and community relations.",
        "salaryRange": "$90,000 - $180,000",
        "experienceLevel": "executive",
        "requiredTechnicalSkills": ["Law Enforcement", "Police Administration", "Criminal Justice", "Emergency Management"],
        "requiredSoftSkills": ["Leadership", "Communication", "Crisis Management", "Community Relations"],
        "companies": ["Municipal Police Departments", "County Sheriff Offices", "State Police"],
        "learningPath": "Criminal Justice Degree + Law Enforcement Career + Command Training (15+ years)",
        "relevanceScore": 88,
        "confidenceLevel": 90,
        "matchReasons": ["Law enforcement leadership", "Public safety", "Community service"],
        "minExperienceYears": 15,
        "maxExperienceYears": 30,
        "minSalary": 90000,
        "maxSalary": 180000
    },
    {
        "title": "Fire Chief",
        "careerType": "fire-chief",
        "description": "Lead fire department, oversee emergency response, manage fire prevention and public safety programs.",
        "salaryRange": "$85,000 - $160,000",
        "experienceLevel": "executive",
        "requiredTechnicalSkills": ["Fire Science", "Emergency Management", "Fire Administration", "Public Safety"],
        "requiredSoftSkills": ["Leadership", "Crisis Management", "Communication", "Decision Making"],
        "companies": ["Municipal Fire Departments", "Fire Districts", "County Fire Services"],
        "learningPath": "Fire Science Degree + Firefighting Career + Command Training (12+ years)",
        "relevanceScore": 85,
        "confidenceLevel": 87,
        "matchReasons": ["Emergency management", "Public safety leadership", "Community service"],
        "minExperienceYears": 12,
        "maxExperienceYears": 25,
        "minSalary": 85000,
        "maxSalary": 160000
    },
    {
        "title": "Emergency Management Director",
        "careerType": "emergency-management-director",
        "description": "Coordinate emergency preparedness, manage disaster response, develop emergency plans and procedures.",
        "salaryRange": "$75,000 - $120,000",
        "experienceLevel": "senior",
        "requiredTechnicalSkills": ["Emergency Management", "Disaster Response", "FEMA Procedures", "Crisis Planning"],
        "requiredSoftSkills": ["Leadership", "Crisis Management", "Communication", "Coordination"],
        "companies": ["County Emergency Management", "State Emergency Management", "FEMA", "Municipal Emergency Services"],
        "learningPath": "Bachelor's + Emergency Management Certification + Experience (6-12 years)",
        "relevanceScore": 82,
        "confidenceLevel": 85,
        "matchReasons": ["Emergency management", "Crisis leadership", "Public safety"],
        "minExperienceYears": 6,
        "maxExperienceYears": 18,
        "minSalary": 75000,
        "maxSalary": 120000
    },
    {
        "title": "Police Detective",
        "careerType": "police-detective",
        "description": "Investigate crimes, gather evidence, interview witnesses, prepare cases for prosecution.",
        "salaryRange": "$65,000 - $95,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Criminal Investigation", "Evidence Collection", "Interview Techniques", "Report Writing"],
        "requiredSoftSkills": ["Analytical Thinking", "Attention to Detail", "Communication", "Persistence"],
        "companies": ["Police Departments", "Sheriff Offices", "State Investigation Bureaus", "Federal Agencies"],
        "learningPath": "Police Academy + Patrol Experience + Detective Training (5-10 years)",
        "relevanceScore": 80,
        "confidenceLevel": 82,
        "matchReasons": ["Investigation skills", "Law enforcement", "Problem solving"],
        "minExperienceYears": 5,
        "maxExperienceYears": 15,
        "minSalary": 65000,
        "maxSalary": 95000
    },
    {
        "title": "Firefighter/Paramedic",
        "careerType": "firefighter-paramedic",
        "description": "Respond to fires and medical emergencies, provide emergency medical care, conduct fire prevention activities.",
        "salaryRange": "$55,000 - $85,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Firefighting", "Emergency Medical Services", "Rescue Operations", "Fire Prevention"],
        "requiredSoftSkills": ["Physical Fitness", "Teamwork", "Quick Decision Making", "Compassion"],
        "companies": ["Fire Departments", "Emergency Medical Services", "Airport Fire Rescue", "Industrial Fire Services"],
        "learningPath": "Fire Academy + EMT/Paramedic Certification + Experience (2-8 years)",
        "relevanceScore": 78,
        "confidenceLevel": 80,
        "matchReasons": ["Emergency response", "Public safety", "Helping others"],
        "minExperienceYears": 2,
        "maxExperienceYears": 12,
        "minSalary": 55000,
        "maxSalary": 85000
    },

    # LEGISLATIVE BRANCH
    {
        "title": "Legislative Director",
        "careerType": "legislative-director",
        "description": "Manage legislative office, coordinate policy initiatives, oversee staff and legislative agenda.",
        "salaryRange": "$90,000 - $150,000",
        "experienceLevel": "senior",
        "requiredTechnicalSkills": ["Legislative Process", "Policy Development", "Political Strategy", "Staff Management"],
        "requiredSoftSkills": ["Leadership", "Political Acumen", "Communication", "Strategic Thinking"],
        "companies": ["Congressional Offices", "State Legislatures", "Legislative Committees", "Political Organizations"],
        "learningPath": "Political Science/Public Policy + Legislative Experience (6-12 years)",
        "relevanceScore": 85,
        "confidenceLevel": 87,
        "matchReasons": ["Legislative expertise", "Policy leadership", "Political strategy"],
        "minExperienceYears": 6,
        "maxExperienceYears": 18,
        "minSalary": 90000,
        "maxSalary": 150000
    },
    {
        "title": "Congressional Staff Director",
        "careerType": "congressional-staff-director",
        "description": "Lead congressional office operations, manage staff, coordinate legislative and constituent services.",
        "salaryRange": "$120,000 - $180,000",
        "experienceLevel": "senior",
        "requiredTechnicalSkills": ["Congressional Operations", "Legislative Process", "Staff Management", "Political Strategy"],
        "requiredSoftSkills": ["Leadership", "Political Acumen", "Communication", "Crisis Management"],
        "companies": ["House of Representatives", "U.S. Senate", "Congressional Committees"],
        "learningPath": "Political Science + Congressional Experience + Leadership Development (8-15 years)",
        "relevanceScore": 88,
        "confidenceLevel": 90,
        "matchReasons": ["Congressional leadership", "Political expertise", "Staff management"],
        "minExperienceYears": 8,
        "maxExperienceYears": 20,
        "minSalary": 120000,
        "maxSalary": 180000
    },
    {
        "title": "Legislative Analyst",
        "careerType": "legislative-analyst",
        "description": "Research policy issues, analyze legislation, provide briefings and recommendations to legislators.",
        "salaryRange": "$60,000 - $90,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Policy Research", "Legislative Analysis", "Report Writing", "Data Analysis"],
        "requiredSoftSkills": ["Analytical Thinking", "Writing Skills", "Communication", "Critical Thinking"],
        "companies": ["State Legislatures", "Congressional Offices", "Legislative Research Services", "Policy Organizations"],
        "learningPath": "Master's in Public Policy + Legislative Experience (3-7 years)",
        "relevanceScore": 78,
        "confidenceLevel": 80,
        "matchReasons": ["Policy research", "Legislative analysis", "Government focus"],
        "minExperienceYears": 3,
        "maxExperienceYears": 10,
        "minSalary": 60000,
        "maxSalary": 90000
    }
]