"""
Skilled Trades & Construction Career Database
Part of comprehensive career database expansion - Phase 1A
"""

SKILLED_TRADES_CAREERS = [
    # ELECTRICAL TRADES
    {
        "title": "Electrician",
        "careerType": "electrician",
        "description": "Install, maintain, and repair electrical systems in residential, commercial, and industrial settings.",
        "salaryRange": "$55,000 - $85,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Electrical Systems", "Wiring", "Electrical Codes", "Troubleshooting"],
        "requiredSoftSkills": ["Problem Solving", "Attention to Detail", "Physical Stamina", "Safety Consciousness"],
        "companies": ["Electrical Contractors", "Construction Companies", "Utilities", "Manufacturing"],
        "learningPath": "Apprenticeship Program (4 years) + Licensing",
        "relevanceScore": 78,
        "confidenceLevel": 80,
        "matchReasons": ["Technical skills", "Hands-on work", "Problem solving"],
        "minExperienceYears": 0,
        "maxExperienceYears": 40,
        "minSalary": 55000,
        "maxSalary": 85000
    },
    {
        "title": "Master Electrician",
        "careerType": "master-electrician",
        "description": "Lead electrical projects, supervise apprentices, design electrical systems, ensure code compliance.",
        "salaryRange": "$75,000 - $110,000",
        "experienceLevel": "senior",
        "requiredTechnicalSkills": ["Advanced Electrical Systems", "Project Management", "Electrical Design", "Code Compliance"],
        "requiredSoftSkills": ["Leadership", "Teaching", "Project Management", "Business Skills"],
        "companies": ["Electrical Contractors", "Construction Companies", "Own Business"],
        "learningPath": "Journeyman + Additional Experience + Master License (8+ years)",
        "relevanceScore": 82,
        "confidenceLevel": 85,
        "matchReasons": ["Advanced technical expertise", "Leadership role", "Business ownership potential"],
        "minExperienceYears": 8,
        "maxExperienceYears": 40,
        "minSalary": 75000,
        "maxSalary": 110000
    },
    {
        "title": "Electrical Engineer",
        "careerType": "electrical-engineer",
        "description": "Design electrical systems, develop electrical components, oversee electrical projects and installations.",
        "salaryRange": "$85,000 - $130,000",
        "experienceLevel": "senior",
        "requiredTechnicalSkills": ["Electrical Engineering", "Circuit Design", "Power Systems", "CAD Software"],
        "requiredSoftSkills": ["Analytical Thinking", "Problem Solving", "Communication", "Project Management"],
        "companies": ["Engineering Firms", "Utilities", "Manufacturing", "Construction"],
        "learningPath": "Bachelor's in Electrical Engineering + PE License (4-6 years)",
        "relevanceScore": 85,
        "confidenceLevel": 88,
        "matchReasons": ["Engineering background", "Technical design", "System thinking"],
        "minExperienceYears": 4,
        "maxExperienceYears": 35,
        "minSalary": 85000,
        "maxSalary": 130000
    },
    {
        "title": "Power Line Technician",
        "careerType": "power-line-technician",
        "description": "Install, maintain, and repair electrical power lines and systems for utility companies.",
        "salaryRange": "$65,000 - $95,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["High Voltage Systems", "Power Line Equipment", "Safety Procedures", "Climbing Techniques"],
        "requiredSoftSkills": ["Physical Fitness", "Risk Assessment", "Teamwork", "Emergency Response"],
        "companies": ["Utility Companies", "Power Contractors", "Municipal Utilities", "Cooperative Utilities"],
        "learningPath": "Technical School + Apprenticeship (2-4 years)",
        "relevanceScore": 80,
        "confidenceLevel": 82,
        "matchReasons": ["High-demand specialty", "Good compensation", "Critical infrastructure"],
        "minExperienceYears": 0,
        "maxExperienceYears": 35,
        "minSalary": 65000,
        "maxSalary": 95000
    },
    {
        "title": "Industrial Electrician",
        "careerType": "industrial-electrician",
        "description": "Maintain and repair electrical systems in manufacturing and industrial facilities.",
        "salaryRange": "$60,000 - $90,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Industrial Controls", "Motor Systems", "PLC Programming", "Electrical Troubleshooting"],
        "requiredSoftSkills": ["Problem Solving", "Analytical Thinking", "Safety Consciousness", "Continuous Learning"],
        "companies": ["Manufacturing Plants", "Chemical Companies", "Food Processing", "Automotive Plants"],
        "learningPath": "Electrical Apprenticeship + Industrial Training (4-6 years)",
        "relevanceScore": 82,
        "confidenceLevel": 84,
        "matchReasons": ["Specialized industrial knowledge", "Technology integration", "Problem solving"],
        "minExperienceYears": 2,
        "maxExperienceYears": 35,
        "minSalary": 60000,
        "maxSalary": 90000
    },
    {
        "title": "Electrical Inspector",
        "careerType": "electrical-inspector",
        "description": "Inspect electrical installations to ensure compliance with codes and safety standards.",
        "salaryRange": "$55,000 - $80,000",
        "experienceLevel": "senior",
        "requiredTechnicalSkills": ["Electrical Codes", "Inspection Procedures", "Safety Standards", "Documentation"],
        "requiredSoftSkills": ["Attention to Detail", "Communication", "Regulatory Knowledge", "Report Writing"],
        "companies": ["Government Agencies", "Inspection Companies", "Utilities", "Insurance Companies"],
        "learningPath": "Electrical Experience + Inspector Certification (8-10 years)",
        "relevanceScore": 75,
        "confidenceLevel": 78,
        "matchReasons": ["Regulatory expertise", "Quality assurance", "Safety focus"],
        "minExperienceYears": 8,
        "maxExperienceYears": 35,
        "minSalary": 55000,
        "maxSalary": 80000
    },

    # PLUMBING & HVAC
    {
        "title": "Plumber",
        "careerType": "plumber",
        "description": "Install, repair, and maintain plumbing systems, pipes, fixtures, and water systems.",
        "salaryRange": "$50,000 - $80,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Plumbing Systems", "Pipe Installation", "Water Systems", "Plumbing Codes"],
        "requiredSoftSkills": ["Problem Solving", "Physical Stamina", "Customer Service", "Attention to Detail"],
        "companies": ["Plumbing Contractors", "Construction Companies", "Maintenance Companies", "Self-Employed"],
        "learningPath": "Apprenticeship Program (4-5 years) + Licensing",
        "relevanceScore": 75,
        "confidenceLevel": 78,
        "matchReasons": ["Hands-on work", "Problem solving", "Essential services"],
        "minExperienceYears": 0,
        "maxExperienceYears": 40,
        "minSalary": 50000,
        "maxSalary": 80000
    },
    {
        "title": "HVAC Technician",
        "careerType": "hvac-technician",
        "description": "Install, maintain, and repair heating, ventilation, and air conditioning systems.",
        "salaryRange": "$48,000 - $75,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["HVAC Systems", "Refrigeration", "Electrical Components", "System Diagnostics"],
        "requiredSoftSkills": ["Problem Solving", "Customer Service", "Physical Stamina", "Attention to Detail"],
        "companies": ["HVAC Contractors", "Construction Companies", "Facilities Management", "Self-Employed"],
        "learningPath": "Technical School + Apprenticeship (2-4 years) + Certification",
        "relevanceScore": 76,
        "confidenceLevel": 78,
        "matchReasons": ["Technical systems", "Problem solving", "Growing demand"],
        "minExperienceYears": 0,
        "maxExperienceYears": 35,
        "minSalary": 48000,
        "maxSalary": 75000
    },
    {
        "title": "Master Plumber",
        "careerType": "master-plumber",
        "description": "Lead plumbing projects, supervise teams, design plumbing systems, run plumbing business.",
        "salaryRange": "$70,000 - $105,000",
        "experienceLevel": "senior",
        "requiredTechnicalSkills": ["Advanced Plumbing", "System Design", "Project Management", "Business Operations"],
        "requiredSoftSkills": ["Leadership", "Business Management", "Customer Relations", "Teaching"],
        "companies": ["Plumbing Contractors", "Construction Companies", "Own Business"],
        "learningPath": "Journeyman + Experience + Master License (8+ years)",
        "relevanceScore": 80,
        "confidenceLevel": 82,
        "matchReasons": ["Advanced expertise", "Business ownership", "Leadership role"],
        "minExperienceYears": 8,
        "maxExperienceYears": 40,
        "minSalary": 70000,
        "maxSalary": 105000
    },
    {
        "title": "Pipefitter",
        "careerType": "pipefitter",
        "description": "Install and maintain high-pressure piping systems in industrial and commercial settings.",
        "salaryRange": "$55,000 - $85,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Pipe Systems", "Welding", "Blueprint Reading", "Pressure Testing"],
        "requiredSoftSkills": ["Physical Stamina", "Precision", "Safety Consciousness", "Problem Solving"],
        "companies": ["Industrial Contractors", "Power Plants", "Chemical Plants", "Refineries"],
        "learningPath": "Apprenticeship Program (4-5 years)",
        "relevanceScore": 78,
        "confidenceLevel": 80,
        "matchReasons": ["Specialized skills", "Industrial applications", "Good compensation"],
        "minExperienceYears": 0,
        "maxExperienceYears": 35,
        "minSalary": 55000,
        "maxSalary": 85000
    },
    {
        "title": "HVAC Engineer",
        "careerType": "hvac-engineer",
        "description": "Design heating, ventilation, and air conditioning systems for buildings and facilities.",
        "salaryRange": "$70,000 - $105,000",
        "experienceLevel": "senior",
        "requiredTechnicalSkills": ["HVAC Design", "Energy Efficiency", "Building Codes", "CAD Software"],
        "requiredSoftSkills": ["Analytical Thinking", "Project Management", "Communication", "Problem Solving"],
        "companies": ["Engineering Firms", "Construction Companies", "Consulting Firms", "Government"],
        "learningPath": "Engineering Degree + HVAC Specialization (4-6 years)",
        "relevanceScore": 82,
        "confidenceLevel": 85,
        "matchReasons": ["Engineering expertise", "Energy efficiency focus", "Design work"],
        "minExperienceYears": 4,
        "maxExperienceYears": 35,
        "minSalary": 70000,
        "maxSalary": 105000
    },
    {
        "title": "Refrigeration Technician",
        "careerType": "refrigeration-technician",
        "description": "Install, maintain, and repair commercial and industrial refrigeration systems.",
        "salaryRange": "$45,000 - $70,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Refrigeration Systems", "Electrical Controls", "System Diagnostics", "EPA Certification"],
        "requiredSoftSkills": ["Problem Solving", "Attention to Detail", "Customer Service", "Safety Awareness"],
        "companies": ["Refrigeration Contractors", "Food Service", "Grocery Stores", "Cold Storage"],
        "learningPath": "Technical School + EPA Certification (1-2 years)",
        "relevanceScore": 74,
        "confidenceLevel": 76,
        "matchReasons": ["Specialized niche", "Essential services", "Technical skills"],
        "minExperienceYears": 0,
        "maxExperienceYears": 35,
        "minSalary": 45000,
        "maxSalary": 70000
    },

    # CONSTRUCTION TRADES
    {
        "title": "Carpenter",
        "careerType": "carpenter",
        "description": "Build, install, and repair structures and fixtures made from wood and other materials.",
        "salaryRange": "$45,000 - $70,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Carpentry", "Woodworking", "Construction Tools", "Blueprint Reading"],
        "requiredSoftSkills": ["Attention to Detail", "Physical Stamina", "Problem Solving", "Craftsmanship"],
        "companies": ["Construction Companies", "Contractors", "Furniture Makers", "Self-Employed"],
        "learningPath": "Apprenticeship or On-the-Job Training (3-4 years)",
        "relevanceScore": 72,
        "confidenceLevel": 75,
        "matchReasons": ["Hands-on craftsmanship", "Building and creating", "Practical skills"],
        "minExperienceYears": 0,
        "maxExperienceYears": 40,
        "minSalary": 45000,
        "maxSalary": 70000
    },
    {
        "title": "Construction Manager",
        "careerType": "construction-manager",
        "description": "Oversee construction projects, manage teams, ensure safety and quality, coordinate schedules.",
        "salaryRange": "$85,000 - $130,000",
        "experienceLevel": "senior",
        "requiredTechnicalSkills": ["Construction Management", "Project Planning", "Safety Regulations", "Cost Estimation"],
        "requiredSoftSkills": ["Leadership", "Communication", "Problem Solving", "Organization"],
        "companies": ["Construction Companies", "General Contractors", "Real Estate Developers"],
        "learningPath": "Construction Experience + Management Training (8-12 years)",
        "relevanceScore": 82,
        "confidenceLevel": 85,
        "matchReasons": ["Project management", "Leadership role", "Construction expertise"],
        "minExperienceYears": 8,
        "maxExperienceYears": 35,
        "minSalary": 85000,
        "maxSalary": 130000
    },
    {
        "title": "Mason",
        "careerType": "mason",
        "description": "Build structures with brick, stone, concrete blocks, and other masonry materials.",
        "salaryRange": "$42,000 - $65,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Masonry", "Bricklaying", "Stone Work", "Mortar Mixing"],
        "requiredSoftSkills": ["Physical Stamina", "Attention to Detail", "Craftsmanship", "Patience"],
        "companies": ["Construction Companies", "Masonry Contractors", "Restoration Companies", "Self-Employed"],
        "learningPath": "Apprenticeship or On-the-Job Training (3-4 years)",
        "relevanceScore": 70,
        "confidenceLevel": 72,
        "matchReasons": ["Traditional craftsmanship", "Building skills", "Artistic elements"],
        "minExperienceYears": 0,
        "maxExperienceYears": 40,
        "minSalary": 42000,
        "maxSalary": 65000
    },
    {
        "title": "Roofer",
        "careerType": "roofer",
        "description": "Install, repair, and maintain roofs using various materials and techniques.",
        "salaryRange": "$40,000 - $65,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Roofing Systems", "Material Installation", "Safety Procedures", "Weather Sealing"],
        "requiredSoftSkills": ["Physical Stamina", "Balance", "Attention to Detail", "Safety Consciousness"],
        "companies": ["Roofing Contractors", "Construction Companies", "Self-Employed"],
        "learningPath": "On-the-Job Training or Apprenticeship (2-3 years)",
        "relevanceScore": 68,
        "confidenceLevel": 70,
        "matchReasons": ["Specialized trade", "Physical work", "Weather protection expertise"],
        "minExperienceYears": 0,
        "maxExperienceYears": 35,
        "minSalary": 40000,
        "maxSalary": 65000
    },
    {
        "title": "Concrete Finisher",
        "careerType": "concrete-finisher",
        "description": "Pour, smooth, and finish concrete surfaces for construction projects.",
        "salaryRange": "$38,000 - $60,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Concrete Work", "Surface Finishing", "Tools Operation", "Quality Control"],
        "requiredSoftSkills": ["Physical Stamina", "Attention to Detail", "Time Management", "Teamwork"],
        "companies": ["Construction Companies", "Concrete Contractors", "Infrastructure Projects"],
        "learningPath": "On-the-Job Training or Apprenticeship (2-3 years)",
        "relevanceScore": 68,
        "confidenceLevel": 70,
        "matchReasons": ["Essential construction skill", "Physical work", "Infrastructure projects"],
        "minExperienceYears": 0,
        "maxExperienceYears": 35,
        "minSalary": 38000,
        "maxSalary": 60000
    },
    {
        "title": "Drywall Installer",
        "careerType": "drywall-installer",
        "description": "Install and finish drywall panels in residential and commercial construction.",
        "salaryRange": "$40,000 - $62,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Drywall Installation", "Taping", "Mudding", "Sanding"],
        "requiredSoftSkills": ["Attention to Detail", "Physical Stamina", "Efficiency", "Quality Focus"],
        "companies": ["Construction Companies", "Drywall Contractors", "Renovation Companies"],
        "learningPath": "On-the-Job Training (1-2 years)",
        "relevanceScore": 65,
        "confidenceLevel": 68,
        "matchReasons": ["Construction specialty", "Finishing work", "Steady demand"],
        "minExperienceYears": 0,
        "maxExperienceYears": 30,
        "minSalary": 40000,
        "maxSalary": 62000
    },
    {
        "title": "Flooring Installer",
        "careerType": "flooring-installer",
        "description": "Install various types of flooring including hardwood, tile, carpet, and laminate.",
        "salaryRange": "$35,000 - $58,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Flooring Installation", "Measuring", "Cutting Tools", "Surface Preparation"],
        "requiredSoftSkills": ["Attention to Detail", "Customer Service", "Physical Stamina", "Craftsmanship"],
        "companies": ["Flooring Contractors", "Home Improvement Stores", "Construction Companies", "Self-Employed"],
        "learningPath": "On-the-Job Training or Technical School (1-2 years)",
        "relevanceScore": 66,
        "confidenceLevel": 68,
        "matchReasons": ["Finishing specialty", "Customer interaction", "Craftsmanship"],
        "minExperienceYears": 0,
        "maxExperienceYears": 30,
        "minSalary": 35000,
        "maxSalary": 58000
    },
    {
        "title": "Construction Project Manager",
        "careerType": "construction-project-manager",
        "description": "Plan, coordinate, and oversee construction projects from start to completion.",
        "salaryRange": "$75,000 - $115,000",
        "experienceLevel": "senior",
        "requiredTechnicalSkills": ["Project Management", "Construction Knowledge", "Scheduling", "Budget Management"],
        "requiredSoftSkills": ["Leadership", "Communication", "Problem Solving", "Organization"],
        "companies": ["General Contractors", "Construction Companies", "Real Estate Developers"],
        "learningPath": "Construction Experience + Project Management Training (6-10 years)",
        "relevanceScore": 85,
        "confidenceLevel": 88,
        "matchReasons": ["Management role", "Project coordination", "Construction expertise"],
        "minExperienceYears": 6,
        "maxExperienceYears": 35,
        "minSalary": 75000,
        "maxSalary": 115000
    },
    {
        "title": "Heavy Equipment Operator",
        "careerType": "heavy-equipment-operator",
        "description": "Operate heavy machinery for construction, excavation, and site preparation projects.",
        "salaryRange": "$45,000 - $70,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Heavy Equipment Operation", "Safety Procedures", "Equipment Maintenance", "Site Preparation"],
        "requiredSoftSkills": ["Hand-Eye Coordination", "Safety Consciousness", "Attention to Detail", "Spatial Awareness"],
        "companies": ["Construction Companies", "Excavation Contractors", "Mining Companies", "Utilities"],
        "learningPath": "Equipment Training + Certification (3-6 months)",
        "relevanceScore": 72,
        "confidenceLevel": 75,
        "matchReasons": ["Specialized equipment skills", "Construction projects", "Good demand"],
        "minExperienceYears": 0,
        "maxExperienceYears": 35,
        "minSalary": 45000,
        "maxSalary": 70000
    },

    # AUTOMOTIVE TRADES
    {
        "title": "Automotive Technician",
        "careerType": "automotive-technician",
        "description": "Diagnose, repair, and maintain automobiles and light trucks using computerized diagnostic equipment.",
        "salaryRange": "$42,000 - $65,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Automotive Repair", "Diagnostic Equipment", "Engine Systems", "Electrical Systems"],
        "requiredSoftSkills": ["Problem Solving", "Attention to Detail", "Customer Service", "Continuous Learning"],
        "companies": ["Auto Dealerships", "Independent Repair Shops", "Fleet Services", "Tire Centers"],
        "learningPath": "Technical School + ASE Certification (1-2 years)",
        "relevanceScore": 75,
        "confidenceLevel": 78,
        "matchReasons": ["Mechanical aptitude", "Problem solving", "Technology integration"],
        "minExperienceYears": 0,
        "maxExperienceYears": 35,
        "minSalary": 42000,
        "maxSalary": 65000
    },
    {
        "title": "Master Automotive Technician",
        "careerType": "master-automotive-technician",
        "description": "Lead automotive repair teams, handle complex diagnostics, train junior technicians.",
        "salaryRange": "$60,000 - $85,000",
        "experienceLevel": "senior",
        "requiredTechnicalSkills": ["Advanced Diagnostics", "All Automotive Systems", "Training", "Quality Control"],
        "requiredSoftSkills": ["Leadership", "Teaching", "Problem Solving", "Customer Relations"],
        "companies": ["Auto Dealerships", "Large Repair Shops", "Fleet Services"],
        "learningPath": "Automotive Technician + Advanced Certifications (8-12 years)",
        "relevanceScore": 80,
        "confidenceLevel": 82,
        "matchReasons": ["Advanced technical expertise", "Leadership role", "Training others"],
        "minExperienceYears": 8,
        "maxExperienceYears": 35,
        "minSalary": 60000,
        "maxSalary": 85000
    },
    {
        "title": "Diesel Mechanic",
        "careerType": "diesel-mechanic",
        "description": "Repair and maintain diesel engines in trucks, buses, construction equipment, and generators.",
        "salaryRange": "$48,000 - $72,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Diesel Engines", "Heavy Equipment", "Hydraulic Systems", "Diagnostic Tools"],
        "requiredSoftSkills": ["Problem Solving", "Physical Stamina", "Attention to Detail", "Safety Awareness"],
        "companies": ["Trucking Companies", "Construction Companies", "Equipment Dealers", "Fleet Services"],
        "learningPath": "Technical School + On-the-Job Training (2-4 years)",
        "relevanceScore": 76,
        "confidenceLevel": 78,
        "matchReasons": ["Heavy equipment expertise", "Specialized skills", "Industrial applications"],
        "minExperienceYears": 0,
        "maxExperienceYears": 35,
        "minSalary": 48000,
        "maxSalary": 72000
    },
    {
        "title": "Automotive Service Advisor",
        "careerType": "automotive-service-advisor",
        "description": "Communicate with customers about vehicle repairs, estimate costs, and coordinate service work.",
        "salaryRange": "$40,000 - $65,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Automotive Knowledge", "Service Writing", "Cost Estimation", "Computer Systems"],
        "requiredSoftSkills": ["Customer Service", "Communication", "Sales Skills", "Problem Solving"],
        "companies": ["Auto Dealerships", "Independent Repair Shops", "Chain Service Centers"],
        "learningPath": "Automotive Knowledge + Customer Service Training (1-3 years)",
        "relevanceScore": 70,
        "confidenceLevel": 72,
        "matchReasons": ["Customer interaction", "Automotive knowledge", "Service coordination"],
        "minExperienceYears": 1,
        "maxExperienceYears": 30,
        "minSalary": 40000,
        "maxSalary": 65000
    },
    {
        "title": "Auto Body Technician",
        "careerType": "auto-body-technician",
        "description": "Repair and restore damaged vehicle bodies, frames, and exterior components.",
        "salaryRange": "$40,000 - $65,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Body Repair", "Welding", "Painting", "Frame Alignment"],
        "requiredSoftSkills": ["Attention to Detail", "Hand-Eye Coordination", "Patience", "Quality Focus"],
        "companies": ["Auto Body Shops", "Dealerships", "Insurance Companies", "Fleet Services"],
        "learningPath": "Technical School + Apprenticeship (2-4 years)",
        "relevanceScore": 72,
        "confidenceLevel": 74,
        "matchReasons": ["Specialized repair skills", "Craftsmanship", "Insurance work"],
        "minExperienceYears": 0,
        "maxExperienceYears": 35,
        "minSalary": 40000,
        "maxSalary": 65000
    },
    {
        "title": "Motorcycle Technician",
        "careerType": "motorcycle-technician",
        "description": "Service, repair, and maintain motorcycles, ATVs, and other recreational vehicles.",
        "salaryRange": "$35,000 - $55,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Motorcycle Engines", "Electrical Systems", "Suspension", "Diagnostic Tools"],
        "requiredSoftSkills": ["Attention to Detail", "Problem Solving", "Customer Service", "Manual Dexterity"],
        "companies": ["Motorcycle Dealerships", "Independent Shops", "Recreational Vehicle Dealers"],
        "learningPath": "Technical School + Manufacturer Training (1-2 years)",
        "relevanceScore": 68,
        "confidenceLevel": 70,
        "matchReasons": ["Specialized niche", "Recreational vehicles", "Technical skills"],
        "minExperienceYears": 0,
        "maxExperienceYears": 30,
        "minSalary": 35000,
        "maxSalary": 55000
    },

    # MANUFACTURING TRADES
    {
        "title": "Machinist",
        "careerType": "machinist",
        "description": "Operate machine tools to produce precision metal parts according to specifications.",
        "salaryRange": "$45,000 - $70,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Machine Tools", "CNC Programming", "Blueprint Reading", "Precision Measurement"],
        "requiredSoftSkills": ["Attention to Detail", "Problem Solving", "Mathematical Skills", "Quality Focus"],
        "companies": ["Manufacturing Companies", "Machine Shops", "Aerospace", "Automotive"],
        "learningPath": "Apprenticeship or Technical School (2-4 years)",
        "relevanceScore": 78,
        "confidenceLevel": 80,
        "matchReasons": ["Precision work", "Technical skills", "Manufacturing expertise"],
        "minExperienceYears": 0,
        "maxExperienceYears": 35,
        "minSalary": 45000,
        "maxSalary": 70000
    },
    {
        "title": "Welder",
        "careerType": "welder",
        "description": "Join metal parts using various welding techniques and equipment for construction and manufacturing.",
        "salaryRange": "$40,000 - $65,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Welding Techniques", "Metal Fabrication", "Blueprint Reading", "Safety Procedures"],
        "requiredSoftSkills": ["Hand-Eye Coordination", "Attention to Detail", "Physical Stamina", "Safety Consciousness"],
        "companies": ["Construction Companies", "Manufacturing", "Shipyards", "Pipeline Companies"],
        "learningPath": "Technical School + Certification (6 months - 2 years)",
        "relevanceScore": 72,
        "confidenceLevel": 75,
        "matchReasons": ["Skilled craftsmanship", "Metal working", "Construction applications"],
        "minExperienceYears": 0,
        "maxExperienceYears": 35,
        "minSalary": 40000,
        "maxSalary": 65000
    },
    {
        "title": "Tool and Die Maker",
        "careerType": "tool-die-maker",
        "description": "Create precision tools, dies, and fixtures used in manufacturing processes.",
        "salaryRange": "$55,000 - $85,000",
        "experienceLevel": "senior",
        "requiredTechnicalSkills": ["Tool Making", "Die Design", "CNC Machining", "Precision Measurement"],
        "requiredSoftSkills": ["Problem Solving", "Attention to Detail", "Mathematical Skills", "Quality Focus"],
        "companies": ["Manufacturing Companies", "Tool Shops", "Automotive", "Aerospace"],
        "learningPath": "Apprenticeship Program (4-5 years)",
        "relevanceScore": 82,
        "confidenceLevel": 85,
        "matchReasons": ["Precision craftsmanship", "Advanced manufacturing", "Specialized expertise"],
        "minExperienceYears": 4,
        "maxExperienceYears": 35,
        "minSalary": 55000,
        "maxSalary": 85000
    },
    {
        "title": "CNC Operator",
        "careerType": "cnc-operator",
        "description": "Operate computer-controlled machine tools to produce precision parts and components.",
        "salaryRange": "$40,000 - $60,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["CNC Operation", "Machine Setup", "Quality Control", "Blueprint Reading"],
        "requiredSoftSkills": ["Attention to Detail", "Problem Solving", "Mathematical Skills", "Safety Consciousness"],
        "companies": ["Manufacturing Companies", "Machine Shops", "Aerospace", "Medical Device"],
        "learningPath": "Technical School + On-the-Job Training (1-2 years)",
        "relevanceScore": 75,
        "confidenceLevel": 78,
        "matchReasons": ["Precision manufacturing", "Technology operation", "Quality focus"],
        "minExperienceYears": 0,
        "maxExperienceYears": 30,
        "minSalary": 40000,
        "maxSalary": 60000
    },
    {
        "title": "Quality Control Inspector",
        "careerType": "quality-control-inspector",
        "description": "Inspect manufactured products and materials to ensure they meet quality standards.",
        "salaryRange": "$38,000 - $58,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Quality Control", "Measurement Tools", "Statistical Analysis", "Documentation"],
        "requiredSoftSkills": ["Attention to Detail", "Analytical Thinking", "Communication", "Problem Solving"],
        "companies": ["Manufacturing Companies", "Aerospace", "Automotive", "Medical Device"],
        "learningPath": "Technical Training + Quality Certification (1-2 years)",
        "relevanceScore": 72,
        "confidenceLevel": 74,
        "matchReasons": ["Quality assurance", "Analytical work", "Manufacturing support"],
        "minExperienceYears": 0,
        "maxExperienceYears": 30,
        "minSalary": 38000,
        "maxSalary": 58000
    },
    {
        "title": "Industrial Maintenance Technician",
        "careerType": "industrial-maintenance-technician",
        "description": "Maintain and repair industrial equipment, machinery, and systems in manufacturing facilities.",
        "salaryRange": "$50,000 - $75,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Mechanical Systems", "Electrical Systems", "Hydraulics", "Preventive Maintenance"],
        "requiredSoftSkills": ["Problem Solving", "Safety Consciousness", "Time Management", "Teamwork"],
        "companies": ["Manufacturing Plants", "Chemical Companies", "Food Processing", "Power Plants"],
        "learningPath": "Technical School + Industrial Training (2-4 years)",
        "relevanceScore": 78,
        "confidenceLevel": 80,
        "matchReasons": ["Multi-skilled maintenance", "Industrial environment", "Problem solving"],
        "minExperienceYears": 0,
        "maxExperienceYears": 35,
        "minSalary": 50000,
        "maxSalary": 75000
    },
    {
        "title": "Millwright",
        "careerType": "millwright",
        "description": "Install, maintain, and repair industrial machinery and equipment in manufacturing facilities.",
        "salaryRange": "$55,000 - $80,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Machinery Installation", "Alignment", "Rigging", "Mechanical Systems"],
        "requiredSoftSkills": ["Problem Solving", "Physical Stamina", "Precision", "Safety Consciousness"],
        "companies": ["Manufacturing Plants", "Power Plants", "Paper Mills", "Steel Mills"],
        "learningPath": "Apprenticeship Program (4 years)",
        "relevanceScore": 76,
        "confidenceLevel": 78,
        "matchReasons": ["Specialized machinery skills", "Industrial applications", "Problem solving"],
        "minExperienceYears": 0,
        "maxExperienceYears": 35,
        "minSalary": 55000,
        "maxSalary": 80000
    },
    {
        "title": "Sheet Metal Worker",
        "careerType": "sheet-metal-worker",
        "description": "Fabricate, install, and maintain sheet metal products for construction and manufacturing.",
        "salaryRange": "$45,000 - $70,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Sheet Metal Fabrication", "Welding", "Blueprint Reading", "HVAC Systems"],
        "requiredSoftSkills": ["Attention to Detail", "Physical Stamina", "Problem Solving", "Safety Consciousness"],
        "companies": ["HVAC Contractors", "Construction Companies", "Manufacturing", "Aerospace"],
        "learningPath": "Apprenticeship Program (4 years)",
        "relevanceScore": 74,
        "confidenceLevel": 76,
        "matchReasons": ["Metal fabrication skills", "Construction applications", "HVAC integration"],
        "minExperienceYears": 0,
        "maxExperienceYears": 35,
        "minSalary": 45000,
        "maxSalary": 70000
    },
    {
        "title": "Boilermaker",
        "careerType": "boilermaker",
        "description": "Assemble, install, and repair boilers, closed vats, and other large vessels for industrial use.",
        "salaryRange": "$60,000 - $90,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Welding", "Metal Fabrication", "Blueprint Reading", "Rigging"],
        "requiredSoftSkills": ["Physical Stamina", "Safety Consciousness", "Attention to Detail", "Teamwork"],
        "companies": ["Power Plants", "Chemical Plants", "Refineries", "Manufacturing"],
        "learningPath": "Apprenticeship Program (4 years)",
        "relevanceScore": 78,
        "confidenceLevel": 80,
        "matchReasons": ["Specialized industrial skills", "High-pressure systems", "Good compensation"],
        "minExperienceYears": 0,
        "maxExperienceYears": 35,
        "minSalary": 60000,
        "maxSalary": 90000
    },

    # ADDITIONAL SPECIALIZED TRADES
    {
        "title": "Locksmith",
        "careerType": "locksmith",
        "description": "Install, repair, and maintain locks, security systems, and access control devices.",
        "salaryRange": "$35,000 - $55,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Lock Mechanisms", "Security Systems", "Key Cutting", "Electronic Access"],
        "requiredSoftSkills": ["Problem Solving", "Customer Service", "Attention to Detail", "Trustworthiness"],
        "companies": ["Locksmith Services", "Security Companies", "Hardware Stores", "Self-Employed"],
        "learningPath": "Technical Training + Apprenticeship (1-2 years)",
        "relevanceScore": 68,
        "confidenceLevel": 70,
        "matchReasons": ["Security specialty", "Problem solving", "Customer service"],
        "minExperienceYears": 0,
        "maxExperienceYears": 30,
        "minSalary": 35000,
        "maxSalary": 55000
    },
    {
        "title": "Glazier",
        "careerType": "glazier",
        "description": "Install and replace glass in windows, doors, storefronts, and other structures.",
        "salaryRange": "$40,000 - $65,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Glass Installation", "Measuring", "Cutting Tools", "Sealants"],
        "requiredSoftSkills": ["Attention to Detail", "Physical Stamina", "Safety Consciousness", "Precision"],
        "companies": ["Glass Companies", "Construction Companies", "Window Manufacturers"],
        "learningPath": "Apprenticeship or On-the-Job Training (3-4 years)",
        "relevanceScore": 70,
        "confidenceLevel": 72,
        "matchReasons": ["Specialized installation", "Construction applications", "Precision work"],
        "minExperienceYears": 0,
        "maxExperienceYears": 35,
        "minSalary": 40000,
        "maxSalary": 65000
    },
    {
        "title": "Insulation Worker",
        "careerType": "insulation-worker",
        "description": "Install insulation materials in buildings and industrial equipment for energy efficiency.",
        "salaryRange": "$38,000 - $58,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Insulation Materials", "Installation Techniques", "Safety Procedures", "Energy Efficiency"],
        "requiredSoftSkills": ["Physical Stamina", "Attention to Detail", "Safety Consciousness", "Teamwork"],
        "companies": ["Insulation Contractors", "Construction Companies", "Industrial Contractors"],
        "learningPath": "On-the-Job Training (6 months - 1 year)",
        "relevanceScore": 66,
        "confidenceLevel": 68,
        "matchReasons": ["Energy efficiency focus", "Construction specialty", "Growing demand"],
        "minExperienceYears": 0,
        "maxExperienceYears": 30,
        "minSalary": 38000,
        "maxSalary": 58000
    },
    {
        "title": "Elevator Technician",
        "careerType": "elevator-technician",
        "description": "Install, maintain, and repair elevators, escalators, and other lifting equipment.",
        "salaryRange": "$70,000 - $100,000",
        "experienceLevel": "senior",
        "requiredTechnicalSkills": ["Elevator Systems", "Electrical Controls", "Hydraulics", "Safety Systems"],
        "requiredSoftSkills": ["Problem Solving", "Safety Consciousness", "Attention to Detail", "Physical Fitness"],
        "companies": ["Elevator Companies", "Maintenance Contractors", "Building Services"],
        "learningPath": "Apprenticeship Program (4 years)",
        "relevanceScore": 82,
        "confidenceLevel": 85,
        "matchReasons": ["Specialized high-tech trade", "Excellent compensation", "Safety critical"],
        "minExperienceYears": 4,
        "maxExperienceYears": 35,
        "minSalary": 70000,
        "maxSalary": 100000
    }
]