"""
Skilled Trades & Construction Career Database
Part of comprehensive career database expansion - Phase 1A
"""

SKILLED_TRADES_CAREERS = [
    # ELECTRICAL TRADES
    {
        "title": "Electrician",
        "careerType": "electrician",
        "description": "Install, maintain, and repair electrical systems in residential, commercial, and industrial settings.",
        "salaryRange": "$55,000 - $85,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Electrical Systems", "Wiring", "Electrical Codes", "Troubleshooting"],
        "requiredSoftSkills": ["Problem Solving", "Attention to Detail", "Physical Stamina", "Safety Consciousness"],
        "companies": ["Electrical Contractors", "Construction Companies", "Utilities", "Manufacturing"],
        "learningPath": "Apprenticeship Program (4 years) + Licensing",
        "relevanceScore": 78,
        "confidenceLevel": 80,
        "matchReasons": ["Technical skills", "Hands-on work", "Problem solving"],
        "minExperienceYears": 0,
        "maxExperienceYears": 40,
        "minSalary": 55000,
        "maxSalary": 85000
    },
    {
        "title": "Master Electrician",
        "careerType": "master-electrician",
        "description": "Lead electrical projects, supervise apprentices, design electrical systems, ensure code compliance.",
        "salaryRange": "$75,000 - $110,000",
        "experienceLevel": "senior",
        "requiredTechnicalSkills": ["Advanced Electrical Systems", "Project Management", "Electrical Design", "Code Compliance"],
        "requiredSoftSkills": ["Leadership", "Teaching", "Project Management", "Business Skills"],
        "companies": ["Electrical Contractors", "Construction Companies", "Own Business"],
        "learningPath": "Journeyman + Additional Experience + Master License (8+ years)",
        "relevanceScore": 82,
        "confidenceLevel": 85,
        "matchReasons": ["Advanced technical expertise", "Leadership role", "Business ownership potential"],
        "minExperienceYears": 8,
        "maxExperienceYears": 40,
        "minSalary": 75000,
        "maxSalary": 110000
    },
    {
        "title": "Electrical Engineer",
        "careerType": "electrical-engineer",
        "description": "Design electrical systems, develop electrical components, oversee electrical projects and installations.",
        "salaryRange": "$85,000 - $130,000",
        "experienceLevel": "senior",
        "requiredTechnicalSkills": ["Electrical Engineering", "Circuit Design", "Power Systems", "CAD Software"],
        "requiredSoftSkills": ["Analytical Thinking", "Problem Solving", "Communication", "Project Management"],
        "companies": ["Engineering Firms", "Utilities", "Manufacturing", "Construction"],
        "learningPath": "Bachelor's in Electrical Engineering + PE License (4-6 years)",
        "relevanceScore": 85,
        "confidenceLevel": 88,
        "matchReasons": ["Engineering background", "Technical design", "System thinking"],
        "minExperienceYears": 4,
        "maxExperienceYears": 35,
        "minSalary": 85000,
        "maxSalary": 130000
    },

    # PLUMBING & HVAC
    {
        "title": "Plumber",
        "careerType": "plumber",
        "description": "Install, repair, and maintain plumbing systems, pipes, fixtures, and water systems.",
        "salaryRange": "$50,000 - $80,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Plumbing Systems", "Pipe Installation", "Water Systems", "Plumbing Codes"],
        "requiredSoftSkills": ["Problem Solving", "Physical Stamina", "Customer Service", "Attention to Detail"],
        "companies": ["Plumbing Contractors", "Construction Companies", "Maintenance Companies", "Self-Employed"],
        "learningPath": "Apprenticeship Program (4-5 years) + Licensing",
        "relevanceScore": 75,
        "confidenceLevel": 78,
        "matchReasons": ["Hands-on work", "Problem solving", "Essential services"],
        "minExperienceYears": 0,
        "maxExperienceYears": 40,
        "minSalary": 50000,
        "maxSalary": 80000
    },
    {
        "title": "HVAC Technician",
        "careerType": "hvac-technician",
        "description": "Install, maintain, and repair heating, ventilation, and air conditioning systems.",
        "salaryRange": "$48,000 - $75,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["HVAC Systems", "Refrigeration", "Electrical Components", "System Diagnostics"],
        "requiredSoftSkills": ["Problem Solving", "Customer Service", "Physical Stamina", "Attention to Detail"],
        "companies": ["HVAC Contractors", "Construction Companies", "Facilities Management", "Self-Employed"],
        "learningPath": "Technical School + Apprenticeship (2-4 years) + Certification",
        "relevanceScore": 76,
        "confidenceLevel": 78,
        "matchReasons": ["Technical systems", "Problem solving", "Growing demand"],
        "minExperienceYears": 0,
        "maxExperienceYears": 35,
        "minSalary": 48000,
        "maxSalary": 75000
    },
    {
        "title": "Master Plumber",
        "careerType": "master-plumber",
        "description": "Lead plumbing projects, supervise teams, design plumbing systems, run plumbing business.",
        "salaryRange": "$70,000 - $105,000",
        "experienceLevel": "senior",
        "requiredTechnicalSkills": ["Advanced Plumbing", "System Design", "Project Management", "Business Operations"],
        "requiredSoftSkills": ["Leadership", "Business Management", "Customer Relations", "Teaching"],
        "companies": ["Plumbing Contractors", "Construction Companies", "Own Business"],
        "learningPath": "Journeyman + Experience + Master License (8+ years)",
        "relevanceScore": 80,
        "confidenceLevel": 82,
        "matchReasons": ["Advanced expertise", "Business ownership", "Leadership role"],
        "minExperienceYears": 8,
        "maxExperienceYears": 40,
        "minSalary": 70000,
        "maxSalary": 105000
    },

    # CONSTRUCTION TRADES
    {
        "title": "Carpenter",
        "careerType": "carpenter",
        "description": "Build, install, and repair structures and fixtures made from wood and other materials.",
        "salaryRange": "$45,000 - $70,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Carpentry", "Woodworking", "Construction Tools", "Blueprint Reading"],
        "requiredSoftSkills": ["Attention to Detail", "Physical Stamina", "Problem Solving", "Craftsmanship"],
        "companies": ["Construction Companies", "Contractors", "Furniture Makers", "Self-Employed"],
        "learningPath": "Apprenticeship or On-the-Job Training (3-4 years)",
        "relevanceScore": 72,
        "confidenceLevel": 75,
        "matchReasons": ["Hands-on craftsmanship", "Building and creating", "Practical skills"],
        "minExperienceYears": 0,
        "maxExperienceYears": 40,
        "minSalary": 45000,
        "maxSalary": 70000
    },
    {
        "title": "Construction Manager",
        "careerType": "construction-manager",
        "description": "Oversee construction projects, manage teams, ensure safety and quality, coordinate schedules.",
        "salaryRange": "$85,000 - $130,000",
        "experienceLevel": "senior",
        "requiredTechnicalSkills": ["Construction Management", "Project Planning", "Safety Regulations", "Cost Estimation"],
        "requiredSoftSkills": ["Leadership", "Communication", "Problem Solving", "Organization"],
        "companies": ["Construction Companies", "General Contractors", "Real Estate Developers"],
        "learningPath": "Construction Experience + Management Training (8-12 years)",
        "relevanceScore": 82,
        "confidenceLevel": 85,
        "matchReasons": ["Project management", "Leadership role", "Construction expertise"],
        "minExperienceYears": 8,
        "maxExperienceYears": 35,
        "minSalary": 85000,
        "maxSalary": 130000
    },
    {
        "title": "Mason",
        "careerType": "mason",
        "description": "Build structures with brick, stone, concrete blocks, and other masonry materials.",
        "salaryRange": "$42,000 - $65,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Masonry", "Bricklaying", "Stone Work", "Mortar Mixing"],
        "requiredSoftSkills": ["Physical Stamina", "Attention to Detail", "Craftsmanship", "Patience"],
        "companies": ["Construction Companies", "Masonry Contractors", "Restoration Companies", "Self-Employed"],
        "learningPath": "Apprenticeship or On-the-Job Training (3-4 years)",
        "relevanceScore": 70,
        "confidenceLevel": 72,
        "matchReasons": ["Traditional craftsmanship", "Building skills", "Artistic elements"],
        "minExperienceYears": 0,
        "maxExperienceYears": 40,
        "minSalary": 42000,
        "maxSalary": 65000
    },
    {
        "title": "Roofer",
        "careerType": "roofer",
        "description": "Install, repair, and maintain roofs using various materials and techniques.",
        "salaryRange": "$40,000 - $65,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Roofing Systems", "Material Installation", "Safety Procedures", "Weather Sealing"],
        "requiredSoftSkills": ["Physical Stamina", "Balance", "Attention to Detail", "Safety Consciousness"],
        "companies": ["Roofing Contractors", "Construction Companies", "Self-Employed"],
        "learningPath": "On-the-Job Training or Apprenticeship (2-3 years)",
        "relevanceScore": 68,
        "confidenceLevel": 70,
        "matchReasons": ["Specialized trade", "Physical work", "Weather protection expertise"],
        "minExperienceYears": 0,
        "maxExperienceYears": 35,
        "minSalary": 40000,
        "maxSalary": 65000
    },

    # AUTOMOTIVE TRADES
    {
        "title": "Automotive Technician",
        "careerType": "automotive-technician",
        "description": "Diagnose, repair, and maintain automobiles and light trucks using computerized diagnostic equipment.",
        "salaryRange": "$42,000 - $65,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Automotive Repair", "Diagnostic Equipment", "Engine Systems", "Electrical Systems"],
        "requiredSoftSkills": ["Problem Solving", "Attention to Detail", "Customer Service", "Continuous Learning"],
        "companies": ["Auto Dealerships", "Independent Repair Shops", "Fleet Services", "Tire Centers"],
        "learningPath": "Technical School + ASE Certification (1-2 years)",
        "relevanceScore": 75,
        "confidenceLevel": 78,
        "matchReasons": ["Mechanical aptitude", "Problem solving", "Technology integration"],
        "minExperienceYears": 0,
        "maxExperienceYears": 35,
        "minSalary": 42000,
        "maxSalary": 65000
    },
    {
        "title": "Master Automotive Technician",
        "careerType": "master-automotive-technician",
        "description": "Lead automotive repair teams, handle complex diagnostics, train junior technicians.",
        "salaryRange": "$60,000 - $85,000",
        "experienceLevel": "senior",
        "requiredTechnicalSkills": ["Advanced Diagnostics", "All Automotive Systems", "Training", "Quality Control"],
        "requiredSoftSkills": ["Leadership", "Teaching", "Problem Solving", "Customer Relations"],
        "companies": ["Auto Dealerships", "Large Repair Shops", "Fleet Services"],
        "learningPath": "Automotive Technician + Advanced Certifications (8-12 years)",
        "relevanceScore": 80,
        "confidenceLevel": 82,
        "matchReasons": ["Advanced technical expertise", "Leadership role", "Training others"],
        "minExperienceYears": 8,
        "maxExperienceYears": 35,
        "minSalary": 60000,
        "maxSalary": 85000
    },
    {
        "title": "Diesel Mechanic",
        "careerType": "diesel-mechanic",
        "description": "Repair and maintain diesel engines in trucks, buses, construction equipment, and generators.",
        "salaryRange": "$48,000 - $72,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Diesel Engines", "Heavy Equipment", "Hydraulic Systems", "Diagnostic Tools"],
        "requiredSoftSkills": ["Problem Solving", "Physical Stamina", "Attention to Detail", "Safety Awareness"],
        "companies": ["Trucking Companies", "Construction Companies", "Equipment Dealers", "Fleet Services"],
        "learningPath": "Technical School + On-the-Job Training (2-4 years)",
        "relevanceScore": 76,
        "confidenceLevel": 78,
        "matchReasons": ["Heavy equipment expertise", "Specialized skills", "Industrial applications"],
        "minExperienceYears": 0,
        "maxExperienceYears": 35,
        "minSalary": 48000,
        "maxSalary": 72000
    },

    # MANUFACTURING TRADES
    {
        "title": "Machinist",
        "careerType": "machinist",
        "description": "Operate machine tools to produce precision metal parts according to specifications.",
        "salaryRange": "$45,000 - $70,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Machine Tools", "CNC Programming", "Blueprint Reading", "Precision Measurement"],
        "requiredSoftSkills": ["Attention to Detail", "Problem Solving", "Mathematical Skills", "Quality Focus"],
        "companies": ["Manufacturing Companies", "Machine Shops", "Aerospace", "Automotive"],
        "learningPath": "Apprenticeship or Technical School (2-4 years)",
        "relevanceScore": 78,
        "confidenceLevel": 80,
        "matchReasons": ["Precision work", "Technical skills", "Manufacturing expertise"],
        "minExperienceYears": 0,
        "maxExperienceYears": 35,
        "minSalary": 45000,
        "maxSalary": 70000
    },
    {
        "title": "Welder",
        "careerType": "welder",
        "description": "Join metal parts using various welding techniques and equipment for construction and manufacturing.",
        "salaryRange": "$40,000 - $65,000",
        "experienceLevel": "mid",
        "requiredTechnicalSkills": ["Welding Techniques", "Metal Fabrication", "Blueprint Reading", "Safety Procedures"],
        "requiredSoftSkills": ["Hand-Eye Coordination", "Attention to Detail", "Physical Stamina", "Safety Consciousness"],
        "companies": ["Construction Companies", "Manufacturing", "Shipyards", "Pipeline Companies"],
        "learningPath": "Technical School + Certification (6 months - 2 years)",
        "relevanceScore": 72,
        "confidenceLevel": 75,
        "matchReasons": ["Skilled craftsmanship", "Metal working", "Construction applications"],
        "minExperienceYears": 0,
        "maxExperienceYears": 35,
        "minSalary": 40000,
        "maxSalary": 65000
    },
    {
        "title": "Tool and Die Maker",
        "careerType": "tool-die-maker",
        "description": "Create precision tools, dies, and fixtures used in manufacturing processes.",
        "salaryRange": "$55,000 - $85,000",
        "experienceLevel": "senior",
        "requiredTechnicalSkills": ["Tool Making", "Die Design", "CNC Machining", "Precision Measurement"],
        "requiredSoftSkills": ["Problem Solving", "Attention to Detail", "Mathematical Skills", "Quality Focus"],
        "companies": ["Manufacturing Companies", "Tool Shops", "Automotive", "Aerospace"],
        "learningPath": "Apprenticeship Program (4-5 years)",
        "relevanceScore": 82,
        "confidenceLevel": 85,
        "matchReasons": ["Precision craftsmanship", "Advanced manufacturing", "Specialized expertise"],
        "minExperienceYears": 4,
        "maxExperienceYears": 35,
        "minSalary": 55000,
        "maxSalary": 85000
    }
]